### ISSUE TITLE
Review and Scope IBM Quantum Accelerator 

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#1008]
We need to spend time scoping v1.0 + identifying resource needs

**Comment by pandasa123** [comment]
@lerongil, we've [reviewed it here](https://ibm.box.com/s/pjx6mrsdhubodd0z98mw8hsv1nm9au06)

**Comment by JRussellHuffman** [comment]
Can the content from that box note be captured in a github issue so that we can start scoping it?

**Comment by pandasa123** [comment]
@JRussellHuffman, I copied it over into [here](https://github.com/Qiskit/platypus/issues/380)

**Comment by JRussellHuffman** [comment]
Awesome, thanks. I added a "needs grooming" label to it.
