### ISSUE TITLE
Investigate / Review Professor Portal

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#1009]
## Background

Educators (Professors, IBM) need a way to track student progress across readings, quizzes, labs, etc. 

## Goal

> From a product perspective, this is revisiting #380, understanding how both audiences align and scoping this down a bit. From a dev perspective, we need to turn on the Teacher Experience and investigate how progress tracking works

## Sized Use Cases

- [ ] Creation of roles (Backend)
   - professor, student
   - size: M 
- [ ] Creation of a cohort (Backend) 
   - relation to classes and students 
   - size: M
- [ ] Enrolling into a cohort (UI & Process) 
   - bulk registration by a professor 
   - self registration by a students
   - size: L
- [ ] *Class Visibility - Professor (Backend)**
   - relations between class and cohorts
   - remove students from a cohort 
   - size: M 
- [ ] *Class Visibility - Professor (UI)*
   - admin panel to add and remove classes to cohorts 
   - Size: L
- [ ] Student View (UI)
   - Navigation (Learning vs Cohort specific class page)
   - Completion of chapters from class visibility
   - Permissions based on cohort
   - Size: L
- [ ] Progress Tracking (Data / Backend)
   - Reading + Completion date: Mathigon
   - Questions + Completion date: Mathigon API
   - Number of attempts + date: new
   - Size: XL
- [ ] Progress Tracking (UI)
   - Create UI for tracking on admin 
   - Reading completion by student
   - Question completion by student
   - Table view, Graph view?
   - Filter by course
   - Size: XL
- [ ] *Country Control (Backend)*
   - Only applicable to cohorts owned by IBM Delivery Leads, Extend Cohort model for "require country"
   - List of countries + check logic
   - Extend Student Model
   - Size: L
- [ ] *Country Control (UI)*
   - If students want to join a cohort AND cohort requires a country limit, students must add their country 
   - UI for students to provide country
   - UI for professors to see the user country in panel
   - Admin panel to show blocked student by delivery lead
   - Size L

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
