### ISSUE TITLE
Update `CodeCell` component to expand / grow with code 

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1019]
Question:
- Should this happen for all code cells?
- What happens when the `CodeCell` reaches the full height of the viewport?
- test mobile and tablet

[Design shown here](https://www.figma.com/file/tEpo1ZT4O7txFUT2aI0QAM/252-Python-Scratchpad?node-id=50%3A773)

**Comment by frankharkins** [comment]
> What happens when the CodeCell reaches the full height of the viewport?

IMO the code cells should be consistent with those in notebooks, i.e. the viewport scrolls
