### ISSUE TITLE
Formula characters colliding and overlapping (in Safari)

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1022]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-algorithms/quantum-teleportation
2. scroll down to Step 2
3. See how the parenthesis characters `(` collides with other characters

### What is the expected behavior?
All characters within any formula should render with its own proper spacing

### Screenshots (optional but very helpful)
<img width="839" alt="153448896-7bed5286-bf44-46e7-a7cc-67a3107a0c11" src="https://user-images.githubusercontent.com/6276074/168841128-fcdf32bb-61f0-41b4-ac87-5692c23f50dc.png">

### Environment (optional but very helpful)
 - Device: Mac OS
 - Browser: Safari

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
