### ISSUE TITLE
Add Indonesian as a Language to platypus/LOCALIZATION_CONTRIBUTORS

### ISSUE THREAD

**Issue by hanifanrn** [Qiskit/platypus#1026]
Add Indonesian

Hanifan Rizki Nurahman | Hanifanrn

**Comment by 0sophy1** [comment]
Hi @hanifanrn can we close this issue? Thanks!

**Comment by hanifanrn** [comment]
> Hi @hanifanrn can we close this issue? Thanks!

Sure, thanks for the support!
