### ISSUE TITLE
progress tracking on "why quantum"

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#1035]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/introduction/why-quantum-computing
2. Scroll down to first multiple-choice question
3. Click on correct answer
4. See error of progress not  icon not advancing

### What is the current behavior?

Progress icon does not indicate progress

### What is the expected behavior?

Progress icon should fill when up when the multiple-choice question is correctly answered

### Screenshots (optional but very helpful)
<img width="985" alt="Screen Shot 2022-05-17 at 3 28 55 PM" src="https://user-images.githubusercontent.com/7633881/169066665-b8d6e727-f808-41b1-b7b5-fdfb022298ab.png">

### Environment (optional but very helpful)
 - Device: laptop (macbook pro)
 - OS: MacOS
 - Browser: Firefox. It works fine in Chrome

### Additional context (optional)

This seems to be an issue specific to Firefox. Other pages with progress tracking still work just fine.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
