### ISSUE TITLE
[Code Cell UX] Connection to the kernels die after time

### ISSUE THREAD

**Issue by korgan00** [Qiskit/platypus#1038]
### Steps to reproduce the problem
Enter any page with a coding exercise, wait about 20 minutes.

### What is the current behavior?
The connection no longer works.

### What is the expected behavior?
It should work or have a button to reconnect.

**Comment by JRussellHuffman** [comment]
The ideal version is that the kernel doesn't die, but if it does, what options do we have? Can we know if the user hasn't run any code in the last 20 minutes? If so, could we include some sort of notification that they would need to refresh the page?

<img width="958" alt="Screen Shot 2022-06-27 at 3 50 32 PM" src="https://user-images.githubusercontent.com/7633881/176033293-5701a3ae-16a2-4bae-9ae4-d61620e75618.png">

Do we have any options other than asking them to refresh the page?

**Comment by vabarbosa** [comment]
a brief summary of the discussion we had around this (@korgan00 @Tansito @JRussellHuffman @techtolentino feel free to correct me or add anything i may have missed):

in the immediate term, we should try to see if we can

- determine (or get notified of) when the kernel has died and connection is lost/broken
- determine if  we can force a re-establish/re-connect to a kernel (w/o refreshing page)
- display the notification above (when user tries to run after kernel has died) and allow the user to refresh the page (the design/styling of the message should align with that of the [API key is missing notification](https://github.com/Qiskit/platypus/issues/1336#issuecomment-1183380170))
     - if we can re-establish connection with a kernel then the button/link just reconnect to kernel
     - if we cannot then the button/link refreshes the entire page

for further consideration (follow-up work/issue)

- keep track of executed code block on the page or have a way to determine what code blocks have been ran
- after re-connecting to a kernel re-run all previously ran code blocks on the page

**Comment by vabarbosa** [comment]
should we re-open this issue or create a new to not lose track of the long term update?

my take is the initial issue was a bug which you resolved in #1379 (thank you!).
the idea of re-connecting/re-running previously ran cells i see more as an enhancement/feature which should be tracked in a new issue. thoughts?

**Comment by Tansito** [comment]
I agree, I also see it as improvement so I put my two cents for a new issue.
