### ISSUE TITLE
[DevOps] Preview clean process is failing due to permissions

### ISSUE THREAD

**Issue by Tansito** [Qiskit/platypus#1050]
### Steps to reproduce the problem

1. Close a PR
2. Preview clean process is failing due to some kind of lack permissions

### What is the current behavior?

The clean process is not being executed correctly.

### What is the expected behavior?

The image should be removed from the registry once time the PR is closed.

### Screenshots

<img width="640" alt="Screenshot 2022-05-24 at 16 43 14" src="https://user-images.githubusercontent.com/9059044/170064765-63b14e6a-3707-4bfa-a548-01a25b3298a5.png">

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
