### ISSUE TITLE
As a Student, I want to complete an Assessment, so I can measure my comprehension

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#1079]
### Background

Professors need a way to test their students with MCQs + FRQs. Assessments are a collection of these problems, but with specific "test-taking" experiences. This user story is focusing on the student aspect 

Related:

- [Problem Sets Bank](https://github.com/Qiskit/platypus/issues/1259)
- [Problem Set Bank collection](https://github.com/Qiskit/platypus/issues/1260)
- [Integrations into Syllabus](https://github.com/Qiskit/platypus/issues/667)

### Goal

Students should be able to take an exam on Qiskit Learning Platform...this should match Professor expectations for their classrooms

### Acceptance criteria

**Taking the exam**

- [ ] Students should not be able to see if their MCQs are correct until they submit their Assessment
- [ ] Students should not be able to see if their FRQs are correct until they submit their Assessment until they click Grade

**After the exam**

- [ ] Students should be able to see how they did on the entire assessment...this could be with a score / certificate / badge?

### Out of scope

- Timed Exams (for right now)...we can use Amplitude Session Data for now? 
- Scheduled Exam (this could be out of scope right now since we're not letting Professors configure it at the moment?)
- Professors creating custom assessment is out of scope
- Professors receiving student grades (for now)
- Generating new questions...we should be using existing questions only 
- Test Bank that rotates. This is a priority, but we shouldn't worry about this for the experience MVP

### Open questions

- [ ] Where should this live accessibly?
- [x] How can we integrate this into a Syllabus? Is it a case of adding a dropdown to Syllabus that allows Profs to flip between Content, Tutorials, Problems? 
- [ ] How can we store this centrally so it's easy for Professors and Students to peruse through problems? (probably a later date)
- [ ] **What does a Test Bank look? What does a Syllabus bank look?** Professors should be able to peruse and adapt to their class

### Resources

- Qiskit Challenges 
- Qiskit Labs
- Textbook MCQs
- Related discussion on [Problem Set Banks](https://github.com/Qiskit/platypus/issues/1259) and [Integrations into Syllabus](https://github.com/Qiskit/platypus/issues/667) and...these will have some similarities but first, let's define what an Assessment is with pre-made examples and then figure out how Professors can pick them _and then_ create their own 
- There's some additional, [recent discussions](https://github.com/Qiskit/platypus/issues/972) with Professors here as well

**Comment by pandasa123** [comment]
**UC Davis**

- 3 quarters, grad with IBM Quantum
- Last quarter, undergrad (38, some joined grad)
    - 6 depts: physics, applied physics, maths, computer science, etc.
- 1/3 was software
- Weekly assignment, homework for undergrad
- IBM material was important for graduates 
    - Coding with Qiskit
    - Take literature experiments and implement on Qiskit
    - Quantum Supremacy on IBM Quantum systems
    - First paper on entanglement and answer questions about hidden states
- Undergrad focuses on Quantum Algorithms
    - Foundations, all the way to Shor
    - Starting only with Linear 
    - Professor taught lecture and concepts 
    - 20 students go to lab 
    - Used Textbook original rather than beta since it gives a good prescriptive guideline
    - Liked how it got into mechanics first and then chapters
    - Inspired by Qiskit’s in-context MCQs
    - I enjoy explaining Deutch-Josza, Amplitude Amplification, Shor’s
    - It would be great for educators if there was more exercises
        - Specifically, more computational exercises 
        - I can use them as a base for my own
- I use Bob Sutor’s Dancing with Qubits
    - Students want to practice alone by themselves…I have to assign another one myself since there’s only one per chapter
- Students feel more comfortable as they have more
- “If you change this state, what is the quantum”, “chronicle product”




- What do you use if you don’t use Nielsin? David McMackin “Quantum Computing Explained”



Participation — professors take a very hands on approach asking people

Midterm + final exam —

Project — choose your own adventure and make a video

Homeworks + Labs — graded by graders, or lab graders 

12 hours a week: 3 hours in lecture, 1 hour in lab, 8 hours homework (5 - 6 hours)

Zybooks -- syllabus is amazing. They get a report too and use it for preparation. Students feel seen (required points). Qiskit has great content, assigning to students, when are submissions done. Problems are synchronisation with Canvas is broken

Canvas is very very important. But this is advantageous enough that I’ll use this! 

Practice exam -- background knowledge survey, exam, is it possible to randomise five options (test bank), prevent cheating (timed, one problem at a time), end of course survey (ungraded, retained)

**Comment by pandasa123** [comment]
Wyoming

- Professor in CE, HPC, Networks, AR, ML. 
    - Lots of grants for developing GPU + HPC use cases Weather Company
- Last year, introduction QC course at UG + Grad students
    - Focused on Computing rather than Physics — 16 students
    - Content was split between theory + maths, and then a physics faculty to talk about hardware, and then implement maths on Qiskit simulators
    - There’s a limit to simulation with qubit limitations and then they introduced students to Systems. Learnt about code optimisations with Deutch-Joza, VB, QFT algorithms (since lots of EE students), crypto, and ended class with Shor’s algorithms
- Couldn’t show them Pulse
- They could do everything on Simulators…but they needed to understand that it’s not perfect.
    - They first code a 4 bit ripple adder, and re-code it for a 8 bit ripple adder
    - They ran algorithms as well
- They first ran on sims with 8Q, and then they ran it on a 6Q systems
    - Half the class knew CUDA 


Success

- Every assignment had a few parts: proving maths to demonstrate fundamental understanding, improving template code, running on a system and optimising
- If a UG student understood the math and ran on a sim, then they’re successful
- Grad students should be able to do everything, especially 


- 6 assignments, each student has 1 - 2 weeks to finish. Prof writes it in JupyterLab Notebooks. Constraints
- It’s important to relate back to the actual hardware and understand what’s going on with optimisation tools


Grading

- I need to see the circuit
- They need to explain how they compare theirs vs IBM’s adder…characteristics
- Statevector distributions simulators 


Challenges

- Lack of proper textbooks
- Usually it’s written by physicists and it’s very very difficult to understand
- Then there’s computing textbooks but it’s too low level
- The Textbook isn’t deep enough. It’s enough to get excited but they need to understand why they’re doing and how they’re doing, rather than output 
- I wrote all the material over the course of 3 / 4 years based on reading books that had some hardware info. Must’ve 15 books   
Educator’s Program

- I was in contact with IBMers ~4 years…I was the director of QC centre
- Initially, the Educator’s Program had issues submitting jobs with Qiskit errors
- Then students had a hard time with job scheduling
- Last 20 minutes of the course, I’d walk them through a job and errors 

Things for the future

- I think a hardware document would be interesting: focusing on the architecture rather than the physics. Topology, connecting to control electronics
- Next semester, I’m going to focus on ML 
- I am an Nvidia Certified Instructor. I make it a requirement that they’re certified

**Comment by pandasa123** [comment]
Harrisburg

Alex (Harrisburg)

- MIT XPro course in 2019

- Started teaching at Harrisburg in 2020
- Initially, students would run things individually and it took forever to wait in queue. Worked with Bob Sutor, and then signed up for Educators Program
- It's worked out really well
- We're doing preparation and education before students interact with a quantum computer and then get hands on. Once it's time, they schedule time on a QPU
- Students are doing it at the same time and then get results in a few minutes

- We used to have access to a 16Q system (Melbourne) and they miss it. I mostly use 5Q / 7Q (Casablanca) and teaching simple stuff like Berstein / Vazerani / Teleportation. I was teaching how to do an Adder circuit. With 9Q, I can do a 3+3 adder

- Students typically need an intro to Bloch sphere, gates, etc. Students want to use a quantum computer earlier in the course and more...but the reality is the students wouldn't know what to do with it

- If I wanted to teach Shor's Algorithm, I need to do a month of teaching before that about QFT, modular math, etc. we need to do on a simulator but not even a gate computer. 

- When I'm teaching an undergraduate course during the fall (2 classes a week), we don't even touch a quantum computer until 2 months in. If I'm demoing, it has to work immediately

- Students typically repeat what I'm doing -- running on a simulator, then system to see the actual result, errors, etc. I also have them do Projects where they run a circuit, collect probability distribution data, put it on an excel spreadsheet, and do statistical analysis

- A successful assignment is creating the gate circuit properly. For example, the Google Supremacy gate with random 1Q and 2Q gates. A project could be duplicating that experiment with the native basis gate operations, smart qubit selection decisions to avoid SWAPs, I typically look at the probability distribution of the results

- When you run this on Casablanca, you'll get peaks and errors. I look at they circuits they construct -- what they're learning how to interpret a probability distribution

- We're comparing the probability distribution between system and simulators. After they do that, THEN they can start building their circuits etc 

- Dirac and mathematics can come after this type of project and covering Bloch sphere 

- I don't use exams in my course but we have homework assignments -- starting out with linear algebra, matrix multiplication (starting with `|0>` and applying a `CNOT`, get the final state), getting comfortable with probabilities, etc.

- We have 10 students per class

- IBM has done a lot. Hackathons, Textbook, Advocates. I have felt that the students I teach can't keep up with the material. The math and Dirac is too intimidating to even me. Things like Amplitude Application are hard to understand with all the Proofs

- IBM needs to create a course that starts out a bit easy...let's see it works 

- On the [Intro course](https://learn.qiskit.org/course/introduction/the-atoms-of-computation): As an Educator, I should be getting this information! Between this and the Advocates, I should be getting this information

- I use [this book at the undergraduate level](https://arxiv.org/abs/1905.00282) for the first 10 weeks basically. 

- I want to have questions at the end of chapters

- I'm going to experiment with the introduction course with my students next week. Reach out back in 2 weeks

**Comment by pandasa123** [comment]
**Todd Zimmerman (UW)**

Student side

- Time is important but it’s not my thing
- Lockdown browser
- Canvas lacks: autogenerate numbers for problems
    - With a problem template
- Problem banks, especially to prevent cheating
- Multi-select
- Single score
- One shot, no retakes
- Quizzes can have multiple attempts 
- Exams are time bound (start and finish)
- Quizzes + homeworks have an end date
- I’d like students to be able to typesetting responses…I like LaTeX 


Instructor side

- Being able to see the results 
- Exams Statistics — mean, median, standard deviation is nice, but correlations is actually meaningful
    - Correlation to who got a problem right, and their overall score — this helps me know if my problems are good or bad
    - Discrimination Index
- Partial Credit — MCQ is easy based on my judgement, but Multi-Select is ok to do with judgement, FRQ is hard


Most important:

1. Discrimination Index
2. Problem Banks
3. Templated Problems 

Standards Based Exam — a way to assess competencies with homeworks, we should be looking into this

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
