### ISSUE TITLE
MegaMenuDropdown: create single source of truth

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1081]
### Feature description

Currently, the to populate the `MegaMenuDropdown`, the platypus project uses the `TOC.yaml` file. However, on the Qiskit.org side, that project uses an entirely different file and setup, in order to populate its own `MegaMenuDropdown`.

Ideally, the two projects should always have the same mega menu content, that aligns with the latest design updates. 

This issue is to create a single source of truth that works with the `MegaMenuDropdown` component, and can be used for both platypus and qiskit org projects.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
