### ISSUE TITLE
Add Translation for Simplified Chinese

### ISSUE THREAD

**Issue by Dran-Z** [Qiskit/platypus#1088]
### Feature description

As a Qiskit localization project, I would like to add Simplified Chinese (to be distinguished with Traditional Chinese) translation project for the Qiskit textbook. I would like to act as translation lead for this project.

**Comment by LonghengZhang** [comment]
I would like to contribute

**Comment by E-Deer** [comment]
I want to contribute

**Comment by veenaiyuri** [comment]
Hi @Dran-Z @LonghengZhang @E-Deer, thank you for your interest in translating the Qiskit Textbook into Simplified Chinese! As you now have enough number of members to start a new language team, please follow the steps [here](https://github.com/Qiskit/platypus/blob/main/TRANSLATING.md#steps-to-participate-in-qiskit-textbook-translations) to get onboarded to the localization project. Please do not add other members' name on behalf of the but make sure that each of you individually sign yourself up in the [LOCALIZATION_CONTRIBUTORS](https://github.com/Qiskit/platypus/blob/main/LOCALIZATION_CONTRIBUTORS) file by creating separate pull requests (PR) after editing and updating the file with your name.  Let us know if you have any questions our doubts! Looking forward to welcoming you to the project!

**Comment by 0sophy1** [comment]
@Dran-Z  onboarded to the translator list and gitlocalize. Welcome and enjoy translation!
