### ISSUE TITLE
Portuguese localization PRs from GitLocalize fail automated checks.

### ISSUE THREAD

**Issue by MarcoBarroca** [Qiskit/platypus#1120]
### Steps to reproduce the problem

After finalizing the translation review submit a PR from GitLocalize.

### What is the current behavior?

PRs #1117 and #1118 seem to fail the automated checks with errors `Error: Cypress tests: 1 failed` and `Error: buildx failed with: error: denied: You have exceeded your storage quota. Delete one or more images, or review your storage quota and pricing plan. For more information, see https://ibm.biz/BdPdFA.` respectively.

Unsure if this is a bug related to GitLocalize or the repo itself.

### What is the expected behavior?

PRs sent from GitLocalize should pass the automated checks without any errors.

**Comment by 0sophy1** [comment]
Hi @MarcoBarroca. the error was solved and the two PRs already merged. Can we close this issue? Thank you!

**Comment by MarcoBarroca** [comment]
No problem, closing.
