### ISSUE TITLE
Bug: images in Gitlocalize

### ISSUE THREAD

**Issue by omarcostahamido** [Qiskit/platypus#1130]
### Steps to reproduce the problem

1. Go to gitlocalize
2. Navigate to a notebook to translate

### What is the current behavior?

images seem to appear only on the left side, and overlapping the text.

### What is the expected behavior?

no overlap, images on both sides?

### Screenshots

<img width="1129" alt="Screen Shot 2022-06-09 at 1 37 02 PM" src="https://user-images.githubusercontent.com/18335360/172849380-3b1720d4-6e8f-4e4d-8481-d70d93a4ec9f.png">

### Device

laptop

### OS

MacOS 10.15

### Browser

Chrome

### Additional information

anyone else experiencing this?

**Comment by omarcostahamido** [comment]
it was [this page](https://gitlocalize.com/repo/7494/pt/notebooks/algorithms/phase-kickback.ipynb) and it seems to be fixed.
thx

**Comment by omarcostahamido** [comment]
But now it seems that we can't edit the text for the pictures!

**Comment by 0sophy1** [comment]
Thanks @omarcostahamido . Image overlay is one of the famous bugs of gitlocalize. Please DM me with the further issue. Can we close this issue?

**Comment by omarcostahamido** [comment]
Hi @0sophy1, I think the problem not is the same as in https://github.com/Qiskit/platypus/issues/1180#issuecomment-1161141586
So yes, lets close this issue.
