### ISSUE TITLE
Add Translation to Italian

### ISSUE THREAD

**Issue by fulvio-martinelli** [Qiskit/platypus#1139]
### Feature description

This is a request to add a translation of the Qiskit Textbook to Italian. 
I can act as a translation lead for this project.

**Comment by veenaiyuri** [comment]
Hi @fulvio-martinelli ! Thank you for your interest in translating the Qiskit Textbook into Italian! Per our [guidelines](https://github.com/Qiskit/platypus/blob/main/TRANSLATING.md#what-is-the-criteria-for-adding-a-new-language), you will need a minimum of three members to get your language added to the project.
Can you please encourage members in your community to join your effort and have them leave comments here showing their support?

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
