### ISSUE TITLE
As a learner, I want to be apart a cohort of learners so that I can consume content that is most relevant to me. 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#1142]
### Background

Explore the experience of creating custom courses that is visible to a subset group of users. 

### Acceptance criteria

* Creation of roles/cohorts (roles = students & professors) (cohorts = students & professor relation) 
* Expose existing content from 3rd party location through custom syllabus (course) 
* Exposing content to the correct cohort of students 
* Exposing public/private syllabus to cohorts 
* Additional branding elements for course catalog and course experience

**Comment by pandasa123** [comment]
@gracelindsell has [created a design here](https://www.figma.com/file/8p0JKUHYdHGiScxhCmmCsN/1142-Cohort-Creation?node-id=120%3A2721)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
