### ISSUE TITLE
User testing for Quantum 301

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#1143]
Now that the first page of Quantum 301 is nearing completion, we should do some user testing to validate the content and design

**Comment by pandasa123** [comment]
Yep! I think there are two potential audiences we can test with:

1. **Students**: we have many interns who we can test with, segmented by CS / Physics disciplines 
2. **Instructors**: we have multiple internal instructors including @quantumjim and @amirhassank who can review this

**Comment by JRussellHuffman** [comment]
I think we can do a phased approach. We could start by circulating the preview link internally with our own technical experts and just ask them for feedback (informally). We could use any insights from them (plus our own thoughts) to create a survey. Then, we could share the preview link and survey link with the Qiskit Advocates and the textbook-reading-group slack channel. 

Neither of those slack channels specifically include students or professors, so it would be good to try to target them specifically too. But I think we can get a good set of feedback from the advocates and the reading group.

**Comment by eddybrando** [comment]
@JRussellHuffman @pandasa123 is this still going on or should we close this issue?
