### ISSUE TITLE
In a user created Syllabus an added link does show up wrong in Firefox on Windows

### ISSUE THREAD

**Issue by TigrisCallidus** [Qiskit/platypus#1161]
### Steps to reproduce the problem

0. Have someone create a syllabus and set a link in it
1. Use a windows 10 computer with the newest version of Firefox (101.0.1) 64 bit
2. Go to https://learn.qiskit.org/syllabus/LBX-CAK
3. Look on the website below "Week 1"

### What is the current behavior?

The link shows up as 

<p>This is week 1</p><ul><li><a href="https://learn.qiskit.org/syllabus/create">Link out of site</a></li></ul>

In plain text and not as a link.

### What is the expected behavior?

It would be expected to see a normal link like the other links.

### Screenshots

![linkError](https://user-images.githubusercontent.com/20563847/174113465-1068a054-2bda-4f39-8ad9-65e983a9e942.JPG)

### Device

Lenovo Think Pad

### OS

Windows 10

### Browser

Firefox 

### Additional information

I had it with an older version of firefox, and updating did not help.
This does not occur in Chrome or Edge though (and according to a coworker also not in firefox on a mac)

**Comment by pandasa123** [comment]
Hey @TigrisCallidus, I recommend a hard refresh to your browser (Ctrl, Shift and the 'R' key.)

@techtolentino, I think we may need to revisit our caching policies?
