### ISSUE TITLE
Add Dutch language

### ISSUE THREAD

**Issue by ianhellstrom** [Qiskit/platypus#1163]
### Feature description

Add a Dutch translation to the Qiskit Textbook. I’m happy to take the lead.

**Comment by veenaiyuri** [comment]
Hi @ianhellstrom ! Thank you for your interest in translating the Qiskit Textbook into Dutch. Per our [guidelines](https://github.com/Qiskit/platypus/blob/main/TRANSLATING.md#what-is-the-criteria-for-adding-a-new-language), you will need a minimum of three members who can commit to work on the same language. 
Can you please encourage members in your community to join your effort and have them leave comments here showing their support?

**Comment by veenaiyuri** [comment]
@ianhellstrom Hi! I noticed you closed this issue? Is everything okay? If there is anything we can do to support, please let us know. Thank you.
