### ISSUE TITLE
Enable Automatic Equation Numbering for all equations

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1189]
### Feature description

Currently, in order to have equation numbering, an author must use the `{\tag ()}` syntax, for every equation that they wish to number. However, it _is_ possible to have MathJax render equations automatically.

This would be nice to have, and helpful for both authors and students, since the content can reference equations throughout the page.

This feature request is to figure out how we can patch our version of MathJax (via Mathigon Studio), to enable equation numbering, automatically.

### Additional context

MathJax documentation:

https://docs.mathjax.org/en/latest/input/tex/eqnumbers.html

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
