### ISSUE TITLE
As a learner, I would like to run code on IBM Quantum hardware without leaving the textbook, so that I can understand the impacts of noise in my experiments. 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#1196]
### Background
Learners in the textbook should be able to run code on hardware within the textbook to see that it exists and understand the concept of noise. The final implementation should seem like a magical experience where the user needs to merely learn and write code to run on hardware without any other sign-up flows or inputing their own API token. In an effort to remain agile, this user story has been broken up into 2 phases: Exploratory and Execution. We should take as little time as possible in both phases to release this user story so please comment on suggestions for scoping down or clarifying.  

### Goal
Learners should be able to run qiskit code on IBM Quantum hardware directly from the scratchpad and code cells within the qiskit textbook. 

Exploratory Phase: 
- [x] Research the feasibility of the below acceptance criteria 

Acceptance Criteria: 

- [x] User can copy their IBM Quantum API token to Qiskit account
- [x] User is able to run code on hardware when relevant without any account code inputted 
- [x] User is able to interact with hardware in a chapter with error mitigation material
- [x] IBMer is able to measure textbook execution contribution metrics 

Design file: 
- [Figma design](https://www.figma.com/file/RWKSDXw64Pm6WG4ObDAl6H/2475-Run-on-hardware?node-id=37%3A721)

Tasks to be done to accomplish the criterias:
- #1197 
- #1198 
- #1199 
- #1200

**Comment by Tansito** [comment]
> One slight update to the acceptance criteria: we want to make sure that this is something that can be measured. The last bullet in the acceptance criteria ensure we have attribution to this feature development.

Do you mean to have an score? (like I don't know, from 0 to 10) and not only a check that says if the user passes or not?

**Comment by JRussellHuffman** [comment]
I think it's purely for analytics. We want to know if our users are actually using this feature.

**Comment by pandasa123** [comment]
@frankharkins, [I've created an issue to add a hardware example](https://github.com/Qiskit/platypus/issues/1368)
