### ISSUE TITLE
[Analytics] Canonical URL causing Segment page tracking issues

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1218]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-states/representing-qubit-states
2. Ensure `Functional` cookies are enabled
3. Let the page load
4. View [Segment Event Tracker](https://chrome.google.com/webstore/detail/segment-event-tracker/hbanigoffkilibdakdmmlgefndpjmajl?hl=en) extension info

### What is the current behavior?

The `url` and `path` properties of the page are _hijacked_ to read `https://learn.qiskit.org/textbook`

 

### What is the expected behavior?

They should accurately report the `url` and `path` of the _current_ page, and not a static address

### Screenshots

![Screen Shot 2022-06-23 at 11 53 05 AM](https://user-images.githubusercontent.com/6276074/175376506-a01426dd-987b-4b26-b5b2-5f016342b7ab.png)

### Additional information

[This line](https://github.com/Qiskit/platypus/blob/ae562bd25fc70ca57581c097b017c31fb600340a/server/templates/head.pug#L16) seems to be the culprit

**Comment by techtolentino** [comment]
### Note:

If we need to keep the `canonical` url for SEO reasons, we may be able to leverage middleware. Discussed in an issue [here](https://github.com/segmentio/analytics.js/issues/617), it appears that we can leverage two middleware functions.

[Documentation on Analytics.js Middleware](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/middleware/)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
