### ISSUE TITLE
[Circuit Sandbox UI] Styling on "reset" button for the Circuit sandbox

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#1233]
### Steps to reproduce the problem

1. Go to the single system's page (url is in preview)
3. Scroll down to the Circuit sandbox
4. See error in styling on the "reset" button

### What is the current behavior?

The reset icon is offset from the reset text

### What is the expected behavior?

The text and the icon should be on the same level

### Screenshots

<img width="534" alt="Screen Shot 2022-06-27 at 10 07 46 AM" src="https://user-images.githubusercontent.com/7633881/175973639-53024a53-5588-4e08-81c8-b2ceba24c18e.png">

### Device

macbook

### OS

MacOS

### Browser

firefox (its fine on Chrome)

**Comment by eddybrando** [comment]
@JRussellHuffman could you please help us adding the link to the page with the issue? 😬 Thank you! 🙂

**Comment by vabarbosa** [comment]
> @JRussellHuffman could you please help us adding the link to the page with the issue? 😬 Thank you! 🙂

@eddybrando @mariacloehb you can see it 
near the bottom of this preview page: https://platypus-pr-942.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/basics/single-systems#single-systems-unitary
or at the top of the examples page: https://learn.qiskit.org/course/examples/widgets

**Comment by JRussellHuffman** [comment]
Thanks Va, that's it.
