### ISSUE TITLE
Layout: design exploration for main content width 

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1250]
### Feature description

Currently, for screens at the max breakpoint and above, the textbook content has a maximum width of 42rem.

This design issue is for the exploration of the main content layout for screens that are larger than the max Carbon breakpoint.

**CC:** @JRussellHuffman

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
