### ISSUE TITLE
As a professor, I want to pick and choose problem sets from a bank so that I can test my students without needing to spend time grading.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#1259]
## Background

Professors need ways to test student comprehension. These Professors already use Qiskit Labs in their course and should be able to integrate auto-graded problem sets into homeworks and exams, simplifying their course creation and in-flight collection and grading time

This work can be started independently by a content writer first, and then integrated over time 

Related:

- [Problem Sets Bank](https://github.com/Qiskit/platypus/issues/1259)
- [Problem Set Bank discovery](https://github.com/Qiskit/platypus/issues/1260)

## Goal

> Create a "best-of-class" questions & answers problem set bank for early Quantum 301's material

## Acceptance Criteria

- [ ] Create 5 auto-graded problems -- MCQ + FRQ (can be reduced down, can we reuse old Challenges?) 
- [ ] Create variations on these problems for question bank (optional)
~~- [ ] Enable [Assessment Mode](https://github.com/Qiskit/platypus/issues/1079) for this MVP problem set~~
- [x] #754

**Comment by pandasa123** [comment]
[All the existing problems across Textbook + Challenges](https://app.mural.co/invitation/mural/ibmquantum0809/1657130461503?sender=sanket0836&key=25d16b79-496e-4afb-8e35-2583332fb856). With this, we can create the following Problem Sets within a week:

1. **Foundations of Computing**: Questions that test intuition and the case for quantum
2. **Classical Information and Quantum Information**: $n$ bits + how many states, binary
3. **Single Systems**: Supporting 301 with some maths questions...plus creating several Bell + GHZ states
4. **Basics of Gates**: Creating a Toffoli with basis gates, creating a full adder

Weaker but possible

1. **Grover's Algorithm**: We have quite a few search questions + a Grover Problem
2. **Optimisation**: The knapsack problem (4a + 4b) + portfolio optimisation are easy challenges

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
