### ISSUE TITLE
Bug: Incorrect symbols in formulas

### ISSUE THREAD

**Issue by derwind** [Qiskit/platypus#1271]
### Where does the issue happen?

https://learn.qiskit.org/course/machine-learning/quantum-generative-adversarial-networks

### What is the content issue?

A little above the quick quiz in section "Quantum Generative Adversarial Networks (theory)", a formula that should be displayed as $|\text{Data}_G\rangle$ is displayed as
$|\text{Data}  \lt em \gt G\rangle$.

As far as I investigated, underscores are used in multiple formulas within a single line of this notebook and thus seem to be incorrectly  parsed as an emphasis in markdown's basic syntax.

I expect that perhaps in this case we should use &#096;`{latex}...`&#096; instead of `$...$` to describe the formula, but I am not sure. If my understanding is correct, I would like to create a pull request to correct the display.

### Screenshots

![quantum-generative-adversarial-networks](https://user-images.githubusercontent.com/12698960/176999595-84b05c27-d59d-4ee0-8db1-9e77d12767e1.png)

**Comment by eddybrando** [comment]
Solved with #1291

**Comment by eddybrando** [comment]
Solved with #1291
