### ISSUE TITLE
Add contributing page for textbook beta

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#1288]
### Feature description

We could do with a short page that explains the contribution process and links to this repo. Need to discuss where this lives.

### Additional context

Many people struggle to find the repo, or end up at [qiskit-community/qiskit-textbook](https://github.com/qiskit-community/qiskit-textbook). Related #1289.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
