### ISSUE TITLE
Updated Syllabus course list layout

### ISSUE THREAD

**Issue by gracelindsell** [Qiskit/platypus#1300]
### Feature description

the current course list layout in the syllabus feature is out of date and does not follow the same pattern as the drop down list of the courses and chapters on the learn page. Here is the updated list for the syllabus that is the same as the learn page.

![chapter list](https://user-images.githubusercontent.com/89415444/178052525-81d041bc-ffa1-4801-a408-e6f2e5cfec92.png)
e

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
