### ISSUE TITLE
[Scratchpad] outputArea `clear()` not working

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1328]
### Steps to reproduce the problem

Following up from [this comment](https://github.com/Qiskit/platypus/pull/1212#discussion_r917875828).

To clear the output for the code output, we had to change from using `clear()` to using `setHidden(true)`.

This issue is to investigate why this was necessary, and why the `clear()` wasn't working correctly.

### What is the current behavior?

the `clear()` was not working, so we changed to `setHidden`

### What is the expected behavior?

`clear()` should've worked

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
