### ISSUE TITLE
UI improvements for code cell

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1336]
Design file [here](https://www.figma.com/file/RWKSDXw64Pm6WG4ObDAl6H/2475-Run-on-hardware?node-id=37%3A1405
)

**Comment by eddybrando** [comment]
@JRussellHuffman, I believe this is the final design, right?

![Image](https://user-images.githubusercontent.com/22047320/178774219-89d80a06-126b-409c-a483-bb173946e9ec.png)

If so, I believe we can start working on the code implementation.
