### ISSUE TITLE
Looking into enabling Hotjar again

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1338]

**Comment by vabarbosa** [comment]
on hold while hotjar account gets updated

**Comment by techtolentino** [comment]
@vabarbosa @JRussellHuffman - we seem to be getting responses again, in Hotjar. I think this issue can be closed, but please let me know if there's anything you'd like to review.

I'm able to see results by doing the following:

- log into Hotjar
- select the qiskit.org > Workspace #1 dashboard
- view Scratchpad surveys or other recordings

**Comment by JRussellHuffman** [comment]
you're right. that's so interesting that it has magically come back. But I suppose I won't complain! I think we can close this.
