### ISSUE TITLE
Progress tracking doesn't work on some pages

### ISSUE THREAD

**Issue by luukament** [Qiskit/platypus#1354]
Progress tracking bar doesn't work for some of the pages in the QML course:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/32486545/179703482-05aa5fc8-acea-46a1-bc54-c5e7d7cf9d2e.png">

I scroll all the way down to the bottom of the pages titled "supervised learning" and "Variational classification" but they don't check off.

I use Firefox 102.0.1 (64-bit) on MacOsX.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
