### ISSUE TITLE
Hardware example for Introduction Course

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#1368]
### Feature description

[Users are now able to run on hardware](https://github.com/Qiskit/platypus/issues/1196). We should providing a small, canned example that demonstrates this for the Introduction Course 

### Additional context

[Implementation](https://github.com/Qiskit/platypus/pull/1210/) by @Qiskit/qiskit-digital

**Comment by Tansito** [comment]
I changed a little bit the description @pandasa123 , the implementation was done by the team not only me 😛
