### ISSUE TITLE
incorrect description in the Grover's algorithm

### ISSUE THREAD

**Issue by ljeda** [Qiskit/platypus#1389]
### Where does the issue happen?

https://learn.qiskit.org/course/introduction/grovers-search-algorithm

### What is the content issue?

While I'm following the explanation of the Grover's algorithm, I've encountered the following statement:
"We then need to repeat steps 2 & 3 a few times depending on the size of the circuit. Note that we query the oracle in step 2, so the number of queries is roughly proportional to the square root of the number of possible inputs."
At this stage of the explanation, this is more a statement that should be proven, not the fact that was already explained. I've spent some time trying to figure out how this can be stated at this point and I think this is something that gets the explanation later, so it shouldn't be presented as a fact/corollary here.

**Comment by frankharkins** [comment]
@ljeda do you think the description is incorrect? Or just that it should be moved to a different part of the page?

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
