### ISSUE TITLE
As a Student, I want to submit my problem set to my Professor, so they have a copy of my submission 

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#1472]
### Background

In a classroom, students need to submit their assignments to their professors for collection + grading. We need a way to:

- Grade an entire problem set
- Submit an entire problem set to a professor

### Goal

> Students can click a submit button to send their problem set to their professor

### Acceptance criteria

- [ ] When a student reaches the end of a problem set, they should see a submit page
- [ ] A student should be able to enter their professor's email address (to send the problem set)
- [ ] Before sending an email to a professor, the backend should check if the professor has an account on the Learning Platform
- [ ] When a student clicks the submit button, a professor should receive an email with the student's answers (MCQ + FRQ) and if they answered the question correctly

### Future of feature

After this, we all the basic pieces needed for Professors to assess a course. We need to explore deeper integrations and flexibility, such as custom professor problems, LMS integration, reporting, etc later down the line

### Resources

[Related to server-side MCQ](https://github.com/Qiskit/platypus/issues/1419)

**Comment by pandasa123** [comment]
Something to consider...independent learners should be able to submit + receive a grade without needing a syllabus link. @JRussellHuffman + @gracelindsell might have elegant ideas for this

**Comment by pandasa123** [comment]
Added a few ideas here 

![IMG_1A9FE7763646-1](https://user-images.githubusercontent.com/6241840/189690346-cb0b8768-67c7-4897-9044-94b0bd2174ea.jpeg)

**Comment by pandasa123** [comment]
After talking to @lerongil, we have two problems that we need to figure out:

1. How would professors know who's submitting
2. How would student progress be saved pre-login? LocalStorage?

This "submission" experience should be only available to a user if they're logged in

**Comment by pandasa123** [comment]
- **Last page**: Professor email
- **Students should be logged in**: Pull from the user account
- **Submit is disabled if not logged in**

- First page -- add a "nudge" / prompt that says if a student wants to save their progress, create / login. Inline first? 
- No email sending right now. Maybe a DB that we manually setup and link to professors / ask professor to reach out to us
- Mid-progress: store code in `localStorage`

**Comment by pandasa123** [comment]
Professors need to see what students submitted to the Problem Set. Based on prior user interviews, we need a summarised "score", and being able to see what a student submitted.

**Summarised Scores**

Currently, our FRQ are scored as correct or incorrect. Over time, we can approach fractional scoring but let's assume that it's not going to be the case for now. Let's present the summary with two simple, summary measures:

- `Number of MCQ correct` / `Total MCQ`
- `Number of FRQ correct` / `Total FRQ`

**Multiple Choice Question**

For each problem, Professors should see the following:

- `Question`
- `Student Score`: `Correct | Incorrect`
- `Student Answer`
- `Actual Answer`

**FRQ Question**

For each problem, Professors should see the following:

- `Question`
- `Student Score`: `Correct | Incorrect`
- `Student Code`
- `Suggested Code`

**Comment by pandasa123** [comment]
Holding off development on this issue until @vabarbosa comes up with alternatives

**Comment by pandasa123** [comment]
As per @vabarbosa, we can create an email service endpoint in Saiba. Then call it from Platypus. We need to ensure this solution is as lightweight as possible client-side to make migration easy down the line

Currently user-testing the aforementioned payload, but this should be ready for development shortly

**Comment by pandasa123** [comment]
On a side note: we need some way of logging the validation response for coding questions. 

> @vabarbosa: We'll need to update from within the code grading widget because grading goes out to binder env where grading/validation happens & response returned to widget

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
