### ISSUE TITLE
As a Professor, I want to create a collaborative Jupyter environment, so that I can co-write + debug code with my students

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#1477]
### Background

One of the most common requests from Professors and users overall is a collaborative jupyter environment. This is a game-changing feature that would shape coding sessions with instructors. **This is an exploration first**

### Goal

> Professors should be able to spin up a Jupyter environment and allow students to write and store notebooks in this space 

### Acceptance criteria

- [ ] Any user can create a Jupyter "space"
- [ ] Users can add another user to this "space"
- [ ] Owner can see all notebooks in this "space"
- [ ] 10+ concurrent Jupyter environments

**Comment by frankharkins** [comment]
This would be a great tool, but I think this would compete directly with IBM quantum lab, and is probably something we should encourage them to implement (if they're not working on it already).

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
