### ISSUE TITLE
Allow copying drag & drop code exercises to scratchpad

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#1480]
### Feature description

While attempting the drag and drop code exercise (example [here](https://learn.qiskit.org/course/introduction/the-atoms-of-computation#the-15-40) - you'll need to scroll down a bit), readers should have the option to copy the code to the scratchpad so they can play around with it.

Acceptance criteria could be:

- [ ] Ability for reader to copy code to scratchpad
- [ ] Ability for reader to reset exercise
- [ ] Ability for creator to hide this feature for exercises with non-python code

**Comment by JRussellHuffman** [comment]
Design file here: https://www.figma.com/file/lDeDokeHVTqwxOEEU9JhIP/1480-copy-to-scratchpad?node-id=0%3A1

The three added icons are the same as regular code cells
- copy to scratchpad
- copy to clipboard
- reset

This would make the drag and drop components consistent with the code cells, and it satisfies most of the acceptance criteria here.

**Comment by JRussellHuffman** [comment]
@frankharkins what are you thinking for the third acceptance criteria?

> Ability to turn this off for pseudocode exercises

**Comment by vabarbosa** [comment]
> @frankharkins what are you thinking for the third acceptance criteria?
> 
> > Ability to turn this off for pseudocode exercises

i suspect he is suggesting the actions be optional or able to configured/disabled. it would not make sense for exercises that use pseudocode (or more specific, non-python code) since they would not be able to successfully run in the sidebar.

in addition, would it make sense for the copy/copy to sidebar action buttons to be disabled until the exercise is successfully completed? otherwise, what should be copied if the exercise is wrong or incomplete?

**Comment by JRussellHuffman** [comment]
That makes a lot of sense. So it wouldn't be the end user who is enabling/disabling, but the content creator. 

Regarding disabling until complete, it _might_ make sense that a user can copy a half-complete answer over so they can work it out without using the widget, and I suspect that would be easier for development. But, I could go either way. You bring up a good point.

**Comment by vabarbosa** [comment]
> That makes a lot of sense. So it wouldn't be the end user who is enabling/disabling, but the content creator.
> 

correct.

> Regarding disabling until complete, it _might_ make sense that a user can copy a half-complete answer over so they can work it out without using the widget, and I suspect that would be easier for development. But, I could go either way. You bring up a good point.
>

make sense. i can go either way on this as well, but +1 for the easier for development option.

**Comment by JRussellHuffman** [comment]
I'm good with the easier dev option too.

**Comment by frankharkins** [comment]
> I think he is suggesting the action buttons be optional or able to configured/disabled/hidden when creating new instance of the widget

Exactly, I've updated the comment to make it a bit clearer.

> it might make sense that a user can copy a half-complete answer over so they can work it out without using the widget

This is also my preference, I think a user might want to copy over broken/incorrect code to run it and investigate why it doesn't work.

**Comment by vabarbosa** [comment]
> 
> This is also my preference, I think a user might want to copy over broken/incorrect code to run it and investigate why it doesn't work.
> 

good point!

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
