### ISSUE TITLE
Syntax highlighting in drag & drop code exercise

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#1481]
### Feature description

Would be nice to have syntax highlighting here:

<img src="https://user-images.githubusercontent.com/36071638/186498730-81e52e8f-ff73-4f8b-b7da-bf2944196205.png" width=500px>

Related: #357

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
