### ISSUE TITLE
There is a lack of explanation in grover's algorithms

### ISSUE THREAD

**Issue by LLLLCCJ** [Qiskit/platypus#1482]
### Feature description

In Grover's algorithms (https://qiskit.org/textbook/ch-algorithms/grover.html), There is a lack of explanation about mathematical things. 
Particularly, Step 3 part Us = 2|s><s| - 1, I don't know why this equation come up. 

<s| means outer product with |s> and |s>. I don't know what this means. And also I don't know why this means rotate in range 4 theta.

**Comment by hosen20** [comment]
@frankharkins is anyone assigned. I have the necessary knowledge to work on it.

**Comment by hosen20** [comment]
Hi @frankharkins , yes I would like to work on it.

**Comment by frankharkins** [comment]
Thanks! I've assigned you :)

**Comment by themathqueen** [comment]
So it turns out that I've been working on pretty much the same thing (see https://github.com/qiskit-community/qiskit-textbook/issues/1542). @hosen20, do you want to collaborate on this?

**Comment by micpap25** [comment]
possible duplicate of #399

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
