### ISSUE TITLE
learn.qiskit.org should contain a link to this repo

### ISSUE THREAD

**Issue by rht** [Qiskit/platypus#1483]
### Feature description

learn.qiskit.org, which I think is the website associated with this repo, should contain a link to this repo, so that the readers can readily make a pull request to fix errors/typo.

**Comment by frankharkins** [comment]
I agree, would implementing #1289 be enough to resolve this?

**Comment by rht** [comment]
Yeah. Alright, this issue seems to be a duplicate.

Another note is that I wonder if most people would associate being able to view the source code to being able to additionally post bugs/feedback via the GH issue. But I hope so.
