### ISSUE TITLE
Update syllabus view with `Duplicate syllabus` button

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1514]
### Feature description

As part of the curated syllabi experience, we'll need the ability to duplicate syllabi.

- for curated syllabi, we need to add a ghost button to the top right of the syllabus
- when a user clicks on the `Duplicate syllabus` button, they are taken to the `Classroom` section in `/account/classroom`
  - if a user is logged out, they should still be able to duplicate a syllabus and land on their Classroom page 

**Screenshot of design**
![Screen Shot 2022-09-02 at 12 58 14 PM](https://user-images.githubusercontent.com/6276074/188227564-0ef544fc-38f4-4eaf-a824-737e2481d3c4.png)

### Additional context

- For design questions or guidance, please reach out to @gracelindsell 

#### Note
(Design and acceptance criteria are subject to change, prior to sprint planning)

**Comment by pandasa123** [comment]
@techtolentino, looks like this can be closed?

**Comment by techtolentino** [comment]
@pandasa123 yes!
