### ISSUE TITLE
Customize duplicate syllabus workflow

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1515]
### Feature description

As part of the curated syllabi experience, we'll need ensure the correct interactions are part of the customize syllabi workflow

- [x] when a user clicks to Edit a duplicated syllabi, they're taken to the edit syllabus page
- [x] the syllabus creation tool view should be expanded (see design)
- [x] Name and university fields are required
- [x] when a user customizes/edits the duplicated syllabi, they'll be prompted to re-fill out the top section (syllabus information)

## Screenshot of design

![Screen Shot 2022-09-02 at 1 10 51 PM](https://user-images.githubusercontent.com/6276074/188229044-f784bacd-4158-4331-a8ae-faffeae7f912.png)

### Additional context

- For design questions or guidance, please reach out to @gracelindsell 

#### Note
(Design and acceptance criteria are subject to change, prior to sprint planning)

**Comment by pandasa123** [comment]
@techtolentino, time to close this one?

**Comment by techtolentino** [comment]
@pandasa123 yes!
