### ISSUE TITLE
Syllabus: How do we give some sense of "order" learners should follow?

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#1526]
### Feature description

Let's take the following example:

<img width="610" alt="Screenshot 2022-09-06 at 08 59 03" src="https://user-images.githubusercontent.com/6241840/188641467-31978fd9-2954-459a-a3df-baeb19d52d6d.png">

How do learners know which order to follow across the 7 chapters? 

### Additional context

CC: @lerongil, @gracelindsell, @techtolentino

**Comment by pandasa123** [comment]
There's a few solutions that we discussed earlier:

- **Add numbers to the chapters**: Yep, this helps order the Textbook chapters...but the external links have no order
- **Allow external links to inline "chapter" link**: This is something we talked about from MVP, but we could add a "create custom chapter" link creator?

**Comment by pandasa123** [comment]
We should include this for user testing, along with the following ideas:

- Chapter / Reading order
- External link issues
- Overview description

CC: @JRussellHuffman, @gracelindsell

**Comment by JRussellHuffman** [comment]
yep. agreed. This is a good one

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
