### ISSUE TITLE
Bug: qiskit-megamenu-dropdown performedSearch not properly tracking

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1533]
### Steps to reproduce the problem

1. Go to the [Why Quantum](https://learn.qiskit.org/course/introduction/why-quantum-computing) page in the Textbook
2. Click on `Browse all content`
3. Enter search terms
4. Now check the [Segment Chrome extension](https://chrome.google.com/webstore/detail/segment-event-tracker/hbanigoffkilibdakdmmlgefndpjmajl?hl=en) for what was tracked
5. See that search terms are not tracked under a performed search

### What is the current behavior?

See that search terms are not tracked under a performed search

### What is the expected behavior?

Search terms should track by a performed search

### Screenshots

This screen shot shows the following:

- visit a page in the Texbook
- see that the Page Load event is working 
- type in search terms
- see that performed search is not triggering and no data is being captured

https://user-images.githubusercontent.com/6276074/188928541-8979a8c1-e3f5-4166-8f07-a7edb953903c.mov

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
