### ISSUE TITLE
[Content] Apostrophe not rendering correctly

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#1539]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-algorithms/bernstein-vazirani-algorithm (bottom of the page)

### What is the content issue?

The apostrophe in the 'next' button at the bottom shows the escape sequence instead of the apostrophe character. Also in the browser page title (I'm using OSX Firefox).

### Screenshots

<img width="254" alt="Screenshot 2022-09-09 at 13 25 57" src="https://user-images.githubusercontent.com/36071638/189349478-3f5b2cae-e4ee-4714-972a-5bb89db0cab1.png">

<img width="284" alt="Screenshot 2022-09-09 at 13 30 24" src="https://user-images.githubusercontent.com/36071638/189350242-81b5c53c-a548-4375-8872-a7a7db6337dc.png">

### Additional information

Related or similar to https://github.com/Qiskit/platypus/issues/1922

**Comment by mdrodelo** [comment]
Hello. I saw this issue was still open and decided to give it a go. The same issues occur on Chrome OSX. Pull request #1575.

**Comment by mdrodelo** [comment]
I believe I figured out how to fix browser page title. How should I approach this as far as pull requests go? Open a new pull request?

**Comment by frankharkins** [comment]
Yes please open another pull request, thanks!

**Comment by callistusndemo** [comment]
This issue appears to have been fixed on the current live version of the textbook:

![image](https://user-images.githubusercontent.com/29136312/222802462-d4bc778f-87a3-4ab2-9799-de4947da87e5.png)

**Comment by vabarbosa** [comment]
related issue https://github.com/Qiskit/platypus/issues/1922

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
