### ISSUE TITLE
Bug: Inconsistent product state-vector example

### ISSUE THREAD

**Issue by husayngokal** [Qiskit/platypus#1556]
### Where does the issue happen?

https://learn.qiskit.org/course/introduction/entangled-states

### What is the content issue?

As I was going through this section of the textbook, I noticed that the example used to introduce product states to the learner does not follow the material presented in the rest of the chapter:

![problem](https://user-images.githubusercontent.com/92259277/190081937-479796c9-e361-49d3-8c84-a43cdf34cb52.png)

The book says that this product state would be written as +0, and since "+" refers to the "qubit on the left" (aka the first qubit), it would make sense that the format for writing a product state is ab, where a is the first qubit and b is the second qubit. As the chapter progresses, however, this is what the book presents us with:

![explanation 1](https://user-images.githubusercontent.com/92259277/190082569-d99d13a7-7f19-40ef-b550-9bd1fd271469.png)

According to the format, we've just been taught, shouldn't the structure of the product state be +-, considering that the first qubit is in the state "+" and the second qubit is in the state "-", following the ab structure?

![explanation 2](https://user-images.githubusercontent.com/92259277/190082602-142ff735-32c4-48f7-96e9-d9cd82646255.png)

This just outright tells us that product states are written in the format ba, not ab. So why is the first example of the chapter different from the rest of the chapter?

EDIT: This is another example of the same issue, @BoseSj pointed it out 👇 
![image](https://user-images.githubusercontent.com/92259277/201540278-5739111d-3974-4d2f-ba00-354b824d0a5f.png)

The product state says "ab", but shouldn't it say "ba" instead?

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
