### ISSUE TITLE
Bug: typos in traveling salesman problem section

### ISSUE THREAD

**Issue by vandieren** [Qiskit/platypus#1557]
### Where does the issue happen?

https://qiskit.org/textbook/ch-paper-implementations/tsp.html

### What is the content issue?

- [ ] The sentence below appears in the text
  - Lets construct the unitarie for j = 1, 2, 3, & 4:
  - Lets should be Let's and unitarie should be unitary

- [ ] Lets is misspelled throughout the page

- [ ] Further down the page, the sentences copied below need changing for consistency for singular/plural agreement
  - U_j are diagonal unitary matrices. It will be  ... 
  - Proposed change could be
  - Each U_j is a diagonal unitary matrix and it will be...

- [ ] "only the (n−1)contain length" is missing a space in between (n-1) and contain
- [ ] "But, keep in mind, Finding" shouldn't have a capital in Finding
- [ ] A more thorough editing of the grammar and style on this page would improve it and make it more consistent with the language in the rest of the qiskit textbook

**Comment by micpap25** [comment]
Working on this

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
