### ISSUE TITLE
Add segment toUrl property for CTA clicked event

### ISSUE THREAD

**Issue by yoshiemuranaka** [Qiskit/platypus#1564]
### Feature description

With tracking added to the new ui-shell (navbar) component, it would be helpful to leverage the toUrl property in the segment CTA clicked event. Currently we are using the CTA and location properties when the navbar links are clicked

<img width="723" alt="Screen Shot 2022-09-16 at 10 41 15 AM" src="https://user-images.githubusercontent.com/8097306/190700394-6e18c88c-5f62-4971-b59b-29f261a7b04d.png">

**Comment by yoshiemuranaka** [comment]
fyi @agebbie

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
