### ISSUE TITLE
Megamenu Dropdown should include Summer School courses

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1584]
The `Browse all content` / `megamenu` dropdown should include these Summer School courses

![Screen Shot 2022-09-22 at 12 25 18 PM](https://user-images.githubusercontent.com/6276074/191833924-73576671-f11a-472a-90de-b9471f801f6f.png)

(we'll also have to make the update in the qiskit org project)

**Comment by techtolentino** [comment]
@JRussellHuffman - thoughts?

if you agree, we can convert this discussion issue to an actionable item...

**Comment by JRussellHuffman** [comment]
agreed, I think we should include it. I think the content of the megamenu should have the same content as the page itself.

**Comment by techtolentino** [comment]
Updated the issue to read as an actionable issue...
