### ISSUE TITLE
Include Latex support and ability to add images in Qiskit Classroom Syllabus

### ISSUE THREAD

**Issue by desireevl** [Qiskit/platypus#1594]
### Feature description

When creating a custom syllabus in [Qiskit Classroom](https://learn.qiskit.org/account/classroom), it would be useful to have the following support in the 'content' section:

- Support for Latex formatting
- Support for images to be uploaded

Currently there is minimal formatting abilities. Users of this tool such as professors and other educators would find it useful to be able to include mathematical equations into the descriptions. Adding images would also enrich the content of the syllabus.

### Additional context

CC @veenaiyuri @mrvee-qC-bee

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
