### ISSUE TITLE
Bug: Incorrect statement in linear algebra page

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#1595]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-appendix/an-introduction-to-linear-algebra-for-quantum-computing

### What is the content issue?

> The surface of this sphere, along with the inner product between qubit state vectors, is a valid Hilbert space.

But the surface of the Bloch sphere is not a vector space.

### Additional information

Brought to our attention via [tweet](https://twitter.com/rajkk1/status/1575434106577604609?s=46&t=lvszjGXxjTV5phNOrjpYiw) about an [SO post](https://quantumcomputing.stackexchange.com/questions/27191/how-is-the-surface-of-a-bloch-sphere-a-hilbert-space).

**Comment by sriramanved** [comment]
I believe this is a good first issue. Could I please take this on?

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
