### ISSUE TITLE
Add Bengali and Chinese to Mathigon config

### ISSUE THREAD

**Issue by ilyaspiridonov** [Qiskit/platypus#1602]
### Feature description

Before translations can be made publishable, Bengali and Chinese need to be added (or we need to ensure these two are added) in Mathigon config on the server side under `node_modules/@mathigon/studio/server/data/locales.yaml`
**NB:** 
Bengali needs to be added with language code `bn`
Chinese is probably already there with the language code `cn` - needs to be replaced with `zh-CN` (to support the current path to Chinese translations in the repo) 

### Additional context

Mathigon config is not part of this repo (hence no pull request), however these two language codes need to be included (or someone needs to confirm they are already there on the server side – not the case by default), as otherwise the build will fail when these locales are added in [config.yaml](https://github.com/Qiskit/platypus/blob/main/config.yaml)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
