### ISSUE TITLE
Bug: HHL algorithm is going to be deprecated in favor of textbook explanation which uses deprecated HHL

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/platypus#1612]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-applications/solving-linear-systems-of-equations-using-hhl-and-its-qiskit-implementation

### What is the content issue?

Qiskit Terra decided to deprecate HHL (among other things) in https://github.com/Qiskit/qiskit-terra/pull/8617. 
In a follow up PR https://github.com/Qiskit/qiskit-terra/pull/8699, the deprecation message points to the textbook as an alternative. However, the textbook imports deprecated (in #8617) classes to explain linear system. The chapter should be written in independent terms (a la Shor) without using HHL classes.

**Comment by frankharkins** [comment]
I believe this was fixed in https://github.com/Qiskit/platypus/pull/1577 ? Or is this issue asking for an implementation that only uses Terra (i.e. not an external package)?

**Comment by 1ucian0** [comment]
ups! my bad! Fixed by https://github.com/Qiskit/platypus/pull/1577
