### ISSUE TITLE
Issues in Entangled states chapter

### ISSUE THREAD

**Issue by Rai-Sama** [Qiskit/platypus#1619]
### Where does the issue happen?

https://learn.qiskit.org/course/introduction/entangled-states

### What is the content issue?

- [ ] Entangling gates: The cx gate - In this sub-section, under the output cell of the first code there is a note that states that <a href="https://learn.qiskit.org/course/introduction/entangled-states#:~:text=In%20the%20cell%20output%20above%2C%20the%20state%20vectors%20are%20drawn%20horizontally%20instead%20of%20vertically">"the state vectors are drawn horizontally instead of vertically"</a>. But the code is not drawing the state vector at all, rather it is simply drawing the state |00>.

- [ ] Entangling gates: The cx gate revisited - In this sub-section, in the second sentence it says <a href="https://learn.qiskit.org/course/introduction/entangled-states#:~:text=However%2C%20just%20as%20we%20saw%20with%20the%20cx%20gate">"However, just as we saw with the CX gate"</a>. But it should rather say "However, just as we saw with the CZ gate". 

- [ ]  Unique quantum correlations - Typo above the 4th code cell of this section: <a href="https://learn.qiskit.org/course/introduction/entangled-states#entangled-26-0:~:text=of%20an%20when">"Next, let's see the results of an when Bob performs..."</a> It should rather just be "Next, let's see the results of when Bob performs..."

**Comment by Rai-Sama** [comment]
@vabarbosa / @frankharkins These tasks should be part of some of the pull requests, right? I believe one of the tasks (2nd one) has been completed. Can either of you confirm?

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
