### ISSUE TITLE
[User account] Sidebar consistency

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1631]
### Feature description

Currently, when a user visits any content page in the Textbook, they'll see the Sidebar w/ all the chapter content in it. The User account, also has a Sidebar, though their behaviors are different from one another.

**Textbook Content pages** 
- at full screen-sizes, the Sidebar is fully shown
 - at medium screen-sizes (on a tablet, for example), the Sidebar collapses to a more minimal version. 
 - at smaller screen-sizes (phone), the Sidebar menu is fully hidden, and can be revealed using Show Index / Hide Index buttons
 
https://user-images.githubusercontent.com/6276074/195433194-c9bb840f-9098-4344-8bcd-d894978045af.mov

 
 
 **User Account** 
- at full screen-sizes, the Sidebar is fully shown
 - at medium screen-sizes (on a tablet, for example), the Sidebar still shows the nav items, but is has less width
 - at smaller screen-sizes (phone), the Sidebar menu becomes a dropdown 
 
 

https://user-images.githubusercontent.com/6276074/195433245-20cb327b-a413-40cd-97df-dbfb34812946.mov

 
This request is for the design team to help arrive at a consistent experience for the entire platform's Sidebar.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
