### ISSUE TITLE
Bug: quantum-machine-learning/training.ipynb has too long warning message

### ISSUE THREAD

**Issue by Thessal** [Qiskit/platypus#1632]
### Steps to reproduce the problem

1. Go to quantum-machine-learning/training.ipynb 
or, https://learn.qiskit.org/course/machine-learning/training-quantum-circuits
2. Scroll down to cell that starts with "Analogous to the function that computes gradients ..."
3. See FutureWarning message repeating

### What is the current behavior?

Too much warning message is displayed
Scroll bar is too small

### What is the expected behavior?

Hide warning message by adding 

```
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
```

after `from qiskit.opflow import NaturalGradient`

### Screenshots

![image](https://user-images.githubusercontent.com/876804/195532069-51ec10b4-23bb-4b00-aae7-37631073a0d5.png)

### Browser

Chrome

### Additional information

qiskit.opflow.NaturalGradient._ridge is causing the problem

```
        reg = Ridge(
            alpha=lambda_,
            fit_intercept=fit_intercept,
            normalize=normalize,   <------- normalize="deprecated",
            copy_X=copy_a,
            max_iter=max_iter,
            tol=tol,
            solver=solver,
            random_state=random_state,
        )
```

**Comment by frankharkins** [comment]
I'm a bit torn on this:
- The warning looks messy and might be intimidating to readers as it looks like something has gone wrong, but
- it is what a user would see when they replicate the code themselves and it's possible they'd think they're doing something wrong if they don't see it on the website.
- Hiding the warnings also means we won't be automatically alerted to any warnings in the future that we _do_ need to act on.
