### ISSUE TITLE
Bug: Paragraph requires a change of wording

### ISSUE THREAD

**Issue by husayngokal** [Qiskit/platypus#1638]
### Where does the issue happen?

https://learn.qiskit.org/course/introduction/entangled-states#entangled-26-0

### What is the content issue?

The paragraph says that to use this alternative representation of the CX Gate, the target needs to be in the |-> state. To get the target qubit into a |-> state, I used a Hadamard Gate followed by a Z Gate like this:
![CX Gate Alternate Representation 1](https://user-images.githubusercontent.com/92259277/196037588-4474f42b-49ba-4639-8bac-7a8d115fc3f5.png)

The requirements don't mention anything about the control qubit needing to be in superposition, but look what happens when you remove it:
![CX Gate Alternate Representation 2](https://user-images.githubusercontent.com/92259277/196037706-34a15764-3065-4c02-a95c-aeb9eb74f6c8.png)

Phase Kickback doesn't _kick in_ anymore (see what I did there :wink:). 

I would suggest a change of wording in the paragraph, just for clarification:
"This effect can also motivate us to make an alternative interpretation of the cx. We can think of it as applying a z to the control if the target is in state |-> and the control is in superposition, and do nothing if it is in state |+> and or the control is not in superposition."

**Comment by frankharkins** [comment]
Thanks for your comment. I see your confusion, but the original paragraph is correct; the action is still a Z-gate on the control qubit. The reason you're not seeing anything in the composer is
$Z|0\rangle = |0\rangle$, and $Z|1\rangle = -|1\rangle$, so the only change is a global phase which isn't observable and doesn't show up on the q-sphere.

I considered adding a different clarification, but I've decided against it to avoid convoluting the explanation.
