### ISSUE TITLE
Bug: LaTeX not rendering in Lab 8 on Grover's algorithm

### ISSUE THREAD

**Issue by vandieren** [Qiskit/platypus#1639]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-labs/lab-8-grovers-search-with-an-unknown-number-of-solutions

### What is the content issue?

Several instances if raw LaTeX code (in the form $ ... $) are not rendering in [Lab 8 on Grover's Algorithm](https://learn.qiskit.org/course/ch-labs/lab-8-grovers-search-with-an-unknown-number-of-solutions)

**Comment by micpap25** [comment]
Going to try to work on this

**Comment by micpap25** [comment]
Alright, I've identified the issue. Every single Lab except Lab 1 is written using HTML header tags instead of Markdown hashtags for some reason... this interferes with LaTeX rendering. I will edit all the files to be standardized with the rest of the Qiskit code.

**Comment by micpap25** [comment]
I imagine it will be an extension of this to all labs; https://github.com/Qiskit/platypus/commit/150627a505bc24c0413e620c6f1deed486ee6686

**Comment by micpap25** [comment]
Done with Labs 2, 3, and 4. Will do the rest over the weekend.
