### ISSUE TITLE
Bug: typo in Qiskit textbook 

### ISSUE THREAD

**Issue by vandieren** [Qiskit/platypus#1640]
### Where does the issue happen?

https://qiskit.org/textbook/ch-states/single-qubit-gates.html#6.2-The-S-gates--

### What is the content issue?

In the first paragraph of section 6.2 on the S-gates, there is an inconsistency with the article proceeding P-gate.  The first sentence writes "a P-gate" the last sentence writes "an P-gate."  There are other instances of this in section 6.3 further down the page

**Comment by vabarbosa** [comment]
@vandieren thank you for this. 

if possible can you open up the [issue here](https://github.com/qiskit-community/qiskit-textbook/issues/new/choose) instead. apologies for any confusion.

https://qiskit.org/textbook content is manged in the [qiskit-community/qiskit-textbook](https://github.com/qiskit-community/qiskit-textbook) repository.

---
FYI @frankharkins
