### ISSUE TITLE
Bug: npm install fails, node-sass unable to find python, Apple M1

### ISSUE THREAD

**Issue by jacobwatkins1** [Qiskit/platypus#1653]
### Steps to reproduce the problem

On M1 Macbook Pro (2021), proceed through "Getting Started" on platypus README file. After completing pre-requisites steps, run `npm install` in platypus. 

The install fails with error: `python: No such file or directory`.

### What is the current behavior?

A long error message upon execution, with install unsuccessful. Seems to be a device-specific problem, particularly to new Apple M1 laptops.

```
3246 error 2 warnings generated.
3246 error env: python: No such file or directory
3246 error make: *** [Release/sass.a] Error 127
3246 error gyp ERR! build error 
3246 error gyp ERR! stack Error: `make` failed with exit code: 2
3246 error gyp ERR! stack     at ChildProcess.onExit (/<...>/platypus/node_modules/node-gyp/lib/build.js:194:23)
3246 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
3246 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
3246 error gyp ERR! System Darwin 21.6.0
3246 error gyp ERR! command "/usr/local/bin/node" "/<...>/platypus/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
3246 error gyp ERR! cwd /<...>/platypus/node_modules/node-sass
3246 error gyp ERR! node -v v16.18.0
3246 error gyp ERR! node-gyp -v v7.1.2
3246 error gyp ERR! not ok 
3246 error Build failed with error code: 1
3247 verbose exit 1
3248 timing npm Completed in 171232ms
```

### What is the expected behavior?

Successful execution of `npm install` while in platypus directory. 

### Device

MacBook Pro, 2021, M1 Max chip

### OS

macOS Monterey

### Additional information

https://github.com/sass/node-sass/issues/3033 (Shows similar issue for M1 devices and sass execution)

The problem is fixed by manually removing `"node-sass": "^6.0.0"` line from package.json file in platypus directory, then executing the following. 

```
rm -rf node_modules

npm install

npm install --save-dev node-sass@npm:sass
```

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
