### ISSUE TITLE
Bug: Colors in text don't match colors on diagram

### ISSUE THREAD

**Issue by wadleigh** [Qiskit/platypus#1668]
### Where does the issue happen?

https://learn.qiskit.org/course/introduction/visualizing-entanglement

### What is the content issue?

In "Exercise 5" and "Bell test for quantum variables" sections of the "Visualizing Entanglement" section, the text refers to the bars as white representing 1 and black representing 0, but the images acutally have 1 represented by purple and zero represented by a gray empty bar.

### Screenshots

<img width="539" alt="Visualizing Entanglement exercise 5 color" src="https://user-images.githubusercontent.com/72709116/198905976-160b7d19-6bfb-48c7-8d22-e0464303596b.png">
<img width="545" alt="Visualizing Entanglement Puzzle 12 colors" src="https://user-images.githubusercontent.com/72709116/198905980-5fdfa6c2-474f-4790-96be-73a4a5235b1a.png">

**Comment by frankharkins** [comment]
Closed via https://github.com/Qiskit/platypus/pull/1669
