### ISSUE TITLE
Curated syllabi: populate local db w/ Community syllabi

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1671]
### Feature description

Currently, the Community Syllabi are public w/ real published URLs.

When a developer starts the application in our local database, [we populate the database](https://github.com/Qiskit/platypus/blob/8dcb4c6319a8b81663855e12fb6b751f902952de/server/populate-database.ts) w/ a mock syllabus (this mock syllabus is created so that the logged in user is an [owner](https://github.com/Qiskit/platypus/blob/8dcb4c6319a8b81663855e12fb6b751f902952de/server/populate-database.ts#L54)). 

In order for the duplication workflow to fully function correctly in localhost environments, we need to also populate the database w/ "Community syllabi", where the current, logged-in user is **not** the owner.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
