### ISSUE TITLE
Export Syllabus to PDF

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#1687]
### Feature description

Users want to be able to export a syllabus to PDF to distribute it via their own LMS system etc. This request has come up multiple times across Syllabus v1 and v2

### Additional context

I think we do need a way to attribute links from exported syllabi. For example:

- Instrument the `Export` button
- Add UTM codes to the end of links, like `&source=syllabus&code=ABC-DEF`?

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
