### ISSUE TITLE
Bug: "Error displaying widget" in Visualizing Entanglement

### ISSUE THREAD

**Issue by brasswood** [Qiskit/platypus#1690]
### Where does the issue happen?

https://learn.qiskit.org/course/introduction/visualizing-entanglement

### What is the content issue?

After running the second code block, instead of the puzzle, the text "Error displaying widget" is displayed.

### Screenshots

![image](https://user-images.githubusercontent.com/25247756/201415050-0037737a-f5dd-42ec-9735-044ed073b6dc.png)

**Comment by frankharkins** [comment]
This seems to be a problem with `ipywidgets` v8. If you run
```
!pip install ipywidgets==7
```
before importing anything, it works again.

**Comment by frankharkins** [comment]
Closed via https://github.com/Qiskit/platypus-binder/pull/28
