### ISSUE TITLE
Bug: A typo in the step iv of phase estimation

### ISSUE THREAD

**Issue by bfhaha** [Qiskit/platypus#1713]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-algorithms/quantum-phase-estimation

### What is the content issue?

I think the inverse fourier transform is |2^n \theta\rangle \otimes |\psi\rangle. Do I misunderstand anything?

### Screenshots

![image](https://user-images.githubusercontent.com/18122963/203849044-dacd546b-116b-4f88-afd9-4fd2ed8f1ce4.png)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
