### ISSUE TITLE
Timed test/exam/assignment capability on Qiskit Learn

### ISSUE THREAD

**Issue by mrvee-qC-bee** [Qiskit/platypus#1750]
### Feature description

A feature set to potentially explore adding could be Time bound exam mode which could be used by professors to host timed tests/exams/assignment based on their requirements

Illustration:

![TimedExams](https://user-images.githubusercontent.com/109966025/206219553-c26a7c13-8c68-403b-bbd6-6a4682ef640c.png)

FYI: @pandasa123

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
