### ISSUE TITLE
HHL page needs instructions on installing linear solvers package

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#1786]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-applications/solving-linear-systems-of-equations-using-hhl-and-its-qiskit-implementation

### What is the content issue?

We use the linear solvers package from https://github.com/anedumla/quantum_linear_solvers, but don't explain to users how to install it.

Solution is to add a line with install instructions

```
pip install git+https://github.com/anedumla/quantum_linear_solvers
```

**Comment by woodsp-ibm** [comment]
One comment on the external HHL. This code depends on logic in Terra, such as QuantumInstance, which is planned to be deprecated in the upcoming release. Algorithms used to use this but were refactored to use Primitives. It maybe possible to alter the HHL to use a Sampler instead to ensure it continues working as QuantumInstance will be removed in the future. There was a recent issue with its use of QuantumInstance as well Qiskit/qiskit-terra#8735

**Comment by frankharkins** [comment]
@woodsp-ibm thanks for the heads up! I'll take a look
