### ISSUE TITLE
Content references have not margins in mobile (all pages)

### ISSUE THREAD

**Issue by Tansito** [Qiskit/platypus#179]
Some examples of the problem found [here](https://learn.qiskit.org/course/introduction/why-quantum-computing):
<img width="193" alt="Screenshot 2021-10-21 at 17 18 31" src="https://user-images.githubusercontent.com/9059044/138308982-e22fcc79-8e6f-480e-9cc9-9e9dbef7ab8f.png">
<img width="190" alt="Screenshot 2021-10-21 at 17 18 41" src="https://user-images.githubusercontent.com/9059044/138309003-31000e00-066a-4acd-a34c-2983bcf891b9.png">
<img width="172" alt="Screenshot 2021-10-21 at 17 18 58" src="https://user-images.githubusercontent.com/9059044/138309011-314d7832-f129-45a7-ad6e-0fcf7dfa8a3d.png">

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
