### ISSUE TITLE
Menus incoherence in some breakpoints (all pages)

### ISSUE THREAD

**Issue by Tansito** [Qiskit/platypus#180]
Seems to be some inconsistencies between breakpoints in the menu [here](https://learn.qiskit.org/course/introduction/why-quantum-computing):
<img width="611" alt="Screenshot 2021-10-21 at 17 20 59" src="https://user-images.githubusercontent.com/9059044/138309549-0f8bc27e-cd31-4d48-9170-ef0399aade3f.png">
<img width="753" alt="Screenshot 2021-10-21 at 17 20 03" src="https://user-images.githubusercontent.com/9059044/138309565-8e0a31e5-90b1-4f5f-a4a1-108118e59be8.png">
>

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
