### ISSUE TITLE
Bug: Cannot select final option in inline dropdown

### ISSUE THREAD

**Issue by micpap25** [Qiskit/platypus#1816]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-states/representing-qubit-states

### What is the content issue?

I cannot select the final option in the inline dropdown on this page. This could make it impossible to answer the question correctly without a refresh (since that will randomize the answer order).

### Screenshots

[screen-capture.webm](https://user-images.githubusercontent.com/34077605/212345432-15bb3aba-eac7-4536-9a8b-2d205526d2cd.webm)

**Comment by jackoconnordev** [comment]
Behaviour also exists on page https://learn.qiskit.org/course/ch-states/atoms-computation.

<img width="1176" alt="image" src="https://github.com/Qiskit/platypus/assets/134723582/54ddbe10-55d7-407b-a4cc-1b5a95ac5ba8">

E.g. Number 4 can not be selected as answer to question 3.

Browser version is Mozilla Firefox 115.0.1

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
