### ISSUE TITLE
Bug: Nonsensical redirect for next chapter at end of chapters

### ISSUE THREAD

**Issue by micpap25** [Qiskit/platypus#1817]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-gates/classical-computation-on-a-quantum-computer

### What is the content issue?

The next chapter that is linked to at the end of a chapter is often nonsensical.
Chapter 1 links to the examples page; Chapter 2 links to Chapter 7, and the Quantum Information course links to Chapter 3. 
This should be changed so each chapter logically leads to the next.

### Screenshots

<img width="689" alt="image" src="https://user-images.githubusercontent.com/34077605/212392217-fdf9d79c-45a7-4067-b1b6-e6aa25ba403f.png">

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
