### ISSUE TITLE
Bug:  QAOA Lecture: Links in Appendix - Section 5 don't work

### ISSUE THREAD

**Issue by 099NikStone** [Qiskit/platypus#1835]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-applications/solving-combinatorial-optimization-problems-using-qaoa

### What is the content issue?

In Appendix Section 5 - Problems - At the bottom of the course/ lecture:

Links in this section don't work.

The problem sets refer to addtional material and provided solitions, with clickable links. 
Upon clicking the links, nothing happens - the web address changes but, nothing else. 
Opening the link in a new window will just display the lecture from the beginning, not leading to the refered section. 

Maybe the content, that is being referred to just doesn't exist?

### Screenshots

![Git](https://user-images.githubusercontent.com/123097523/213489748-39ed5ce6-17a3-4327-b0ab-150d8c1b7547.png)

**Comment by jonathanortega2023** [comment]
New and old textbook contain the same references to missing Qiskit implementations of text formulations, which contradicts most of the problem prompts.
![image](https://user-images.githubusercontent.com/34843188/224554765-144259b9-500f-4b9d-928c-bb8046bf443a.png)

![image](https://user-images.githubusercontent.com/34843188/224554233-a62bbfb0-ef8c-4e7f-9c79-24b3e384d173.png)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
