### ISSUE TITLE
Update code in VQE page

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#1840]
### Feature description

We should update some of the code in the VQE page in advance of upcoming deprecation:

- [ ] Import from `qiskit_aer` instead of `qiskit.providers`
- [ ] ~~Migrate to Qiskit Nature `5.0.0` ([migration guide](https://qiskit.org/documentation/nature/migration/index.html))~~ Moved to #1893
- [ ] Use QubitConvertor/ParityMapper instead of opflow
- [ ] Use estimator primitive ([reference tutorial](https://qiskit.org/documentation/tutorials.html#algorithms))

### Additional context

Thanks to @woodsp-ibm (see comments in https://github.com/Qiskit/platypus/pull/1820 thread).

**Comment by SamYuan1990** [comment]
do we have `qiskit_aer ` migration guide? as there a lot of parts need to migrate from `qiskit.providers`

**Comment by woodsp-ibm** [comment]
For Aer it should just be where Aer was accessed via providers. This is from release notes for Terra

> To avoid any potential issues starting with this release, updating all imports from qiskit.providers.aer to qiskit_aer and from qiskit.Aer to qiskit_aer.Aer is recommended.

Where this release above was Qiskit 0.38.0 and its part of the [Aer upgrade notes there](https://qiskit.org/documentation/release_notes.html#release-notes-aer-0-11-0-upgrade-notes)

**Comment by SamYuan1990** [comment]
> For Aer it should just be where Aer was accessed via providers. This is from release notes for Terra
> 
> > To avoid any potential issues starting with this release, updating all imports from qiskit.providers.aer to qiskit_aer and from qiskit.Aer to qiskit_aer.Aer is recommended.
> 
> Where this release above was Qiskit 0.38.0 and its part of the [Aer upgrade notes there](https://qiskit.org/documentation/release_notes.html#release-notes-aer-0-11-0-upgrade-notes)

> updating all imports....
I suppose this will impacts for most of notebooks, should we make it in another issue?

**Comment by frankharkins** [comment]
@SamYuan1990 yes please

**Comment by david-alber** [comment]
@frankharkins what is the status of this issue? I would love to be assigned for updating the textbook w.r.t primitives and ParityMapper/QubitConertor.

**Comment by frankharkins** [comment]
I'm not sure, @SamYuan1990 are you working on this? If not then @david-alber I will assign you

**Comment by david-alber** [comment]
@SamYuan1990 , @frankharkins: I'll give it a try 😀.

**Comment by frankharkins** [comment]
@david-alber thank you!

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
