### ISSUE TITLE
Bug: Internal Grader Bug

### ISSUE THREAD

**Issue by divshacker** [Qiskit/platypus#1857]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/problem-sets/single_systems_problem_set/problem-5
2. The question is to make a specific bell state by using different gates. 
3. The answer and code should be 

```
from qiskit import *

# Start your work here.
# We've provided the circuit that is shown above
# Your circuit MUST be named qc

qc = QuantumCircuit(2)
qc.x(0)
qc.x(1)
qc.h(1)
qc.cx(1,0)
qc.draw()
```
![image](https://user-images.githubusercontent.com/55018955/214667312-d336ecb4-575f-46c1-b8ae-01b08446b310.png)

### What is the current behavior?

The Grader shows this, which is not expected as the answer given is correct. 
```
Grading your answer. Please wait...

Oops 😕! Your answer is incorrect
Please review your answer and try again.

```

### What is the expected behavior?

The grader should grade it correctly and mark this correct.

**Comment by micpap25** [comment]
I'm getting internal server errors everywhere. Will look into this when this stops happening.

**Comment by vabarbosa** [comment]
@pandasa123 for this, is it the (state) in the question or validation in the grade that should be updated?

**Comment by pandasa123** [comment]
Hey @vabarbosa, this should be the grader

**Comment by vabarbosa** [comment]
Fixed
<img width="690" alt="image" src="https://user-images.githubusercontent.com/13156555/223608976-d9eb1c3d-448b-4090-a912-0a53002ccf66.png">
