### ISSUE TITLE
Mention the Discrete Logarithm Problem in the Shor's Algorithm page

### ISSUE THREAD

**Issue by micpap25** [Qiskit/platypus#1860]
### Feature description

The Discrete Logarithm Problem is brought up and discussed in a form but isn't explicitly named. Doing so would help readers find further resources to study. 

### Additional context

<img width="479" alt="image" src="https://user-images.githubusercontent.com/34077605/214949624-f6514a87-efd8-47ea-b7df-2f5a17b444d8.png">
<img width="406" alt="image" src="https://user-images.githubusercontent.com/34077605/214949646-c25c060e-f406-4bf5-a338-0c6cc277f302.png">

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
