### ISSUE TITLE
Bug: HTML title apostrophe encoding

### ISSUE THREAD

**Issue by chutommy** [Qiskit/platypus#1922]
### Steps to reproduce the problem

Go to [https://learn.qiskit.org/course/introduction/grovers-search-algorithm](https://learn.qiskit.org/course/introduction/grovers-search-algorithm).

### What is the current behavior?

In the HTML title, there is:

>Grover`&#39;`s search algorithm

instead of

>Grover’s search algorithm.

The whole title can be seen after floating the cursor over the browser tab.

### What is the expected behavior?

Correct HTML title encoding.

## PC browser
![image](https://user-images.githubusercontent.com/51094650/219944736-bf1ee41e-67d5-4384-b343-0a8b639329e6.png)

## Phone browser
![image2](https://user-images.githubusercontent.com/51094650/219944886-3a587529-0221-4608-8f83-f8f30ba6a86a.png)

### Device

Laptop, Smartphone

### OS

Ubuntu, Android

### Browser

Chrome

### Additional information

Similar and possibly related to https://github.com/Qiskit/platypus/issues/1539

**Comment by mustapha-saad-codeStar** [comment]
Can I work on this issue?

**Comment by vabarbosa** [comment]
> Can I work on this issue?

@mustapha-saad-codeStar please feel free to do so, if you want. let us know if you have any questions. thank you!

**Comment by mustapha-saad-codeStar** [comment]
Sure, thank you.

You haven't assigned me to the issue yet...

**Comment by micpap25** [comment]
@mustapha-saad-codeStar any updates?

**Comment by chutommy** [comment]
I noticed a similar issue on the Shor's algorithm page (https://learn.qiskit.org/course/ch-algorithms/shors-algorithm):

![image](https://user-images.githubusercontent.com/51094650/226119277-dea6a776-3af0-4573-8db6-883d4f251486.png)

The problem seems to be only appearing on some pages. There are sites that contain single quotation mark as well, but do not experience the same issue with the HTML title:

* https://learn.qiskit.org/course/ch-algorithms/grovers-algorithm
* https://learn.qiskit.org/course/ch-labs/lab-7-scalable-shors-algorithm
* https://learn.qiskit.org/summer-school/2020/shors-algorithm-i-fourier-transform-phase-estimation

**Comment by Andir16** [comment]
It depends on what symbol was used to display the apostrophe.

For Shor's (https://learn.qiskit.org/course/ch-algorithms/shors-algorithm) the ' was used and that doesn't work properly.
<img width="451" alt="shor1" src="https://github.com/Qiskit/platypus/assets/59705382/2d13253c-4a99-4543-8823-9d651cc0063a">

For Grover's (https://learn.qiskit.org/course/ch-algorithms/grovers-algorithm) the ´ was used and that works correctly.
<img width="443" alt="grover1" src="https://github.com/Qiskit/platypus/assets/59705382/ed38a220-64e4-40e0-b6d6-37d7f9c6423c">

@mustapha-saad are you still working on that?

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
