### ISSUE TITLE
Display execution status of runnable code cells

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit/platypus#1933]
### Details 
If runnable cell does not have any output to stdio, then it's hard to figure out wether cell was executed or not

### How it can be enhanced?
Maybe we should put checkmark ✅  on executed cells or show execution datetime (like jupyter notebooks are showing)

### Screenshots

Cell below was executed, but there is no information on that
<img width="806" alt="Screen Shot 2021-10-22 at 10 03 41 AM" src="https://user-images.githubusercontent.com/8796709/138467621-da36af37-1393-4e4f-af87-5dfebf3cf721.png">

Example of jupyter plugin to show execution times of cells
<img width="799" alt="Screen Shot 2021-10-22 at 10 05 53 AM" src="https://user-images.githubusercontent.com/8796709/138468012-87398855-566f-4497-8330-870b2f09bb99.png">

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
