### ISSUE TITLE
French Localization

### ISSUE THREAD

**Issue by Theo-Reignier** [Qiskit/platypus#1960]
### Feature description

I would like to request a **French translation** of the Qiskit Textbook.

France is strongly engaged with Quantum technologies, and the government is setting initiatives/programs to become a leader in the industry. I believe that **French localization** would be very valuable.

### Additional context

Unfortunately, I haven't been able to gather French contributors or proof-readers yet.
I would be happy to join as a **contributor and/or proof-reader**.

**Comment by vabarbosa** [comment]
FYI, @Qiskit/qiskit-translation
