### ISSUE TITLE
Bug: 404 on Problem Sets link

### ISSUE THREAD

**Issue by micpap25** [Qiskit/platypus#2005]
### Where does the issue happen?

https://learn.qiskit.org/problem-sets

### What is the content issue?

This link leads to a 404 even though it is in the Content dropdown. It should redirect to a problem set like https://learn.qiskit.org/problem-sets/single_systems_problem_set/problem-1

### Screenshots

<img width="137" alt="image" src="https://user-images.githubusercontent.com/34077605/225952007-9253c228-634a-4e04-84e5-4fc4be7855d4.png">

**Comment by micpap25** [comment]
@vabarbosa Would you happen to know either how to 1. define a redirect on `/problem-sets` or 2. create a new page at `/problem-sets` as a landing page

**Comment by vabarbosa** [comment]
@micpap25 redirecting from `/course/<courseId>` to `/course/<courseId>/<sectionId>` is actually taken care of by the framework (Mathigon Studio) being used. see the code here: https://github.com/mathigon/studio/blob/main/server/app.ts#L295-L314

we do the same thing with the summer school content i.e., redirect
from `https://learn.qiskit.org/summer-school/2022` 
to `https://learn.qiskit.org/summer-school/2022/history-quantum-computing-motivation-quantum-simulation`
and you can see this code here: https://github.com/Qiskit/platypus/blob/main/server/app.ts#L213-L234

**Comment by micpap25** [comment]
That is different from what I am trying to do; it would be the equivalent of redirecting from https://learn.qiskit.org/summer-school to a summer school course. I don't believe this is possible with Mathigon Studio.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
