### ISSUE TITLE
Grammar in Quantum Coin Game page needs substantial review

### ISSUE THREAD

**Issue by micpap25** [Qiskit/platypus#2008]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-demos/coin-game

### What is the content issue?

The writing of this page needs substantial reworking to put it in line with the rest of the textbook. Attached are the first two paragraph which are similar to other paragraphs on the page.

### Screenshots

<img width="431" alt="image" src="https://user-images.githubusercontent.com/34077605/226211422-249d6687-5f02-49f2-8a2c-34dc47fb3bbe.png">

### Additional information

Could be grouped with #1557 under issues pertaining to reworking the grammar of English articles

**Comment by micpap25** [comment]
I will try to make a commit that fixes this and #1557 soon

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
