### ISSUE TITLE
Pathway for readers to submit issues/comments from learn.qiskit.org

### ISSUE THREAD

**Issue by kdk** [Qiskit/platypus#2040]
### Feature description

As far as I was able to tell, there isn't a clear way for readers to find out how or where they should submit feedback/suggestions/corrections for content on https://qiskit.org/learn/ . It might be helpful if there were either a form for feedback submission, or a link to this repository so that users can open issues directly.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
