### ISSUE TITLE
Bug: complex conjugation not rendered

### ISSUE THREAD

**Issue by gavinking** [Qiskit/platypus#2041]
### Where does the issue happen?

https://learn.qiskit.org/course/basics/quantum-circuits#quantum-16-0

### What is the content issue?

In section 2.1 of this Python notebook:

<https://github.com/Qiskit/platypus/blob/main/notebooks/basics/quantum-circuits.ipynb>

There are a number of uses of `\overline{...}` to indicate complex conjugation.

But these are missing from the website version here:

<https://learn.qiskit.org/course/basics/quantum-circuits#quantum-16-0>

### Screenshots

<img width="1130" alt="Screenshot 2023-03-29 at 6 26 15 PM" src="https://user-images.githubusercontent.com/579974/228605565-4d55f3c0-44bc-4301-bcca-d6519acdd91c.png">
<img width="620" alt="Screenshot 2023-03-29 at 6 26 53 PM" src="https://user-images.githubusercontent.com/579974/228605575-2fec1906-e778-4819-95d2-f20984dcacaa.png">
<img width="1080" alt="Screenshot 2023-03-29 at 6 28 10 PM" src="https://user-images.githubusercontent.com/579974/228605849-eef265ec-e1ab-48b4-9e4a-bbb954cd28e3.png">
<img width="661" alt="Screenshot 2023-03-29 at 6 28 24 PM" src="https://user-images.githubusercontent.com/579974/228605866-c02c13a1-11d0-4756-bcf8-55a13adafd28.png">

**Comment by kdk** [comment]
Just to add a datapoint, these _do_ appear for me in the textbook version of the page, but only in Firefox (ver. 109.0.1) and Chrome (103.0.5028.0). 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/2241698/230503477-690a50ec-183c-4b4c-82be-e3d03ea4d35a.png">

but are missing in Safari (16.3):

<img width="716" alt="image" src="https://user-images.githubusercontent.com/2241698/230503677-ed3a5980-5b79-40a8-94c2-6bcdb4aa07ae.png">

**Comment by gavinking** [comment]
Ah, yeah, sorry, my bad, I should have specified that this was on Safari.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
