### ISSUE TITLE
Bug: Randomized benchmarking still using Ignis

### ISSUE THREAD

**Issue by coruscating** [Qiskit/platypus#2052]
### Where does the issue happen?

https://learn.qiskit.org/course/quantum-hardware/randomized-benchmarking

### What is the content issue?

Chapters using Ignis, which is no longer supported, should switch to Qiskit Experiments. The update was in progress in the old textbook (see https://github.com/qiskit-community/qiskit-textbook/pull/1480) but it was decided the work should be done here.

**Comment by coruscating** [comment]
Will be done once https://github.com/Qiskit/textbook/pull/20 is live.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
