### ISSUE TITLE
Bug: Cannot run the quiskit aer simulator

### ISSUE THREAD

**Issue by nuvinga** [Qiskit/platypus#2062]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-applications/hybrid-quantum-classical-neural-networks-with-pytorch-and-qiskit

### What is the content issue?

I was running the code locally and came across an error saying that the example uses a deprecated package in the defined quantum circuit. The circuit is using a qobj for run() is deprecated as of qiskit-aer 0.9.0.

### Screenshots

![image](https://user-images.githubusercontent.com/61136277/231271524-effd769d-ff21-4c65-aca9-5bcd36a2ac65.png)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
