### ISSUE TITLE
As a learner, I want to navigate through the problems, so that I can complete the badge requirements

### ISSUE THREAD

**Issue by vandieren** [Qiskit/platypus#2079]
### Background

When I finish an exercise, it's not clear that I need to go back to the challenge page to click on the next exercise (and reload the challenge page to show progress has been made) to then be sent back to the IBM Quantum Lab in another tab (by the time I complete the badge, I have 5+ tabs open).  

Once I do reload the challenge page, it would be nice that the page resets to the next exercise that I need to complete (e.g. if I completed exercise 1, the page would open to exercise 2).  

When I open up the badge page I want to go back to the lesson but there is no link.  
When I am in an exercise, I want to refer back to the lesson, but there is no link.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
