### ISSUE TITLE
Bug: code cells in Variational Algo course not running

### ISSUE THREAD

**Issue by vandieren** [Qiskit/platypus#2080]
### Where does the issue happen?

https://learn.qiskit.org/course/algorithm-design/applications

### What is the content issue?

I'm getting error messages when I try to run the code cells using both safari and chrome on a Mac in the [examples and applications section](https://learn.qiskit.org/course/algorithm-design/applications) of the course.

<img width="708" alt="233463588-5b75acdb-bd4f-4f90-90e0-6205e25f144c" src="https://user-images.githubusercontent.com/6241840/234959279-af14d412-d12c-42b2-b210-75a8a75df40a.png">

**Comment by Raghav-Bell** [comment]
Please check your `api token`. For more support you can post on slack too.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
