### ISSUE TITLE
As a learner in the variational Algorithm course, I want to see a message when I finish the badge activities, so that I know what to expect as next steps.

### ISSUE THREAD

**Issue by vandieren** [Qiskit/platypus#2083]
### Background

When completing the badge requirements for the variational algorithm course, it is not apparent if all the steps have been completed and registered and/or if there are any additional steps needed to get the badge.  Maybe a message that says congrats, your badge will be processed soon, you should receive an email soon...  Or something to that effect.

Currently the end page looks identical to an in progress page.
<img width="1490" alt="Screenshot 2023-04-21 at 9 25 16 AM" src="https://user-images.githubusercontent.com/46763032/233648090-a4655e5b-2504-4790-b3f1-83624312ff37.png">

### Goal

leave the learner with a sense of accomplishment and the knowledge that there are no administrative tasks remaining on their end

**Comment by pandasa123** [comment]
I believe there's a popup that should appear. @vabarbosa?

**Comment by vabarbosa** [comment]
yes, you should see a dialog popup as well as well as the badge title should become a clickable link. 
@vandieren what browser are you using?

**Comment by vandieren** [comment]
@vabarbosa I am in safari and in chrome on a Mac.  My pop-ups were blocked, so I'm wondering if that was the issue.  When I unblock the pop ups and reload on chrome, I don't see the pop-up.  When I do so on safari, I get this pop-up which is in the screenshot below.  Since is the congratulations pop-up, it probably doesn't need the text about the number of questions required (since that has been completed).
<img width="687" alt="Screenshot 2023-04-21 at 12 35 49 PM" src="https://user-images.githubusercontent.com/46763032/233689942-37325ec8-ba27-4f6f-9f25-5a0fb2c200c6.png">


Nothing that I can tell is now clickable on the site or the pop up.

**Comment by vabarbosa** [comment]
hi, that is sidebar text which should always be present (that is not the popup). 
maybe when you have some time you can ping me and we can do a screenshare.

see screenshots below to see what i am referring:

![image](https://user-images.githubusercontent.com/13156555/233691116-842dd796-219c-41dc-9434-9dfa33794bd6.png)

![image](https://user-images.githubusercontent.com/13156555/233691240-12264f89-503d-45ca-8e9f-ff94ccb4a033.png)

**Comment by vabarbosa** [comment]
this should be resolved. @vandieren thanks for helping debug
