### ISSUE TITLE
Bug: Typo in variational algorithm course

### ISSUE THREAD

**Issue by vandieren** [Qiskit/platypus#2089]
### Where does the issue happen?

https://learn.qiskit.org/course/algorithm-design/ansatz

### What is the content issue?

In bullet point 3 under the section titled N-local circuits, there is an extra "T" in front of Toffoli

For an entanglement layer, we can use gates like T[Toffoli gates](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CCXGate.html) or [CX](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CXGate.html#qiskit.circuit.library.CXGate) wi

**Comment by pandasa123** [comment]
[Fixing in PR](https://github.com/Qiskit/platypus/pull/2090)
