### ISSUE TITLE
Suggestions to make it more clear that there are Lesson Notes and a Glossary

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/platypus#2091]
### Feature description

In the Dev Forum Qiskit 101 session, we got some user feedback that they did not realize the textbook has a glossary. They did not realize that you could click this arrow to change the page toggle.

<img width="207" alt="Screenshot 2023-04-27 at 4 26 28 PM" src="https://user-images.githubusercontent.com/14852634/234982984-fa8cd8b2-a4c8-4137-be7b-83ae72152ba1.png">

Some ideas for how we could make this more clear:

* Replace the down arrow icon with a hamburger icon or `...` icon. Although, we always use down arrows in our design language, so I'm not sure it's possible.
* Switch the dropdown to tabs. Although, this takes more vertical space
* Add a label, like `Page: Scratchpad` or `Details: Scratchpad`. Although, this takes more vertical space.

Each of these 3 ideas has downsides. Of course, feel free to close this if you don't think the changes are worth it.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
