### ISSUE TITLE
alignment of the course content

### ISSUE THREAD

**Issue by blesso1quanta** [Qiskit/platypus#2107]
### Feature description

After closing the scratchpad using the hide details and the index the text is entirely left-aligned and a lot of unwanted white space is present on the right side a more reader-friendly alignment is requested 

### Additional context

possible solutions
after closing the scratchpad and index
max-content width can be increased from 46rem to 100rem
or
centre align the text and the code

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
