### ISSUE TITLE
Bug: MissingOptionalLibraryError: The 'seaborn' library is required to use 'plot_state_qsphere'.

### ISSUE THREAD

**Issue by yuttai** [Qiskit/platypus#2108]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-labs/lab-4-bell-ghz-circuit

### What is the content issue?

When I run "Lab 4 Bell Circuit & GHZ Circuit", it asked me to install 'seaborn' library. I guess because of the same issue, the built-in pictures don't display correctly...

### Screenshots

![image](https://github.com/Qiskit/platypus/assets/15096557/d2fa4b75-ae83-4b37-a49c-7422ed53e26e)

**Comment by Raghav-Bell** [comment]
I am not able to reporoduce this error. Can you please attach code block image too ?
![image](https://github.com/Qiskit/platypus/assets/83136390/c00e32e6-923c-49be-813a-ed40f6eaac21)

**Comment by vabarbosa** [comment]
@yuttai unfortunately `seaborn` is not one of the installed libraries in the environment. did you edit the code cell to try to use `seaborn`? if so, can you instead try to use `matplotlib` or `bokeh`? both should be available in the environment

**Comment by vabarbosa** [comment]
@yuttai i was able to reproduce your issue i will take a look into possibly adding `seaborn` to the environment
@Raghav-Bell you can reproduce by trying to run `plot_state_qsphere` i.e., un-commenting the code cell like such:

<img width="718" alt="image" src="https://github.com/Qiskit/platypus/assets/13156555/0dcc88af-f6cc-4bd4-aeb9-348e0ef478a2">

**Comment by vabarbosa** [comment]
@frankharkins does it make sense to [add `seaborn`](https://github.com/Qiskit/platypus-binder/pull/37) or should the notebook be updates to remove `plot_state_qsphere`

**Comment by frankharkins** [comment]
Thanks; let's add it for now, I don't think it should have a negative impact.
