### ISSUE TITLE
Bug: multiple choice not working in textbook

### ISSUE THREAD

**Issue by vandieren** [Qiskit/platypus#2114]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-states/representing-qubit-states#rules-measurement

### What is the content issue?

The option to select "0 or 1" does not work.  I am able to select "1" or "0" or "-1 and 1" but the correct option cannot be clicked.
<img width="809" alt="Screenshot 2023-05-26 at 9 56 19 AM" src="https://github.com/Qiskit/platypus/assets/46763032/e9e5daaa-6048-45d0-96f8-333756eac593">

**Comment by Raghav-Bell** [comment]
@vandieren I could n't reproduce the issue. It is working correctly for me (see below).
![image](https://github.com/Qiskit/platypus/assets/83136390/254d61c4-2155-4f6f-871d-b3f5e9a8473e)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com)
