### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/platypus#2118]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-algorithms/shors-algorithm

### What is the content issue?

Bad link

> Shor’s solution was to use [quantum phase estimation](https://learn.qiskit.org/course/ch-algorithms/quantum-phase-estimation.html) on the unitary operator:

The link is 404

### Screenshots

![image](https://github.com/Qiskit/platypus/assets/4604036/72835511-dd6d-47ee-892f-15e665207626)

**Comment by Raghav-Bell** [comment]
You can use this link [quantum phase estimation](https://learn.qiskit.org/course/ch-algorithms/quantum-phase-estimation).

**Comment by Raghav-Bell** [comment]
@vabarbosa  even after merge of PR #2129 , this issue did not fix.  I can make a new PR for same but i don't understand why didn't it work ?

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com)
