### ISSUE TITLE
Update deploy action to set build_args

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/platypus#2120]
with the update in https://github.com/Qiskit/gh-actions/pull/45 the deploy workflow has been updated to make use of `BUILD_ARGS` (thanks @Eric-Arellano). 

this repo's action should be updated to make use of the `build_args`. this allows for a more generic deploy GitHub action that can be used by more repos

**Comment by Eric-Arellano** [comment]
We could not get this working in https://github.com/Qiskit/qiskit.org/pull/3285 due to issues with passing secrets to `with.build_args`. ChatGPT's suggestion of using env vars didn't work either.

This isn't high priority enough to pursue further.

Can an admin or @vabarbosa close this, please?
