### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by nasir26** [Qiskit/platypus#2130]
### Where does the issue happen?

https://learn.qiskit.org/course/v2_ch-states/atoms-computation

### What is the content issue?

Aer.get_backend is not appearing correctly here https://learn.qiskit.org/course/v2_ch-states/atoms-computation  I tried to fix the issue through Qiskit/textbook issue #44 code block is written as ```Aer.get_backend('aer_simulator')``` I changed it to inline code `Aer.get_backend('aer_simulator')` but that is still not fixing the issue. That means the problem is not with .ipynb but when it appears here https://learn.qiskit.org/course/v2_ch-states/atoms-computation at the page.

### Screenshots

![Screenshot from 2023-06-20 07-54-52](https://github.com/Qiskit/platypus/assets/39465244/37d048f9-4766-43e4-beee-9a2f6fb1ef50)

### Additional information

It should appear as Aer.get_backend('aer_simulator')  at https://learn.qiskit.org/course/v2_ch-states/atoms-computation

**Comment by Algh89110377** [comment]
Hi, Can I ask a naive question? I noticed that there are common issues, here and in the textbook repository that links are not working in the textbook webpage. In all of those cases, the notebooks that are being read are in the "/course/..." directories.  I cannot find the "/course/..." directory. For example here, we have "/course/v2_ch-states/..." but if the webpage was reading notebooks from this repository it should have been ".../v2/ch-states/..." and fixing the Aer.get_backend('aer_simulator') in corresponding jupyter notebook in this repository would have solved the format in the webpage. 
I am pretty new to contributing to qiskit code. I will really appreciate if you tell me where is "/course/" directory.

**Comment by nasir26** [comment]
Yes, and I mentioned that. I am also new to this thanks for pointing it, overall I am focused that the problem should be resolved.

**Comment by Raghav-Bell** [comment]
@Algh89110377 Yes you should change in the jupyter notebook - [atoms-computation.ipynb](https://github.com/Qiskit/platypus/blob/main/notebooks/v2/ch-states/atoms-computation.ipynb). But it is correctly written in that . I think problem is between markdown and latex . There is similar issue #2131 .
