### ISSUE TITLE
Shor&#39;s Algorithm instead of Shor's Algorithm webpage title

### ISSUE THREAD

**Issue by Raghav-Bell** [Qiskit/platypus#2131]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-algorithms/shors-algorithm

### What is the content issue?

In both the version (v1 and v2) Shor's Algorithm title is Shor& # 39;s Algorithm instead of Shor's Algorithm.

### Screenshots

![Screenshot 2023-06-19 095238](https://github.com/Qiskit/qiskit.org/assets/83136390/7bb2f6b7-f2bc-4eb3-a713-ac89b1fe1b00)

**Comment by Raghav-Bell** [comment]
This issue is similiar to the issue #1922 .

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com)
