### ISSUE TITLE
Bug: Old URL https://qiskit.org/learn/course/* is not redirected to new URL https://learn.qiskit.org/course/*

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/platypus#2150]
### Steps to reproduce the problem

1. Go to https://qiskit.org/learn/course/ch-algorithms/shors-algorithm/
2. See 404

![image](https://github.com/Qiskit/platypus/assets/7631333/b5099e4b-44e7-445b-a21e-0e6d0f1af3cf)

### What is the current behavior?

404

### What is the expected behavior?

Redirect to the new URL: https://learn.qiskit.org/course/ch-algorithms/shors-algorithm

**Comment by HuangJunye** [comment]
Old textbook should also redirect: https://qiskit.org/textbook/ch-algorithms/shor.html

**Comment by Raghav-Bell** [comment]
@HuangJunye it seems  [ https://qiskit.org/textbook/ch-algorithms/shor.html](https://qiskit.org/textbook/ch-algorithms/shor.html ) redirects to [https://qiskit.org/learn/course/ch-algorithms/shors-algorithm/](https://qiskit.org/learn/course/ch-algorithms/shors-algorithm/).

**Comment by HuangJunye** [comment]
> @HuangJunye it seems [ https://qiskit.org/textbook/ch-algorithms/shor.html](https://qiskit.org/textbook/ch-algorithms/shor.html) redirects to https://qiskit.org/learn/course/ch-algorithms/shors-algorithm/.

Yes, you are right. It guess the there were a few different migrations and a further redirect is needed to redirect https://qiskit.org/learn/* to https//learn.qiskit.org/*
