### ISSUE TITLE
Bug: Shor's algorithm tutorial appear in search results but leads to 404

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/platypus#2151]
### Steps to reproduce the problem

1. Go to https://qiskit.org/learn/
2. Search for "Shor"
<img width="788" alt="Screenshot 2023-07-07 at 11 06 24" src="https://github.com/Qiskit/platypus/assets/7631333/3bfddf90-8d73-4515-8df0-8940e76c4e63">

3. Click on Shor's algorithm tutorial (https://qiskit.org/documentation/tutorials/algorithms/08_factorizers.html)
4. See 404 error

### What is the current behavior?

404 error

### What is the expected behavior?

Shor's algorithm tutorial should not appear in the search result or it should link to the stable release where shor's algorithm tutorial still exist. (The tutorial was removed in https://github.com/Qiskit/qiskit-tutorials/pull/1368)

**Comment by Raghav-Bell** [comment]
Can i work on this problem?

**Comment by chutommy** [comment]
It appears that there are two identical instances of the same code in two different locations
* Qiskit/platypus: https://github.com/Qiskit/platypus/blob/main/frontend/vue/components/constants/megaMenuLinks.ts#L1097
* Qiskit//qiskit.org: https://github.com/Qiskit/qiskit.org/blob/main/components/Learn/LearnMegaMenu.vue#L1301

I'm not sure whether these two codes are connected or if they are maintained independently in parallel.

Based on the [migration guide](https://qiskit.org/documentation/migration_guides/algorithms_migration.html):
![image](https://github.com/Qiskit/platypus/assets/51094650/e8b97868-ee15-49d8-a71b-e2a79343bc9b)
it seems that the link under the **Algorithms** section should be completely removed.
It refer's to the other version of _Shor's algorithm_ that appears in the same search query under the **Quantum Protocols and Quantum Algorithms** section (as it is suggested in the provided image).
