### ISSUE TITLE
Bug: Cannot search Japanese contents at https://qiskit.org/learn/

### ISSUE THREAD

**Issue by kifumi** [Qiskit/platypus#2156]
### Steps to reproduce the problem

1. Go to [Qiskit Textbook](https://qiskit.org/learn/)
2. At the cell of `Browse all content`, input Japanese word `グローバー` which means `Grover` in English.
3. Cannot search that word and see `Nothing here`.

I cannot search any Japanese word.

Now, the old Qiskit Textbook Japanese edition link, https://qiskit.org/textbook/ja/preface.html, is redirected to the [new Qiskit Textbook front page](https://qiskit.org/learn/), so most of Japanese people cannot find the Japanese contents.

### What is the current behavior?

See `Nothing here`. 

<img width="967" alt="image" src="https://github.com/Qiskit/platypus/assets/19249007/33790ddc-6fc1-49df-90d6-5262c9e8daa6">

### What is the expected behavior?

Expected to see the Japanese contents.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com)
