### ISSUE TITLE
Bug: IBMRuntimeService being used

### ISSUE THREAD

**Issue by elvis2** [Qiskit/platypus#2157]
### Where does the issue happen?

https://lab.quantum-computing.ibm.com/user/xxx/files/qiskit-textbook/getting-started/example.ipynb

### What is the content issue?

I'm participating in the Quantum Explorers and ran into an issue with a ipynb file.

I believe the below problem is fixed on the main branch of platypus

Unfortunately, 

> https://lab.quantum-computing.ibm.com

Is populating the ipynb files from the stable branch.

## Broken Code

The executable code in the Transpiler section, is using a deprecated service (IE: IBMRuntimeService)

> service = IBMRuntimeService('<API token>')
backend = service.get_backend('ibmq_santiago')
>
> optimized_circuit = qiskit.transpile(quantum_circuit, backend)
optimized_circuit.draw()

The executable code in the "Run on real hardware" section, will more than likely fail too

>job = service.sample(circuits, backend)
>retrieved_job = backend.job(job.job_id())
>result = retrieved_job.result()

since _**service**_ is failing in the above example.

Simply replacing 

> service = IBMRuntimeService('<API token>')

with

> from qiskit_ibm_runtime import QiskitRuntimeService
> service = QiskitRuntimeService(channel="ibm_quantum")

will still throw an error since the .sample member does not exist in the QiskitRuntimeService class.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It and its content has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com)
