### ISSUE TITLE
Create a banner to announce the new Learning Platform

### ISSUE THREAD

**Issue by y4izus** [Qiskit/platypus#2158]
### Feature description

To announce the new Learning Platform we need to add a banner right below the top menu. It should be the same as [the one we have on qiskit.org](https://github.com/Qiskit/qiskit.org/pull/3411)

### Additional context

The current banner we have is purple, so we need to adapt it to this new style

Wait to merge until Learning Platform team says we can merge

Do not add the new learning platform link until it's launched

The more info blog is still being written, so we should add the link when we have it

**Comment by techtolentino** [comment]
Adding the `On hold` label for now, until it resurfaces as a priority

**Comment by mackinziblank** [comment]
Updating w/ new designs to announce the Learning platform! 

2 parts - large graphic on Textbook home page, and smaller banners on individual pages.

Home page graphic:
<img width="855" alt="image" src="https://github.com/Qiskit/platypus/assets/59657965/fcd640c7-848c-48b5-9ea9-1b36ce2a0f9a">


Smaller banners (same as what will appear in docs, as described in https://github.com/Qiskit/qiskit_sphinx_theme/pull/530): 
<img width="932" alt="image" src="https://github.com/Qiskit/platypus/assets/59657965/0a41311d-8e2f-4b35-bfa8-c31a89d1ffba">
