### ISSUE TITLE
All tutorial links are broken (error 404)

### ISSUE THREAD

**Issue by Raghav-Bell** [Qiskit/platypus#2172]
### Where does the issue happen?

https://qiskit.org/learn/

### What is the content issue?

All the tutorial links are broken.
Can be checked on following links:
1) [Circuit Tutorials](https://qiskit.org/documentation/tutorials/circuits/index.html)
2) [Advanced Circuit Tutorials](https://qiskit.org/documentation/tutorials/circuits_advanced/index.html)
3) [High-Performance Simulator Tutorials](https://qiskit.org/documentation/tutorials/simulators/index.html)
4) [Algorithms Tutorials](https://qiskit.org/documentation/tutorials/algorithms/index.html)
5) [Operators Tutorials](https://qiskit.org/documentation/tutorials/operators/index.html)

### Screenshots

![image](https://github.com/Qiskit/platypus/assets/83136390/e19ad27d-11f3-48e9-a984-e3aa98648448)

**Comment by chloepilonv** [comment]
Same! I was about to post about this. Has it been resolved?

**Comment by chloepilonv** [comment]
Some seem to be available here : https://github.com/Innanov/Qiskit-Global-Summer-School-2022

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It and its content has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com)
