### ISSUE TITLE
Bug: Simon's problem math not rendering

### ISSUE THREAD

**Issue by jacobwatkins1** [Qiskit/platypus#2186]
### Where does the issue happen?

https://learn.qiskit.org/course/algorithms/query-algorithms#query-37-6

### What is the content issue?

In the description of Simon's problem, "Promise:" there is unrendered mathematics.

### Screenshots

<img width="961" alt="Screenshot 2023-08-23 at 12 44 37 PM" src="https://github.com/Qiskit/platypus/assets/29473076/b7e6b08c-05b5-4d2c-bba4-22910440b980">

**Comment by Raghav-Bell** [comment]
Please assign this issue to me.
