### ISSUE TITLE
Handling of typos in textbook

### ISSUE THREAD

**Issue by Andir16** [Qiskit/platypus#2193]
I noticed a typo in the following notebook:
https://learn.qiskit.org/course/quantum-hardware/introduction-to-quantum-error-correction-via-the-repetition-code

I opened a PR (#2184 ) three weeks ago (I haven't received any feedback or review yet) and wanted to ask what the correct way is to address typos that are found. 

I would like to follow the correct way to make such corrections and contributions :)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It and its content has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com)
