### ISSUE TITLE
Pull request tests are failing due to Cypress error

### ISSUE THREAD

**Issue by Raghav-Bell** [Qiskit/platypus#2200]
### Steps to reproduce the problem

1. Open a PR with typo issues are resolved

### What is the current behavior?

Cypress Tests are failing with following (similiar) errors:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Error: Cypress tests: 3 failed
```

### What is the expected behavior?

Cypress Tests should pass

### Additional information

Check PRs #2184 ,#2162 and #2152.

**Comment by Raghav-Bell** [comment]
It might be due to the case of putdate `github-action` version as newer version use node 20:
https://github.com/Qiskit/platypus/blob/5d9ba88dae9cba91e99ce2a1a06bb39462cae065/.github/workflows/test.yml#L50
https://github.com/Qiskit/platypus/blob/5d9ba88dae9cba91e99ce2a1a06bb39462cae065/.github/workflows/test.yml#L20-L25

**Comment by vabarbosa** [comment]
no longer maintained
