### ISSUE TITLE
Add GitHub "repository topics" to this repository

### ISSUE THREAD

**Issue by garrison** [Qiskit/platypus#240]
I believe this repository would benefit from the addition of some "tags."  The six currently listed at [qiskit-textbook](https://github.com/qiskit-community/qiskit-textbook) might be appropriate here as well:
- [quantum-mechanics](https://github.com/topics/quantum-mechanics)
- [learn-to-code](https://github.com/topics/learn-to-code)
- [quantum-computing](https://github.com/topics/quantum-computing) (EDIT: this one appears to have been added in the time since I opened this issue -- thanks!)
- [qiskit](https://github.com/topics/qiskit)
- [quantum-programming](https://github.com/topics/quantum-programming)
- [qiskit-textbook](https://github.com/topics/qiskit-textbook)

**Comment by pandasa123** [comment]
@garrison, @eddybrando I think we can close this out? We haven't seen these being used recently in the [qiskit-textbook](https://github.com/qiskit-community/qiskit-textbook/issues) repository or needing to be used here?

**Comment by garrison** [comment]
The point of adding GitHub tags to this repository is to make it more discoverable on github.com (I added links above to demonstrate).  I believe this could still be beneficial for this repository.

**Comment by eddybrando** [comment]
I think it makes sense to add this _repository topics_ as suggested. 🙂

I'll do so right now.

Thank you very much @garrison

**Comment by eddybrando** [comment]
Done.
