### ISSUE TITLE
As a learner, I would like to interact with code quickly while reading through the Textbook beta

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#252]
Goal: 

The goal with the scratchpad feature is to enable easier experimentation with coding as learners progress through the material. We have some data that shows cohorts of users that run code cells within the textbook perform better on relevant assessment questions compared to those that do not run at all. Giving more opportunities to run code should (in theory) further this understanding  and enable an even greater differentiation compared to only having the in-line code cells. 

Measure success: 
To measure success we will be looking at 2 key metrics: 

* number of times users clicked run in scratchpad
* cohort perfomance in mpc questions 

We need to implement the side panel "scratch pad" as designed in https://www.figma.com/file/tEpo1ZT4O7txFUT2aI0QAM/252-Python-Scratchpad?node-id=89%3A2837

- [x] #1015
- [x] #1016
- [x] #1017
- [x] ~Add section for results~ (not needed because it's already part of the component)
- [x] ~#1018~ (not part of v1)
- [x] #1019
- [x] Add segmentation / instrumentation #1329
- [x] announce feature publicly 

Out of scope: 
- [ ] Add ability to run all code cells sequentially

**Comment by lerongil** [comment]
Congrats team! This is officially done.
