### ISSUE TITLE
As a learner, I want the most robust and interactive course, so that I can stay engaged throughout my learning experience. 

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#254]
- [ ] amplitude demo
- [x] binary demo
- [x] add 1 example of a video integrated

**Comment by JRussellHuffman** [comment]
@korgan00 @vabarbosa Is the amplitude demo live and deployed? If so, this story can be closed.

**Comment by vabarbosa** [comment]
the amplitude components are all available and ready in various forms:

https://learn.qiskit.org/course/examples/widgets#widgets-2-0

i am just not aware of them currently being used in any specific chapter/page? 
CC: @korgan00 @frankharkins

**Comment by frankharkins** [comment]
The amplitude widgets are used here in the QML course [here](https://learn.qiskit.org/course/machine-learning/data-encoding) and I've added a PR to add them to the intro course too (https://github.com/Qiskit/platypus/pull/348)

**Comment by JRussellHuffman** [comment]
Any blockers on that pull request on the intro course? I think that's the last thing before closing this.

**Comment by vabarbosa** [comment]
[it has been merged](https://github.com/Qiskit/platypus/pull/348)

**Comment by JRussellHuffman** [comment]
Great. thank you! Closing.
