### ISSUE TITLE
As a independent learner, I want to share my learning accomplishment on Linkedin, so that I can qualify for future positions.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#255]
Acceptance criteria: 

- [ ] badge or certificate graphic
- [ ] notification of qualification / redemption 
- [ ] merit based off of multiple choice questions 
- [ ] redeemable via user accounts

**Comment by pandasa123** [comment]
We can use [Credly](https://www.credly.com/docs/issued_badges) as an issuer

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
