### ISSUE TITLE
integrate with Mathigon's authentication flow

### ISSUE THREAD

**Issue by korgan00** [Qiskit/platypus#257]
Enable login using Mathigon's authtentication flow

- [x] Connect with Mathigon on IBM login implementation
- [x] Upgrade to latest Mathigon Studio version
- [x] ~~Create IBMid~~ (already have a shared id)
- [x] Register SSO application
- [x] Configure oAuth credentials
- [x] Update & test login page

**Comment by Tansito** [comment]
Issue working on #174
