### ISSUE TITLE
Update video on login page

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#265]
- [x] Update video on the login page. We created a new video that is a little cleaner and includes QML showpieces 
- [x] make video take up entire bottom section

Note: @JRussellHuffman will have the new video

Design file [here](https://www.figma.com/file/SOnOgCGQIWx4oAlSFhIsIX/1972-User-account?node-id=1114%3A7615)

**Comment by vabarbosa** [comment]
resolved by #272
