### ISSUE TITLE
Privacy page - include statement

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#269]
Currently, the `/account#privacy` page does not include the Privacy statement -  this task is to include it.

![Screen Shot 2022-01-14 at 7 50 41 AM (2)](https://user-images.githubusercontent.com/6276074/149544941-e908eac5-c3ec-4cd2-be99-2c45166a8f3a.png)

Design file [here](https://www.figma.com/file/SOnOgCGQIWx4oAlSFhIsIX/1972-User-account?node-id=1114%3A7661)

Related: https://github.com/Qiskit/platypus/issues/264

**Comment by vabarbosa** [comment]
resolved by #310 

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/13156555/150544659-724f73c7-df5a-49dd-9577-05d377c0d876.png">
