### ISSUE TITLE
Hardware efficiency content update

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#278]
Below is a recommendation from a community member: 

> Hi,
> I’m reading very carefully the textbook, and so far I have one observation that maybe needs additional clarification. In Hardware efficiency describes... quick quiz, the question under A is “Whether a parametrized circuit can run on near-term quantum hardware or not”. By my opinion this needs to be reformulated, since every parametrized circuit can be run on near-term hardware, but the question is how efficiently.

**Comment by eddybrando** [comment]
@frankharkins can you help us confirm this is a bug? Or is this maybe rather an _improvement_ request?

**Comment by frankharkins** [comment]
Yeah maybe "how well the circuit will perform on near-term quantum hardware" is better.
