### ISSUE TITLE
Externalize notebooks in another repo

### ISSUE THREAD

**Issue by korgan00** [Qiskit/platypus#294]
Keep content and framework separated in different repositories so we can compile the notebooks once and reuse them.
The development build time will decrease and the framework could be reused.

**Comment by abdonrd** [comment]
As a little first step, I think we should move the `build:nb` script, outside the `build` script itself.

https://github.com/Qiskit/platypus/blob/095c69132d2f9a941669d3a3470844a2de1e7b6c/package.json#L14

So the build just build the framework, and another script build/get the content.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
