### ISSUE TITLE
QML course content feedback

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#303]
For the dataset representation in the computational basis, in the Amplitude encoding section, summation should goes from i=1 to NxM if the alpha amplitude should represent each feature in the dataset. The state |psi (x)> represent the feature(s) of one sample, while the dataset should represent the entire set of features and samples, which have dimension N x M. Actually, this is written in text below the summation, but summation goes from 1 to N, instead from 1 to N x M.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
