### ISSUE TITLE
Reduce Cypress testing times

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#306]
The Cypress tests are currently taking from the action "Run tests" are currently taking up to 25 minutes, as reported by @abdonrd and exemplified here: https://github.com/Qiskit/platypus/runs/4856233611?check_suite_focus=true#step:10:1

We should analyse why this is and try and reduce that time.

Long testing times cause a queue in the CI/CD pipeline that can be hurtful for the development experience and delivery frequency.

This issue might be related to https://github.com/Qiskit/platypus/issues/280, as pointed out by @Tansito.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
