### ISSUE TITLE
External link should open in new tab

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#351]
### Steps to reproduce the problem

1. Go to '[The QML course Introduction page ](https://learn.qiskit.org/course/machine-learning/introduction)'
2. In the right-side panel, click on 'qRAM > Read more'
3. (The same link can be found in the `qRAM` annotation, by hovering over the word

### What is the current behavior?

This link opens in the same tab.

### What is the expected behavior?

All other external links on the page open in a new tab, this should be treated similarly (if possible)

### Screenshots of where the Read more link can be found
![Screen Shot 2022-01-27 at 8 15 35 AM](https://user-images.githubusercontent.com/6276074/151398877-c4e1f960-49bc-455f-bad8-b26ebd5b9d92.png)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
