### ISSUE TITLE
Incorrect code comment on NEQR section

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#352]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-applications/flexible-representation-of-quantum-images-frqi#flexible-48-3
3. Scroll up to the prior code cell
4. See that the comment says `# Encode the third pixel whose value is (10101010):`, but the value encoded is `value11 = '11111111'`

### What is the current behavior?

Code runs fine, but the comment says the wrong value

### What is the expected behavior?

the comment should say `# Encode the third pixel whose value is (11111111):`

### Screenshots (optional but very helpful)
<img width="733" alt="Screen Shot 2022-01-27 at 10 18 52 AM" src="https://user-images.githubusercontent.com/7633881/151399307-a7505b64-8bfe-4c22-aa24-d129238d24da.png">

**Comment by Tansito** [comment]
Fixed with #690
