### ISSUE TITLE
Avoid deprecration messages from executable code widget

### ISSUE THREAD

**Issue by Tansito** [Qiskit/platypus#353]
### List of pages where you can find this kind of message:

- [Fourier transform](https://learn.qiskit.org/course/ch-algorithms/quantum-fourier-transform)
- [Exploring the jaynes cummings hamiltonian with qiskit pulse](https://learn.qiskit.org/course/quantum-hardware-pulses/exploring-the-jaynes-cummings-hamiltonian-with-qiskit-pulse)

### What is the current behaviour?

Inspect if it's possible to resolve the deprecations message.

**Comment by IceKhan13** [comment]
Same for [exploring-the-jaynes-cummings-hamiltonian-with-qiskit-pulse](https://learn.qiskit.org/course/quantum-hardware-pulses/exploring-the-jaynes-cummings-hamiltonian-with-qiskit-pulse) page.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
