### ISSUE TITLE
Rerun textbook regularly

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#355]
The coloring and sizing of the circuits throughout the textbook have been updated, but the update is only shown when each page of the textbook code is run by a user, or an updated version of each page is pushed to the textbook. 

Is it possible to update all pages of the textbook at once to show the new visuals, either via automation or manually running the textbook locally.

FYI @vabarbosa and @frankharkins

**Comment by frankharkins** [comment]
I'm hijacking this issue to make it more general. 

Ideally we run the textbook regularly to check the code still works too. Running the notebooks is too slow to be a PR check, so I think we need:
- [ ] A github action that runs the notebooks once a week / fortnight and makes issues for any errors / deprecation warnings
- [ ] A script (potentially also an action) that we trigger manually to update the notebook outputs, and makes a PR with these changes. We have a start [in the old textbook](https://github.com/qiskit-community/qiskit-textbook/blob/main/scripts/run_notebooks.py).

**Comment by vabarbosa** [comment]
in complete agreement with Frank here. a GitHub action is needed to regularly run the notebook to update the outputs, but also check for error, warnings, etc.
