### ISSUE TITLE
Many code cells are broken in Grovers 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#356]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-algorithms/grovers-algorithm#2qubits-simulation
2. Click on run on the code cells
3. Scroll down to each block and it will most likely provide an error

### What is the current behavior?

Some parts of the code blocks contain deprecated issues or have syntax errors 

### What is the expected behavior?

When running code cells, should see the output and not an error 

### Screenshots (optional but very helpful)

If applicable, please add screenshots or video captures to help explain the problem.

### Environment (optional but very helpful)
 - Device: [e.g. Laptop, iPhone 11, Smart Fridge]
 - OS: [e.g. Windows, iOS]
 - Browser: [e.g. Chrome, Safari]

### Additional context (optional)

Add any other context that could help debug the problem.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
