### ISSUE TITLE
Consider inline code styling

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#357]
This issue is more of a potential design opportunity, for improving readability for inline code. 

The opportunity here is to consider the same visual treatment for inline code
![Screen Shot 2022-01-27 at 8 24 09 AM](https://user-images.githubusercontent.com/6276074/151401990-a5d30f7a-0799-4381-9a08-1de7691f48da.png)

__
**On the Carbon website**
![Screen Shot 2022-01-27 at 8 24 01 AM](https://user-images.githubusercontent.com/6276074/151401610-ce06b436-305b-4cd1-bbbb-f65049d4c04b.png)

**Comment by JRussellHuffman** [comment]
From the conversation over in #391, but seems more appropriate here:
> Do we have designs for what code syntax highlighting should look like for the following two use cases:

We don't have anything written about regarding syntax highlighting or inline code snippets. Regarding inline code, I really like the carbon styling where there are tiny inline code cells throughout the text. I think that's perfect if we could render them in cool-gray-10.

Regarding syntax highlighting, I could switch to the carbon colors to override the defaults, but I don't think it's important enough to prioritize (personally). We have other bugs and enhancements that I would give priority.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
