### ISSUE TITLE
Add Lab 1 Quantum Circuits validation to grading service

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/platypus#359]
Related 
- https://github.com/Qiskit/platypus/issues/253
- https://github.com/Qiskit/platypus/issues/360

**Comment by lerongil** [comment]
Hey @Tansito @frankharkins  - Did the grader integration work get implemented into the [Lab 1 ](https://learn.qiskit.org/course/ch-labs/lab-1-quantum-circuits)?

**Comment by Tansito** [comment]
Is implemented but in the service only, we need to connect now the service and the front. I thought that that was being managed in the #360 but we can let this opened yeah.

**Comment by lerongil** [comment]
Add expected response and question in the grading service
