### ISSUE TITLE
As an educator, I want to be able to create a classroom so that I can invite my students in a shared space. 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#380]
## Background

Professors need a shared space to share a Syllabus, enrol / remove students, track student reading progress, track student MCQ + homework / exam scores

## Goal

> A Professors should be use a classroom administration dashboard to manage and track student performance over a course

## Acceptance Criteria: 

- [ ] Creation of roles (Backend)
   - professor, student
   - size: M 
- [ ] Creation of a cohort (Backend) 
   - relation to classes and students 
   - size: M
- [ ] Enrolling into a cohort (UI & Process) 
   - bulk registration by a professor 
   - self registration by a students
   - size: L
- [ ] *Class Visibility - Professor (Backend)**
   - relations between class and cohorts
   - remove students from a cohort 
   - size: M 
- [ ] *Class Visibility - Professor (UI)*
   - admin panel to add and remove classes to cohorts 
   - Size: L
- [ ] Student View (UI)
   - Navigation (Learning vs Cohort specific class page)
   - Completion of chapters from class visibility
   - Permissions based on cohort
   - Size: L
- [ ] Progress Tracking (Data / Backend)
   - Reading + Completion date: Mathigon
   - Questions + Completion date: Mathigon API
   - Number of attempts + date: new
   - Size: XL
- [ ] Progress Tracking (UI)
   - Create UI for tracking on admin 
   - Reading completion by student
   - Question completion by student
   - Table view, Graph view?
   - Filter by course
   - Size: XL
- [ ] *Country Control (Backend)*
   - Only applicable to cohorts owned by IBM Delivery Leads, Extend Cohort model for "require country"
   - List of countries + check logic
   - Extend Student Model
   - Size: L
- [ ] *Country Control (UI)*
   - If students want to join a cohort AND cohort requires a country limit, students must add their country 
   - UI for students to provide country
   - UI for professors to see the user country in panel
   - Admin panel to show blocked student by delivery lead
   - Size L

**Comment by pandasa123** [comment]
Phillip started a [PR to add Teacher Experience to Mathigon Studio](https://github.com/mathigon/studio/pull/141). He still needs to do a bit more refactoring, but this is a low-priority effort on his side — estimated 1 - 2 months

This does handle a few things that are important to Professors, including classroom enrolments, progress tracking dashboard, basic LMS API interface design. It does not cover [Syllabi](https://github.com/Qiskit/qiskit.org/issues/2442) or the LMSes that are more common at the university level, etc

**Comment by plegner** [comment]
We should be able to get migrate the Mathigon teacher/class code by March, which will add the following features:

* [x] Ability to sign up as a teacher or as a parent
* [x] Teacher accounts can create multiple classes to manage their students
* [x] Students can join classes using an 8-letter "class code" when signing up (or by adding it later on their student dashboard)
* [x] Parents and teachers have a new dashboard to track their students' progress
* [x] Teachers can import student rosters from Google Classroom. We will automatically create accounts for students that don't yet have one, email them, and add them to the teachers' class
* [x] Students aged <13 years can sign up for a "restricted account" with a guardian email. the guardian has to approve the account within 7 days, or it gets auto-deleted
* [x] Users can switch their account type on their account profile page

We don't yet support:

* [ ] Setting assignments
* [ ] Allowing teachers to curate "custom courses" (e.g. change the order of chapters/topics)
* [ ] Integration with other LMSs like Blackboard or Canvas

However, we are planning to release the entire @mathigon/studio repo under an MIT license soon, and would love your help in adding these features.

**Comment by pandasa123** [comment]
Something to note...**Tracking Progress**: Typically, profs don’t track individual students. He looks across a course, typically using exam distribution to identify engagement and comprehension issues. We might need to figure out how to aggregate progress later

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
