### ISSUE TITLE
[Code Cell Code] "Module Not Found Error" on code cells

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#389]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-gates/multiple-qubits-and-entangled-states
2. Run every code cell until the second one in the chapter 3.3
3. See the error message

### What is the current behavior?

After running the code cell, an error message appears.

### What is the expected behavior?

The code cell should run successfully.

### Screenshots (optional but very helpful)

![Screenshot 2021-11-18 at 17 30 41](https://user-images.githubusercontent.com/22047320/142456258-4178f877-8c90-4caa-9a94-5bf1c7e294df.png)

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: MacOS
 - Browser: Chrome

### Additional context (optional)

I ran all code cells before.

**Comment by techtolentino** [comment]
Following up since this has been inactive for some time.

I think that it's been resolved.

I ran every code cell on the page, and when I got the 2nd one in section 3.3, there was no error.


https://user-images.githubusercontent.com/6276074/181546345-c681febe-ef3f-44d6-816b-a598d85efcdd.mov
