### ISSUE TITLE
[Content Design] Update circuit design

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#393]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-algorithms/grovers-algorithm
2. Scroll to example 2 
3. See Circuit output 

### What is the current behavior?

The circuit output does not match the existing design specs for how we represent circuits. 

### What is the expected behavior?

It should follow the purple redesign. 

### Screenshots (optional but very helpful)

<img width="375" alt="Screen Shot 2021-11-18 at 8 25 19 AM" src="https://user-images.githubusercontent.com/9096989/142455305-8f12b6fa-aab4-45c8-9a87-f8faa4997861.png">

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
