### ISSUE TITLE
[Navigation UX] Contents table anchor links offset leave headlines out of the viewport

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#396]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-gates/multiple-qubits-and-entangled-states
2. Click on any link in the **Contents** section
3. See how the new window position is passed the headline

Alternative:
1. Go to a page with an anchor link like https://learn.qiskit.org/course/ch-gates/multiple-qubits-and-entangled-states#single-qubit-gates
2. See how the new window position is passed the headline

### What is the current behavior?

The position is passed the headline.

### What is the expected behavior?

The headline should be included in the viewport.

### Screenshots (optional but very helpful)

https://user-images.githubusercontent.com/22047320/142454503-63572e96-218f-48b9-8cb5-d7c8c497d73d.mov

### Environment (optional but very helpful)
 - Device: MacBook Pro
 - OS: MacOS
 - Browser: Chrome

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
