### ISSUE TITLE
"Name Error" in code cell

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#397]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-demos/level-5-proving-the-uniqueness-of-quantum-variables
2. Run the first code cell
3. See error

### What is the current behavior?
The code throws an error "name 'hello_quantum' is not defined"

### What is the expected behavior?

I assume the first code cell on a page should always run. Further down the page, there may be dependencies on prior code cells, but the first cell should run correctly.

### Screenshots (optional but very helpful)

<img width="743" alt="Screen Shot 2021-11-18 at 10 18 32 AM" src="https://user-images.githubusercontent.com/7633881/142454398-58dd246d-0775-43ed-9f69-90abef0ae750.png">

### Environment (optional but very helpful)
 - Device: macbook pro
 - OS: osx
 - Browser: firefox

issue is probably on all environments

### Additional context (optional)

Add any other context that could help debug the problem.

**Comment by bopardikarsoham** [comment]
This is because the hello_quantum module has not been imported from qiskit_textbook.games

![image](https://user-images.githubusercontent.com/77266161/165014766-bd45c616-6754-4ed2-9e88-a2a8f9fb6a1b.png)

Simply by adding `from qiskit_textbook.games import hello_quantum` fixes the issue

**Comment by bopardikarsoham** [comment]
But, I also found out that in https://github.com/Qiskit/platypus/blob/main/notebooks/ch-ex/hello-qiskit.ipynb all the levels have been merged into one jupyter notebook. But, if we look at the textbook  https://learn.qiskit.org/course/ch-demos/level-5-proving-the-uniqueness-of-quantum-variables Level 5 is created like a separate chapter. Why are they different?
