### ISSUE TITLE
No annotated equations on grovers page

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#399]
This is not so much a bug but mostly an enhancement request. On this page: https://learn.qiskit.org/course/ch-algorithms/grovers-algorithm, all equations do not have any annotations. I believe they would be very useful on this page.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
