### ISSUE TITLE
[General UI] Content breakpoint on mobile

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#400]
### Steps to reproduce the problem

1. Go to 'https://learn.qiskit.org/course/ch-algorithms/simons-algorithm', although it seems to happen on all pages
2. Click on the hide details/show detials toggle

### What is the current behavior?

The main content changes widths the opposite as expected. When the panel isn't visible, the content takes up half the screen. When the panel is visible, it takes up the full width (and therefore is covered by the panel)

### What is the expected behavior?

The main content should never be covered by the side panel, and should be proportional to the amount of screen real-estate available.

### Screenshots (optional but very helpful)

If applicable, please add screenshots or video captures to help explain the problem.

https://user-images.githubusercontent.com/7633881/142453454-44bee79b-fcb9-4243-814b-ae12f211167b.mov

### Environment (optional but very helpful)
 - Device: tested on Firefox on macos, simulating ipad

### Additional context (optional)

Add any other context that could help debug the problem.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
