### ISSUE TITLE
[General UI] Misaligned top banner in Textbook on tablet

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#401]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-gates/introduction on a tablet device
2. Look at the top purple panel and its alignment

### What is the current behavior?

The panel appears to be "misaligned". To the right, it overlaps the sidebar.

### What is the expected behavior?

The panel should look aligned to the general layout of the page.

### Screenshots (optional but very helpful)

![image](https://user-images.githubusercontent.com/22047320/142453091-5098b305-4d9e-45e6-82a3-bb730f1952ee.png)

### Environment (optional but very helpful)
 - Device: Simulated iPad on MacBook via Chrome
 - OS: MacOS
 - Browser: Chrome

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
