### ISSUE TITLE
[General UX] Mobile show index menu disappears when scrolling

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit/platypus#409]
### Steps to reproduce the problem

1. Open https://learn.qiskit.org/course/ch-applications/hybrid-quantum-classical-neural-networks-with-pytorch-and-qiskit on mobile with chrome browser
2. Click on `Show index`
3. Scroll down down and up couple of times
4. See that show index dissapear 

### What is the current behavior?

Show index menu disappear if you scroll content underneath

### What is the expected behavior?

Menu should stay in place

### Screenshots (optional but very helpful)

https://user-images.githubusercontent.com/8796709/140353997-85593c08-595e-426f-976a-d4fe8002c9d6.MP4

### Environment (optional but very helpful)
 - Device: iPhone X
 - OS: iOS
 - Browser: Chrome

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
