### ISSUE TITLE
[General UI] Textbook annotation term styling

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#413]
### Steps to reproduce the problem

1. Go to 'https://learn.qiskit.org/course/quantum-hardware/measuring-quantum-volume'
2. Tab until you reach an annotation term (e.g. `transpiler`
4. Notice the `focus` styles aren't part of the design spec

### What is the current behavior?

An orange border appears

### What is the expected behavior?

The border should be the same [magenta value](https://github.com/Qiskit/platypus/blob/f5cc8f8618dfc7ccdd561b516242deeb55af5d8e/frontend/scss/variables/colors.scss#L72) as the top tooltip, per [this comment](https://github.com/Qiskit/platypus/issues/413#issuecomment-1040894132)

### Screenshots (optional but very helpful)

<img width="899" alt="Screen Shot 2021-11-04 at 8 09 42 AM" src="https://user-images.githubusercontent.com/6276074/140347294-4f75c0bd-448c-4d0e-8203-656e390902ef.png">

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: OSx
 - Browser: Chrome

(Designs for the `Annotations` can be found [here](https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=149%3A37))

**Comment by JRussellHuffman** [comment]
Does "focus" specifically refer to when a user tabs to the element, or does that also include "hover"?

**Comment by techtolentino** [comment]
@JRussellHuffman - this is specifically happening when the element is tabbed to, _not_ hover.

**Comment by JRussellHuffman** [comment]
Okay, good to know. In that case, I agree with Eddy that a border will be beneficial for accessibility, and it seems to be the standard. Can the boarder be the same color pink as used at the top tooltip? That seems like the best/most consistent way to do it.
