### ISSUE TITLE
[General UI] Arrows disappear for small screens

### ISSUE THREAD

**Issue by Tansito** [Qiskit/platypus#415]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/introduction/what-is-quantum
2. Reduce the size of the screen to something small

### What is the current behavior?

The arrows that should be at both sides of the circles disappear for small screens but they are remain clickable.

### What is the expected behavior?

The arrows should be there.

### Screenshots (optional but very helpful)

<img width="400" alt="Screenshot 2021-11-04 at 16 14 08" src="https://user-images.githubusercontent.com/9059044/140345125-178df1d8-10a8-4e9d-b7ab-a32af0525eec.png">

### Environment (optional but very helpful)
 - Browser: Chrome

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
