### ISSUE TITLE
[Code Cell Code] NameError when running code cells on platypus

### ISSUE THREAD

**Issue by y4izus** [Qiskit/platypus#420]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/quantum-hardware/introduction-to-quantum-error-correction-via-the-repetition-code
2. Click on Run on the code cell number 39
3. See error: NameError: name 'logical_prob_match' is not defined

### What is the current behavior?

We gets an NameError error

### What is the expected behavior?

We should not have an error here

### Screenshots (optional but very helpful)

<img width="785" alt="Captura de pantalla 2021-10-25 a las 15 36 11" src="https://user-images.githubusercontent.com/17231966/138705626-be831b59-153e-4447-9ccb-7af517b667a5.png">

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: MacOS
 - Browser: Chrome

**Comment by memolina2323** [comment]
it relies on quantum hardware and should be updated once #1196 is completed.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
