### ISSUE TITLE
[Code Cell Code] FileNotFoundError when running code cells on platypus

### ISSUE THREAD

**Issue by y4izus** [Qiskit/platypus#421]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/quantum-hardware/introduction-to-quantum-error-correction-via-the-repetition-code
2. Click on Run on the code cell number 38
3. See error: FileNotFoundError: [Errno 2] No such file or directory: 'results/logical_prob_match_ibmq_16_melbourne.txt'

### What is the current behavior?

We gets an FileNotFoundError error

### What is the expected behavior?

We should not have an error here

### Screenshots (optional but very helpful)

<img width="1008" alt="Captura de pantalla 2021-10-25 a las 15 30 47" src="https://user-images.githubusercontent.com/17231966/138704741-b0d1bc90-324c-4d98-b25e-f6b8d36ed688.png">

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: MacOS
 - Browser: Chrome

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
