### ISSUE TITLE
[General UI] Content width on changing size

### ISSUE THREAD

**Issue by korgan00** [Qiskit/platypus#423]
### Steps to reproduce the problem

1. Configure the browser with 1440width (large config)
2. Go to any textbook course
3. Change the width to 768 (vertical tablet)
4. Open and close the "show details"

### What is the current behavior?

The content width is wider when the panel is open.

### What is the expected behavior?

The content width should be wider when the panel is close.

### Aditional context

It get fixed on reload.

### Screenshots (optional but very helpful)

https://user-images.githubusercontent.com/4138279/138491019-d7c589f2-5ec0-4dc3-a53d-fc9facd6b113.mov

**Comment by eddybrando** [comment]
Fixed with @korgan00's layout redesign.
