### ISSUE TITLE
[General UI] "Read time" overlaps menu on mobile

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#424]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-applications/solving-linear-systems-of-equations-using-hhl-and-its-qiskit-implementation (on all pages)
2. error is visible at the top of the page

### What is the current behavior?

The component that specifies the read time at the top left of the page overlaps with the menu directly above it

### What is the expected behavior?

The read time component should be situated below the menu.

### Screenshots (optional but very helpful)

![Screenshot_20211021-101402_Brave](https://user-images.githubusercontent.com/7633881/138309480-c32f24e2-484e-4a92-b8a9-d8bc1701320f.jpg)

### Environment (optional but very helpful)
 - Device: mobile (galaxy z fold 3, closed)
 - OS: android
 - Browser: brave, chrome

### Additional context (optional)
This might just be fore skinny screens, or just android. I couldn't duplicate on a simulated iphone, but I could simulate of simulate android.

Add any other context that could help debug the problem.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
