### ISSUE TITLE
[Code Cell UI] Missing a visual success indicator after Run cta

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#425]
### Steps to reproduce the problem

1. Go to 'https://learn.qiskit.org/course/ch-labs/lab-1-quantum-circuits'
2. Click on 'Run'
3. Wait for some confirmation, action, change, update
4. See nothing

### What is the current behavior?

As a user, I expect there to be some sort of visual cue or an indication that what I just _ran_, worked

### What is the expected behavior?

"Success", check mark, some sort of positive indicator

### Screenshots (optional but very helpful)

![Screen Shot 2021-10-21 at 8 09 41 AM](https://user-images.githubusercontent.com/6276074/138309976-e36d8d7c-b2cc-4e49-ab11-2fef38e74c8e.png)

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: macOs Big Sur
 - Browser: Chrome

**Comment by eddybrando** [comment]
@JRussellHuffman do we have a design spec for this already? Otherwise I'd consider this a "feature" and not a "bug".

**Comment by JRussellHuffman** [comment]
As far as I can tell, this isn't technically a bug, but a content issue that should be addressed. There are some cells that don't return anything below the cell. For example, the first cell could be clarified by adding `print("imports successful")`, but currently the imports happen (successfully) and no feedback is given to the user. 

I don't think all cells should return a value, but I see Randy's point that right now it's kind of unclear. What do you think @frankharkins 

When the auto-grader gets implemented, the design should be implemented to give users feedback on if they are correct or incorrect: https://www.figma.com/file/Kj9I5oa8rddh0C0LSrkeAw/2031-grader-integration?node-id=501%3A521

**Comment by vabarbosa** [comment]
just to revisit this issue. the [autograder is implemented](https://learn.qiskit.org/course/examples/grader) and when grading you do get a message indicating your submission was correct incorrect. however, just running (not grading) would still only show a response if the code has some call that prints/returns some response.

i agree cells should not be required to return a value, but yes, some feedback would be nice.

for what it is worth quantum lab/jupyter displays an execution number besides the cell after it completes regardless of correct/incorrect or there is a return or not:



![Image](https://user-images.githubusercontent.com/13156555/183761178-a5f72637-4ac3-4ddc-a02b-bced0dd3c913.png)



![Image](https://user-images.githubusercontent.com/13156555/183761276-7df522ef-4be1-446d-af1d-2466a7efc0a7.png)


i am no designer 😬 but what about using the gutter for some kind of status icon (e.g., `not yet ran`, `running`, `finished run`). something like this but with more of that Russell or Grace flare (and better choice of icon)


https://user-images.githubusercontent.com/13156555/183767666-f720ea5c-068a-4dc0-8d3f-07a8b614d4e3.mov


all that to say, yeah this is more of an enhancement/feature request than a bug!

**Comment by frankharkins** [comment]
I agree with Va, I think adding print statements is more of a workaround, e.g. the user could easily modify a cell so that it produces no output. Also agree indicating `not yet ran`, `running`, `finished run` should be more than sufficient.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
