### ISSUE TITLE
[Links] Links direct to content in original textbook instead of textbook-beta

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/platypus#426]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-algorithms/quantum-circuits
1. Scroll down to introduction section: `1. Introduction`
1. Click on some of the links on the page

### What is the current behavior?

some of the links redirect to pages in the original textbook. for example (in the first paragraph):

- [single-quibit](https://qiskit.org/textbook/ch-states/single-qubit-gates.html)
- [multi-qubit](https://qiskit.org/textbook/ch-gates/introduction.html)

### What is the expected behavior?

if content is available in textbook-beta the links should direct to the textbook-beta page. for example:

- https://learn.qiskit.org/course/ch-states/single-qubit-gates
- https://learn.qiskit.org/course/ch-gates/multiple-qubits-and-entangled-states

### Environment (optional but very helpful)

- Device: MacBook Pro
- OS: OS X
- Browser: Firefox 92.0

**Comment by techtolentino** [comment]
I just checked all the links on this page, and the issue looks to have been addressed... please see below.



https://user-images.githubusercontent.com/6276074/182425333-4641b774-fb63-4798-ac3e-3f58939ef9c1.mov
