### ISSUE TITLE
[Code Cell Code] "Deprecation Warning" in code cells

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#429]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-states/the-atoms-of-computation (also happening in other pages)
2. Click on "Run" on every code cell until cell number 8
3. See the warning on the result of cell number 8

### What is the current behavior?

A warning is shown.

### What is the expected behavior?

No warning should be shown.

### Screenshots (optional but very helpful)

![Screenshot 2021-10-21 at 17 17 06](https://user-images.githubusercontent.com/22047320/138308755-16febf3a-5bf6-4198-88d1-629eedce21a4.png)

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: MacOS
 - Browser Chrome

### Additional context (optional)

This issue occurs many times in various pages.

**Comment by pandasa123** [comment]
Could we use @1ucian0's [proposal](https://github.com/Qiskit/qiskit.org/discussions/2670) to catch these issues in our CI / CD pipeline?

**Comment by techtolentino** [comment]
Just checked this bug to see if it's still an issue, and it seems to have been resolved.
Please [recheck the page](https://learn.qiskit.org/course/ch-states/the-atoms-of-computation) itself, and also review the screengrab below 

https://user-images.githubusercontent.com/6276074/182423956-6dafddfc-b132-499a-a552-eec3919281f4.mov
