### ISSUE TITLE
[Code UI] Qiskit Textbook Formulas Overlapping

### ISSUE THREAD

**Issue by sderakhshandeh** [Qiskit/platypus#431]
When reviewing the Qiskit textbook on Safari formulas show as overlapping. This is only an issue when using Safari, other browsers look fine. 
<img width="548" alt="Screen Shot 2021-10-20 at 9 38 51 AM" src="https://user-images.githubusercontent.com/92757140/138135063-4755c381-dbfc-4f5e-9baa-098d6b6d5c29.png">

**Comment by eddybrando** [comment]
Duplicate of https://github.com/Qiskit/platypus/issues/709
