### ISSUE TITLE
Migrate 2020 Summer School to learn.qiskit.org

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#444]
For 2021, we created a new format for viewing and learning summer schools. This is located here: learn.qiskit.org. We should consider moving the [previous year's summer school](https://qiskit.org/learn/intro-qc-qh/) to this new format. This could be a nice good first issue for someone to learn about our educational material, qiskit.org, and learn.qiskit.org.

**Comment by MarcoBarroca** [comment]
Someone should close this issue. The 2020 Summer School page seems to be migrated already.

**Comment by pandasa123** [comment]
Available on the [new Learn page](https://qiskit.org/learn/)
