### ISSUE TITLE
Add CTA Property to `CTA clicked` event for next page element in textbook

### ISSUE THREAD

**Issue by agebbie** [Qiskit/platypus#446]
Related to [issue 2139]( https://github.com/Qiskit/qiskit.org/issues/2139)

Hello! Separating out from the ticket above ^^

Looking to add in the `CTA` property to the `CTA clicked` event type for the page buttons at the bottom of the page in the intro course of the textbook (https://learn.qiskit.org/course/introduction/describing-quantum-computers#describing-2-4)

Currently the event type is instrumented but there is no way to distinguish for this specific button, need this to track a user flow for engaged users following the designated user path.

Images below!

![Screen Shot 2021-09-23 at 3 14 16 PM](https://user-images.githubusercontent.com/66438533/134569797-3932864a-332c-413e-8a71-33962eb17bfc.png)

![Screen Shot 2021-09-23 at 3 14 29 PM](https://user-images.githubusercontent.com/66438533/134569809-9675b8ba-f8d8-49e4-8939-0f1eb353de7f.png)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
