### ISSUE TITLE
Text overlapping on math equations

### ISSUE THREAD

**Issue by gracelindsell** [Qiskit/platypus#447]
### Steps to reproduce the problem
https://learn.qiskit.org/course/ch-states/the-case-for-quantum-computers
If you open this page in safari, you can see the text overlaps on the equations specifically

### What is the current behavior?
<img width="1020" alt="Screen Shot 2021-09-22 at 3 40 34 PM" src="https://user-images.githubusercontent.com/89415444/134411479-c0744ae1-5a04-407d-a948-14c49455573e.png">

### What is the expected behavior?
Text equations should not overlap

**Comment by micpap25** [comment]
Looks like this is fixed on Google Chrome, can someone confirm for Safari?
<img width="547" alt="image" src="https://user-images.githubusercontent.com/34077605/214198192-e38e417e-8b47-453d-a0f6-58130e8021d8.png">

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
