### ISSUE TITLE
Add Textbook Beta Footer

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#464]
We need a proper `Footer`

**Comment by pandasa123** [comment]
I think this'll be closed soon, with [this PR](https://github.com/Qiskit/web-components/issues/77)?

**Comment by techtolentino** [comment]
Removing the label since this is being worked on

**Comment by pandasa123** [comment]
[Footer is implemented](https://github.com/Qiskit/web-components/issues/77), closing out!

**Comment by JRussellHuffman** [comment]
What pages is it implemented on? I don't see it on the content pages under learn.qiskit.org. I tried hard refereshes and I tried in Chrome and Firefox.
