### ISSUE TITLE
[Code Cell UI] Success text should be on one line

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#465]
### Steps to reproduce the problem
Successfully complete a drag and drop code exercise

### What is the current behavior?
The "that's correct" text is broken into two lines (screenshot below)
<img width="192" alt="Screen Shot 2021-08-19 at 10 08 40 AM" src="https://user-images.githubusercontent.com/7633881/130093647-a0ea3b2a-a52e-40aa-8923-925784659020.png">

### What is the expected behavior?
The text should be on one line (see screenshot). Correct version is in the design file: https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=130%3A0
<img width="228" alt="Screen Shot 2021-08-19 at 10 10 03 AM" src="https://user-images.githubusercontent.com/7633881/130093755-6d2c230d-1c2a-45ae-82d4-c249577c1d23.png">

**Comment by micpap25** [comment]
I cannot seem to find a drag and drop code exercise. The only drag-and-drop I can find is the widgets examples page which is all sandboxes.

**Comment by vabarbosa** [comment]
@micpap25 thank you for your interest. you can find some coding exercises here:

- https://learn.qiskit.org/course/introduction/the-atoms-of-computation#the-15-176
- https://learn.qiskit.org/course/quantum-hardware/measuring-quantum-volume#measuring-21-0

and you can reproduce the issue when trying coding exercise in `The atoms of computation` section

<img width="800" alt="image" src="https://user-images.githubusercontent.com/13156555/213030125-3d7efdd8-a931-4b00-8717-e90c9eefa20e.png">

let me know if you have any questions. and thanks again for your interest!

**Comment by micpap25** [comment]
Relevant files are `DragAndDropCode.vue` and `SolutionStateIndicator.vue`, looking into them now

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
