### ISSUE TITLE
[Content UI] Long math text goes beyond text container

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#466]
### Steps to reproduce the problem
Example page: https://learn.qiskit.org/course/ch-algorithms/quantum-fourier-transform

### What is the current behavior?
Math text goes beyond the text container and overlaps with the right side panel (see screenshot)

### What is the expected behavior?
Math should not go beyond container

<img width="513" alt="Screen Shot 2021-08-16 at 8 45 05 AM" src="https://user-images.githubusercontent.com/7633881/129585247-090a6f12-412a-4f10-8153-544a3ff9f38a.png">

**Comment by eddybrando** [comment]
Fixed with @korgan00's layout redesign.
