### ISSUE TITLE
Platypus: Sidebar list structured incorrectly

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#471]
According to an Axe a11y audit performed on `/course/ch-prerequisites/environment-setup-guide-to-work-with-qiskit-textbook`, the sidebar chapter's list is structured incorrectly.

---

https://dequeuniversity.com/rules/axe/4.3/list?application=axeAPI

---

**User impact:** Serious
**Disabilities affected:** Blind, Deafblind
**Requirement(s):** WCAG 2.0 (A): MUST
**WCAG Success Criteria:** 1.3.1 Info and Relationships

**Comment by micpap25** [comment]
Hi, everything here looks correct but let me know if it does need to be restructured... I am glad to look into this alongside other sidebar issues. Thank you.
<img width="373" alt="image" src="https://user-images.githubusercontent.com/34077605/212340499-6bcf1b97-8cc6-40a7-9934-4c506cbd9c1d.png">

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
