### ISSUE TITLE
Create Amplitude demo

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#480]
Designs provided [here](https://www.figma.com/file/xh0oqTfxDeCMsMmoBAYHWW/Qiskit-components?node-id=1429%3A3213)

- implement cycles
- implement calculations

**Comment by pandasa123** [comment]
Can this one be closed, given the widgets in the [Introduction course](https://learn.qiskit.org/course/introduction/what-is-quantum)?

**Comment by lerongil** [comment]
I believe so. @JRussellHuffman can help confirm but this is no longer in scope currently.

**Comment by JRussellHuffman** [comment]
yep, this is done.
