### ISSUE TITLE
As a learner, I want the code of the textbook to be Python and Qiskit idiomatic, so I learn the most effective, modern and supported way of coding with Qiskit

### ISSUE THREAD

**Issue by delapuente** [Qiskit/platypus#484]
- [ ] Qiskit code should be Qiskit idiomatic.
- [ ] Qiskit code should follow Qiskit best practices.
- [ ] Python code should be Python idiomatic.

**Comment by lerongil** [comment]
@1ucian0 @delapuente can you help provide a bit more context here?

**Comment by 1ucian0** [comment]
I think this is about the content in the textbook. Probably, specific instances of of those tasks can be 
 issues in https://github.com/qiskit-community/qiskit-textbook/ 
 
As it phrase, it is not actionable to me.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
