### ISSUE TITLE
Add CNOT to mini-composer widget

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#512]
mini-composer finalized with CNOT 

---
Related: Qiskit/platypus#556, Qiskit/platypus#554, Qiskit/platypus#539, (and https://github.com/qiskit-community/platypus/pull/51)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
