### ISSUE TITLE
[Navigation UX] Clicking on a subsection jumps to that section (as expected) but link is not shown active

### ISSUE THREAD

**Issue by y4izus** [Qiskit/platypus#514]
### Steps to reproduce the problem
Go to a https://learn.qiskit.org/ content page and click on a subsection

### What is the current behavior?
When clicking on the subsection, the page jumps to that section but the link is not shown active. If we scroll to see the title, we get the link active:

https://user-images.githubusercontent.com/17231966/125453972-5d1205b3-2a29-436b-a47a-b137ef4aa631.mov

### What is the expected behavior?
The link should be shown active when we jump to it

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
