### ISSUE TITLE
Section doesn't have the correct format and shows the md structure on the index

### ISSUE THREAD

**Issue by y4izus** [Qiskit/platypus#516]
### Where is the problem?
https://learn.qiskit.org/course/ch-demos/estimating-pi-pi-using-quantum-phase-estimation-algorithm

### What is the problem?
First section doesn't have the correct format and shows the md structure on the index (left side panel):
<img width="427" alt="Captura de pantalla 2021-07-13 a las 14 38 01" src="https://user-images.githubusercontent.com/17231966/125453070-c9d4b61f-1424-4c45-9fa8-592519d0d159.png">
<img width="243" alt="Captura de pantalla 2021-07-13 a las 14 37 36" src="https://user-images.githubusercontent.com/17231966/125453079-bb1a1f61-4814-4b54-86a9-92cedd5c83da.png">

### What would you expect?
Correct format

**Comment by micpap25** [comment]
I am looking into this as a first issue.
