### ISSUE TITLE
Pi symbol in title not rendered as properly ($pi$)

### ISSUE THREAD

**Issue by y4izus** [Qiskit/platypus#517]
### Where is the problem?
https://learn.qiskit.org/course/ch-demos/estimating-pi-pi-using-quantum-phase-estimation-algorithm

### What is the problem?
Pi symbol in title not rendered as properly:
<img width="547" alt="Captura de pantalla 2021-07-13 a las 14 32 13" src="https://user-images.githubusercontent.com/17231966/125452362-59464e70-b88b-4877-8cf3-0fb8d9a58dcb.png">
<img width="241" alt="Captura de pantalla 2021-07-13 a las 14 32 55" src="https://user-images.githubusercontent.com/17231966/125452369-03fab5e7-11ee-4daa-9440-fe5e51125dab.png">

### What would you expect?
Pi symbol render properly

**Comment by divshacker** [comment]
There is no problem in a notebook because github is rendering pi clearly, but in the website it is not.

**Comment by micpap25** [comment]
I am looking into this right now as a first issue and will try to get a fix going.
