### ISSUE TITLE
Equations extend beyond column width in smaller browser windows

### ISSUE THREAD

**Issue by y4izus** [Qiskit/platypus#518]
### Where is the problem?
https://learn.qiskit.org/course/ch-algorithms/quantum-fourier-transform

### What is the problem?
Equations extend beyond column width in smaller browser windows. Example:
<img width="813" alt="Captura de pantalla 2021-07-13 a las 14 30 02" src="https://user-images.githubusercontent.com/17231966/125451824-771f4873-6bc8-40b7-bb84-0835e6b60d39.png">

### What would you expect?
Content fits the screen size

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
