### ISSUE TITLE
[General UI] learn.qiskit.org does not get the correct layout until refreshing

### ISSUE THREAD

**Issue by delapuente** [Qiskit/platypus#523]
### Steps to reproduce the problem

1. Start an incognito/private browsing session on a desktop browser with a window width greater than 1100px.
2. Visit https://learn.qiskit.org/course/introduction/why-quantum-computing
3. Decrease width until reaching the 600px

### What is the current behavior?

The left sidebar changes to the mobile design but the right one remains the same.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/757942/125167112-e9ca5100-e16c-11eb-9cee-07b844c50277.png">

### What is the expected behavior?

Both sidebars change to the mobile design. You can achieve this result by refreshing.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/757942/125167126-f6e74000-e16c-11eb-8352-277a502d6bc9.png">

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
