### ISSUE TITLE
[General UI] Textbook Beta's layout changes after resizing

### ISSUE THREAD

**Issue by delapuente** [Qiskit/platypus#524]
### Steps to reproduce the problem

1. Start an incognito/private browsing session on a desktop browser with a window width greater than 1100px.
2. Visit https://learn.qiskit.org/course/introduction/why-quantum-computing
3. Decrease width until triggering the collapse of the left side panel.
4. Increase width until coming back to the original size.

### What is the current behavior?

The left side panel remains collapsed.

### What is the expected behavior?

The left side panel is restored to its original layout.

**Comment by eddybrando** [comment]
Fixed with @korgan00's layout redesign.
