### ISSUE TITLE
Fix header to the  top of the page

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#662]
When the user scrolls, the header stays fixed to the top of the browser window so that the menu options are still accessible even when the user has scrolled down the page.

**Comment by pandasa123** [comment]
@JRussellHuffman, I believe this can be closed out?

https://user-images.githubusercontent.com/6241840/181937026-53b4be69-6bf6-4c95-8607-8de3203d2c69.mov

**Comment by JRussellHuffman** [comment]
If we close it, can we reopen one specifically for the qiskit.org pages? Looks like it works fine for the textbook.

**Comment by pandasa123** [comment]
[Opened](https://github.com/Qiskit/qiskit.org/issues/2724)
