### ISSUE TITLE
As a Professor, I want to integrate Problem Sets into my Syllabus, so I can test students after they learn concepts 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#667]
## Background

Homeworks, Practice Exams, and Projects are important ways to test student comprehension. With the [Assessment Experience](https://github.com/Qiskit/platypus/issues/1079) and [Problem Set Bank](https://github.com/Qiskit/platypus/issues/1259), professors should be able to add Problem Sets into their Syllabus

Related:

- [Problem Sets Bank](https://github.com/Qiskit/platypus/issues/1259)
- [Problem Set Bank collection](https://github.com/Qiskit/platypus/issues/1260)
- [Integrations into Syllabus](https://github.com/Qiskit/platypus/issues/667)

## MVP Goal

> Professor should be able to select canned Problem Sets on a Syllabus

## Acceptance Criteria

- [ ] Syllabus dropdown to switch between Chapters, Tutorials, and Problem Sets
- [ ] Professor should be able to add Problem Set to a section with a checkbox

**Comment by pandasa123** [comment]
Some notes:

- “It’s expected that students will be destroyed on the first exam. It’s up to students to realise they messed up and correct themselves.“. 
- Using Problem Sets as for Practice Exams, possibly with the Autograder being immensely valuable for students

**Comment by pandasa123** [comment]
As we ship out a Practice Exam and Problem Sets, we should figure out how to grade probability distributions. This is based on a few professor interviews

> Having a grade for the problems is a bit hard since compiled circuits and numerical evaluation is tricky. If I had to think about the core idea when we think about learning algorithms, it's all about probability distributions — that's an easy to thing to score

**Comment by pandasa123** [comment]
Here are some [WIP Practice Exam](https://ibm.ent.box.com/notes/922188302444) questions

**Comment by pandasa123** [comment]
If I had to think about what the basics for having a practical exam:

- Server-side MCQ validation to prevent cheating 
- Exam-wide grading (not just individual problems)
- #255 

And this is just a barebones, before we think about how the exam experience should be:

How can we rotate questions with a test bank? 
How should questions be presented? One page, multiple pages, sections?

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
