### ISSUE TITLE
As a non-native english speaker, I want to read the Qiskit textbook in my language so that I can comprehend the material without using a translator. 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#668]
Acceptance Criteria: 

- [ ] Decide the first language to translate 
- [ ] Translate the first 2 lessons in the introduction to quantum computing course 
- [ ] Add language toggle button for new language

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
