### ISSUE TITLE
As a Professor, I want to grant hardware access to students in my classroom, so that they can experiment with real systems.

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#673]
## Background

Professors care deeply about students experimenting with hardware. Although these students can get access via the open provider, this usually results long queue times. Currently, we have the Educators Program but there's a disconnected experience between syllabus creation and hardware access

## Goal

Professors should be able to add enrolled students into a classroom provider

## Acceptance Criteria

- [ ] Professors should be able to click a button to the [Educator's Program](https://quantum-computing.ibm.com/programs/educators) access on a syllabus page

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
