### ISSUE TITLE
As an IBM Client Educator, I want to upload gated content, so that I can share commercial learning material with Clients

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#674]
## Background

IBM Quantum has a number of teams who are creating commercial learning material for clients. This learning material is not open sourced and must be only be accessible to Clients

## Goal

Client Educators should be able to upload custom, private learning material and create a syllabi only accessible to Client learners

## Acceptance Criteria:

- [ ] IBM Client Educators should be able to upload custom learning material, in Jupyter Notebooks format
- [ ] All IBM Client Educator content should be inaccessible by default
- [ ] Only IBM Client Educators should be able to add this content to syllabi

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
