### ISSUE TITLE
User Account Onboarding Demographic Questions

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#675]
As per our Design Research team, here's what we could collect when users create a new account:

- [ ] **What is your name?**

- [ ] **What is your email address?**

- [ ] **Which of the following options best represents the type of organization you are affiliated with?** [Single answer question]

- Startup
- Academic institution
- Enterprise organization
- Government
- Other (Please specify _____)

- [ ] **How long have you been in the field of quantum computing?** [Single answer question]

- Less than 1 year
- 1 to 3 years
- 4 to 6 years
- More than 6 years

- [ ] **Which of the following statements describe your role? (Check all that apply.)** [Multiple choice question]

- A researcher who is within a quantum computing provider (e.g. IBM), research lab, academic institution or start up focused on using a variety of techniques to build quantum technology (e.g. optimizers, algorithms, or  hardware). 
- A developer who is responsible for designing, developing, and testing software that is code compliant with quality and security protocols.
- An educator who is working to develop the next generation of quantum professionals.
- A hobbyist who is interested in quantum computing but has no work responsibilities tied to it.
- A business leader who is interested in safeguarding company vision, making new product discoveries and/or tackling high impact problems that are not easily solvable with classical computing.
- An innovation leader who is interested in early exploration into the promise of quantum computing
- Other (Please specify ______)

- [ ] **What quantum computing related topics are you interested in learning about?** [Multiple choice question]

- Quantum Machine Learning
- Quantum Hardware
- Etc etc
- Other (Please specify ______)

---

[We should add the "from all users" items as part of this onboarding as well](https://github.com/Qiskit/platypus/issues/261#issuecomment-1012604544)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
