### ISSUE TITLE
BasicLink component "href" issue with some Vue versions

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#677]
The `BasicLink` component currently has several issues in this project. We can use inspiration from Qiskit-vue components, or the Qiskit org project, to resolve the problems.

**Comment by techtolentino** [comment]
We added this issue after @korgan00 mentioned that the component was broken across the project – he'll have more details 🤞

**Comment by korgan00** [comment]
vue 3 does not accept the `:href="isAnchor && url"` notation (`&&`)
In the qiskit-vue repo we have an implementation that works with nuxt 2, vue 2 and vue 3. If we take that implementation, it should work.
