### ISSUE TITLE
Translated element spacing can be improved 

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#679]
### Steps to reproduce the problem

1. On desktop, go to any translated page, [for example](https://ja.learn.qiskit.org/course/examples/locale)
2. Scroll down to the bottom of the left-side panel
4. See how the characters are breaking to a new line

### What is the current behavior?

Characters are breaking to a new line

### What is the expected behavior?

The UI would look cleaner if we either truncated the text, or, reduced some of the right padding to allow the content to fit better

### Screenshots (optional but very helpful)
![Screen Shot 2022-02-01 at 1 53 00 PM](https://user-images.githubusercontent.com/6276074/152058065-ea18f74e-fa91-4700-8761-b8a002cb2b41.png)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
