### ISSUE TITLE
Extra characters displayed instead of markdown text

### ISSUE THREAD

**Issue by Amey-2002** [Qiskit/platypus#680]
1. Go to 'Data Encoding module in Quantum Machine Learning course'
2. Scroll down to 'Amplitude encoding section'
 

### What is the current behavior?

Extra characters '\$' are displayed along with plain text.
eg. \$N$

### What is the expected behavior?

The given text should be displayed in markdown format.

### Screenshots (optional but very helpful)

![Screenshot (55)_LI](https://user-images.githubusercontent.com/90676651/152160583-adf8b74d-3e2c-4d5d-b21c-a8120ba709f2.jpg)

### Environment (optional but very helpful)
 - Device: Laptop
 - OS:  Windows
 - Browser:  Chrome

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
