### ISSUE TITLE
Fix the preview PR link

### ISSUE THREAD

**Issue by abdonrd** [Qiskit/platypus#684]
Right now all the preview PR links are not working well.

When you click, it redirects you to the production site.
Example with this from https://github.com/Qiskit/platypus/pull/681:
- https://platypus-pr-681.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/

Redirects you to: https://qiskit.org/textbook-beta/

**Comment by abdonrd** [comment]
Related to this, I think it also leads to a bad development experience:

1. Run `npm start`
2. Open http://localhost:8080 and expect the app working, but it redirects to https://qiskit.org/textbook-beta

**Comment by eddybrando** [comment]
As described in the README:

>After the application has started, the site will be available at http://localhost:8080/, but the index route will redirect to an external landing page.
>
>In order to test the application locally, you can visit a specific course page, like https://localhost:8080/course/ch-prerequisites/.

https://github.com/Qiskit/platypus#setup

This is not a bug, but we can open an issue to request an improvement for DX or start a discussion about how to improve this.
