### ISSUE TITLE
Document how to check user accounts locally

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#686]
Currently, all of our User Account work is in a [feature branch](https://github.com/Qiskit/platypus/tree/feature/user-account), but we don't have a clear way of knowing how to properly test the entire flow. 

I believe that some members of the team know how to do this, locally. (Actually, Va has [mentioned](https://github.com/Qiskit/platypus/pull/341#discussion_r792064531) that he was able to test locally, using Google)

For the sake of reviewing, it would be great if we could document somewhere, how to properly test the login flow so that we can confidently ship new features and understand any gaps in our delivery.

- [ ] Provide documentation on the process for _How to test the full user login flow_, even if it's in a local environment.

**Comment by Tansito** [comment]
https://github.com/Qiskit/platypus/wiki/Configuration

Here it is!
