### ISSUE TITLE
Minor typos in qml course module

### ISSUE THREAD

**Issue by Amey-2002** [Qiskit/platypus#698]
### Steps to reproduce the problem

1. Go to 'quantum machine learning course'
2. Click on 'Quantum feature maps and kernels module'
3. Scroll down to 'Quantum support vector classification' section
4. See line " The nearest training datapoints to the seperating hyperplan in each class are called “support vectors”.

### What is the current behavior?
The words "seperating hyperplan" are misspelled.

### What is the expected behavior?
The correct sentence should be " The nearest training datapoints to the separating hyperplane in each class are called “support vectors”.

### Screenshots (optional but very helpful)
![Screenshot (78)_LI](https://user-images.githubusercontent.com/90676651/152823346-b66fdb0d-37e2-4d77-96fa-fbd9754c6772.jpg)

**Comment by eddybrando** [comment]
@frankharkins, could you please help us confirm this?
