### ISSUE TITLE
[Content UI] Formulas Formatting Issues (overlapping)

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#709]
### Steps to reproduce the problem

1. Go to [Quantum feature maps and kernels](https://learn.qiskit.org/course/machine-learning/quantum-feature-maps-kernels)
2. See error in formula

### What is the current behavior?

Attached screenshot. The formula kerning is a inconsistent and overlaps with itself

<img width="859" alt="Screenshot 2022-02-10 at 11 08 07" src="https://user-images.githubusercontent.com/6241840/153448217-1960c957-3892-42f8-bce0-22cfe1a8a483.png">

### What is the expected behavior?

We shouldn't be seeing any overlapping text in formula formatting

### Screenshots (optional but very helpful)

If applicable, please add screenshots or video captures to help explain the problem.

### Environment (optional but very helpful)
 - Device: MacBook Pro 16
 - OS: macOS 12.0.1
 - Browser: Safari 15.1

### Additional context (optional)

Add any other context that could help debug the problem.

**Comment by eddybrando** [comment]
Confirming bug in **Safari** 15.4, but formatting works fine in **Chrome** 101.0.4951.64.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
