### ISSUE TITLE
[Content UI] Overlapping Equations

### ISSUE THREAD

**Issue by gracelindsell** [Qiskit/platypus#710]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-algorithms/quantum-teleportation
2. scroll down to Step 2
3. See overlapping equation text

### What is the expected behavior?
the content of the equations within Step 2 overlap with the glossary content to the right 

### Screenshots (optional but very helpful)
<img width="1067" alt="Screen Shot 2022-02-10 at 11 08 57 AM" src="https://user-images.githubusercontent.com/89415444/153448896-7bed5286-bf44-46e7-a7cc-67a3107a0c11.png">

### Environment (optional but very helpful)
 - Device: Mac OS
 - Browser: Safari

**Comment by korgan00** [comment]
It no longer happens since the layout refactor. Can you confirm @gracelindsell ? Maybe you have to hard-refresh the content to update CSS.
