### ISSUE TITLE
404 link in "Unsupervised learning"

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#711]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/machine-learning/unsupervised-learning
2. Scroll down to "Quantum Boltzmann Machines"
3. Click on "quantum Boltzmann machines page"
4. Be redirected to a 404 page

### What is the current behavior?

The link points to a 404 page.

### What is the expected behavior?

The link should point to an available page.

### Screenshots (optional but very helpful)

![Screenshot 2022-02-10 at 17 14 24](https://user-images.githubusercontent.com/22047320/153449105-4487c547-c785-4b55-9e03-07a42a7f4f31.png)

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: MacOS
 - Browser: Chrome

**Comment by techtolentino** [comment]
@frankharkins -- do you know where this link should point to?
