### ISSUE TITLE
[Code Cell UI] Code Block copy button formatting Issue across multiple Textbook pages

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#712]
### Steps to reproduce the problem

1. Go to [Quantum Feature Maps and Kernels](https://learn.qiskit.org/course/machine-learning/quantum-feature-maps-kernels), or [Quantum Generative Adversarial Networks](https://learn.qiskit.org/course/machine-learning/quantum-generative-adversarial-networks)
3. Scroll down to a code block

### What is the current behavior?

The copy button isn't right aligned, the copy hover text is in the middle of the block

<img width="710" alt="Screenshot 2022-02-10 at 11 13 10" src="https://user-images.githubusercontent.com/6241840/153449199-9464462b-39fd-4927-8924-c6f2f91e34a1.png">

### What is the expected behavior?

At the very least, the copy button should be on the right of the block. As for the hover... @JRussellHuffman / @gracelindsell?

### Screenshots (optional but very helpful)

If applicable, please add screenshots or video captures to help explain the problem.

### Environment (optional but very helpful)
 - Device: MacBook Pro 16
 - OS: macOS 12.0.1
 - Browser: Safari 15.1

### Additional context (optional)

Add any other context that could help debug the problem.

**Comment by frankharkins** [comment]
@pandasa123, I think this was fixed with the new code cell component - can we close this now?
