### ISSUE TITLE
[Code Cell Code] Pulse page: runnable cells break due to class rename | accessing higher energy states with qiskit pulse

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit/platypus#714]
### Steps to reproduce the problem

1. Go to 'https://learn.qiskit.org/course/quantum-hardware-pulses/accessing-higher-energy-states-with-qiskit-pulse'
2. Scroll down to '0. Getting Started'
3. Click on 'Run' in a first cell

### What is the current behavior?

First runnable cell emits an error
```
ImportError: cannot import name 'SamplePulse' from 'qiskit.pulse.library' (/srv/conda/envs/notebook/lib/python3.8/site-packages/qiskit/pulse/library/__init__.py)
```

### What is the expected behavior?

- Cell should run without error.
- `SamplePulse` was deprecated and renamed to `qiskit.pulse.library.Waveform`. Need to rename in the notebook too. 

### Screenshots (optional but very helpful)

<img width="783" alt="Screen Shot 2022-02-10 at 11 07 06 AM" src="https://user-images.githubusercontent.com/8796709/153447535-6b4ecc48-c1a8-4faa-9c8c-e5befb23f442.png">

### Environment (optional but very helpful)
 - Device: MacBook
 - OS: MacOS
 - Browser: Chrome

**Comment by eddybrando** [comment]
Bug confirmed:

![Image](https://user-images.githubusercontent.com/22047320/169536165-f2d1e077-2d97-4a2c-ad2b-6c667cf77889.png)

**Comment by alexao8** [comment]
Reviewing this issue we saw it’s already solved it so we can close it. We found a new issue regarding this one:
https://github.com/Qiskit/platypus/issues/1405
