### ISSUE TITLE
Title on the contents section doesn't match title on sidebar panel

### ISSUE THREAD

**Issue by y4izus** [Qiskit/platypus#715]
### Steps to reproduce the problem

1. Go to ['Superdense Coding'](https://learn.qiskit.org/course/ch-algorithms/superdense-coding) page
2. Compare the first title under the Contents section with the one on the sidebar panel and the one on the text of the chapter

### What is the current behavior?

Titles doesn't match

### What is the expected behavior?

Titles should match

### Screenshots (optional but very helpful)

<img width="881" alt="Captura de pantalla 2022-02-10 a las 17 16 05" src="https://user-images.githubusercontent.com/17231966/153449758-f7ac7e9c-b846-4889-b9ac-20b4efa792ec.png">

**Comment by bopardikarsoham** [comment]
This issue can be closed now @y4izus. Thank you!

**Comment by eddybrando** [comment]
The update was done successfully but we're currently experiencing an unrelated issue with the production building. That's why we can't see the change live.

This has been fixed nonetheless.
