### ISSUE TITLE
[General UI] Ordered list aligned weirdly

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#716]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/machine-learning/unsupervised-learning
3. Scroll down to "References"
4. See how the ordered list numbers are aligned weirdly

### What is the current behavior?

The ordered list numbers are aligned to the bottom.

### What is the expected behavior?

The ordered list numbers should be aligned to the top.

### Screenshots (optional but very helpful)

![image](https://user-images.githubusercontent.com/22047320/153449909-a3105f85-a2ec-4a31-8564-68043daa5c03.png)

![Screenshot 2022-02-10 at 17 18 36](https://user-images.githubusercontent.com/22047320/153449976-00fb31d9-8f36-433e-b21e-918405c905b6.png)

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: MacOS
 - Browser: Chrome

**Comment by jhwatrous** [comment]
This behavior is caused by the fact that the *entire bibliography entry* is a (multiple line) link description. Other bibliography entries throughout the textbook provide links *after* the entries (which is a better way to do it for many reasons).

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
