### ISSUE TITLE
Review styles for h3 and h4

### ISSUE THREAD

**Issue by y4izus** [Qiskit/platypus#719]
Not sure if this it's intended so I'm gonna create a blank issue instead of a bug issue.

Styles for h4 are bigger than for h3 and that gives the impression that the h3 is a subsection of h4 and not the way it should be
<img width="712" alt="Captura de pantalla 2022-02-10 a las 17 23 35" src="https://user-images.githubusercontent.com/17231966/153451236-258a254c-499a-4eeb-af59-5e379f46882c.png">

Found in [Superdense coding](https://learn.qiskit.org/course/ch-algorithms/superdense-coding)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
