### ISSUE TITLE
Quantum Generative Adversarial Network -- Formula Formatting Issues

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#720]
### Steps to reproduce the problem

1. Go to [Quantum Generative Adversarial Network](https://learn.qiskit.org/course/machine-learning/quantum-generative-adversarial-networks)
2. See error in formula

### What is the current behavior?

Attached screenshot. The formula kerning is a inconsistent and overlaps with itself

<img width="698" alt="Screenshot 2022-02-10 at 11 27 11" src="https://user-images.githubusercontent.com/6241840/153451631-0fb7a206-e58e-4d15-9afa-55aea86e6ba1.png">

### What is the expected behavior?

We shouldn't be seeing any overlapping text in formula formatting

### Screenshots (optional but very helpful)

If applicable, please add screenshots or video captures to help explain the problem.

### Environment (optional but very helpful)
 - Device: MacBook Pro 16
 - OS: macOS 12.0.1
 - Browser: Safari 15.1

### Additional context (optional)

Add any other context that could help debug the problem.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
