### ISSUE TITLE
Grader: Improve mybinder configuration

### ISSUE THREAD

**Issue by Tansito** [Qiskit/platypus#726]
Enables environment configuration for `mybinder` and creates a dedicated repository for it

Related with #700

**Comment by Tansito** [comment]
New repository in https://github.com/qiskit-community/platypus-binder

This repo is temporal, waiting for the new repo in Qiskit organization.

**Comment by eddybrando** [comment]
We need to create a new repository in the Qiskit org. For this, we need to wait for @vabarbosa. 🙂

**Comment by vabarbosa** [comment]
@Tansito @eddybrando should we transfer  [`https://github.com/qiskit-community/platypus-binder`](https://github.com/qiskit-community/platypus-binder) to Qiskit org or do we want start with a new repo?

**Comment by Tansito** [comment]
My two cents to transfer it

**Comment by vabarbosa** [comment]
PR to update binder repo reference: https://github.com/Qiskit/platypus/pull/863

**Comment by eddybrando** [comment]
I guess this is now done and we can close the issue.

But please feel free to reopen it otherwise @vabarbosa, @Tansito.
