### ISSUE TITLE
[Code Cell Code] Heavy dependencies in executable cell

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit/platypus#728]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-applications/hybrid-quantum-classical-neural-networks-with-pytorch-and-qiskit#hybrid-4-8
2. Scroll down to cell with content
```python
# install packages needed for this specific page
!pip install torchvision
```
3. Click on `Run`
4. See how execution stuck on installation (probably due to torchvision is huge package to install)

### What is the current behavior?

Cell with installing torchvision take long time and simply stucks. 
Because torchvision is not installed all other cells can not be executed due to missed dependency.

### What is the expected behavior?

It would be good to preinstall torchvision and remove installation cell from page.

### Screenshots (optional but very helpful)
Stuck in here
<img width="773" alt="Screen Shot 2021-10-21 at 11 16 44 AM" src="https://user-images.githubusercontent.com/8796709/138705517-6b4a2529-8302-4cbc-8c8f-2e0310ce6bb8.png">

### Environment (optional but very helpful)
 - Device: Laptop (MacBook Pro 16 2019)
 - OS: MacOS 11.6 
 - Browser Chrome

**Comment by alexao8** [comment]
Solved issue. Merged #1418 into main.

https://github.com/Qiskit/platypus/pull/1418
