### ISSUE TITLE
User account: Investigate csrf approach

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#733]
Apart from this that I'm not 100% confident with this approach I'm fine with the rest of the things. I can open an issue to investigate it a bit more but by now I think we can go with it.

_Originally posted by @Tansito in https://github.com/Qiskit/platypus/pull/692#discussion_r807141671_

**Comment by eddybrando** [comment]
@Tansito, as discussed offline, we'll ask about this approach to get more info but pause the development of this for the moment, to prioritise other tasks.
