### ISSUE TITLE
Consider refactor: WidgetsManager + KernelManager + OutputRenderer

### ISSUE THREAD

**Issue by korgan00** [Qiskit/platypus#740]
There is poor documentation about the Jupyter-widgets and jupyterlab-manager. The current implementation is an adaptation of the thebelab plugin.
I think that we can omit `WidgetsManager` somehow.
If it is not possible, another idea is to use the `WidgetsManager` as the interface to manage kernels and the OutputRenderer.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
