### ISSUE TITLE
[Testing] Tests might saturate MyBinder requests

### ISSUE THREAD

**Issue by korgan00** [Qiskit/platypus#751]
I am not sure if this is a real problem, but I suspect it is. We have to take a look at it.

MyBinder is the service we are using to execute the python CodeCells remotely. It has a limited number of requests per hour that we can do.
When a page loads, it makes a request to connect with MyBinder and be ready to execute any code.
During the tests, there will be many requests visiting every page. Cypress clears the cookies very often so that it won't take advantage of the cached connection.

A possible solution is to put a cookie or localStorage key to prevent requests during testing.

**Comment by eddybrando** [comment]
@Tansito, @vabarbosa, do you consider this to be a bug?

**Comment by Tansito** [comment]
Mmm... Maybe yes, but definitely this is something that we should increase the priority and take a look whether it's a bug or not I think.

**Comment by vabarbosa** [comment]
this could be a high priority issue since it is can possibly impact users but i am havent heard of any issues, yet. 
after PR https://github.com/Qiskit/platypus/pull/954 the number of mybinder requests should be down significantly since we are no longer loading every single page.

**Comment by vabarbosa** [comment]
> Hi,
> 
> https://mybinder.org/ is receiving a huge traffic related to https://github.com/Qiskit/platypus-binder. At the moment, https://github.com/Qiskit/platypus-binder is driving more than half of the traffic in https://mybinder.org/
> 
> ![Screenshot 2023-06-20 at 15-53-58 Pod Activity - Dashboards - Grafana](https://user-images.githubusercontent.com/1506457/247139479-ba345c34-d6e6-4e7b-8276-5e2c98e8ef24.png)
> 
> https://mybinder.org/ is running with reduced capacity since May 2023 (details at https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f) and providing CPU time for Qiskit Textbook (
> 
> https://github.com/Qiskit/platypus/blob/dabb389dc39037a9501dd1082b9e1dd8413fc0de/frontend/vue/components/CodeExercise/KernelManager.ts#L44
> ) means declining CPU time for other users.
> 
> Will be possible to use [Pyodide](https://pyodide.org/) to run the code exercises for the textbook?

thank you @rgaiacs we are investigating

**Comment by vabarbosa** [comment]
@rgaiacs we've updated our application to (hopefully) significantly minimize the load on mybinder. 
this is just the first step. additional updates should be forthcoming as we continue to investigate solutions.
our sincerest apologies for any inconveniences or undo strain we may have been putting on mybinder and the mybinder team. thank you!

**Comment by rgaiacs** [comment]
@vabarbosa Thanks for the pull request. I will follow up tomorrow.

**Comment by rgaiacs** [comment]
@vabarbosa Thanks again for the pull request! The traffic on mybinder.org from https://github.com/Qiskit/platypus-binder dropped to 1/4 after https://github.com/Qiskit/platypus/pull/2132 was merged. ❤️ 

![Screenshot 2023-06-22 at 08-26-53 Pod Activity - Dashboards - Grafana](https://github.com/Qiskit/platypus/assets/1506457/87772ea7-c0ae-4163-9600-5d64af023238)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
