### ISSUE TITLE
Review Syllabus designs with Professors

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#753]
1. Reach out 3 Professors 
2. Ask 3 questions about their existing syllabus creation workflow
3. Show syllabus and take notes about feedback

**Comment by pandasa123** [comment]
Syllabus Review with Amir 

> Taught Quantum course to MIT undergrads 5 or 6 times over 5 years

**What do you think a Syllabus is?**

- Structured for a course
- Educational steps, one by one
- Time ordered
- Later material will draw on the things

**Syllabus Walkthrough** 

- Looks amazing and I can see how I would use this!
- Usually broken down by time, what’s in the material
- I like to keep my syllabi neat and few pages
- I don’t have links in my syllabi but I love the links to Qiskit textbook or Mike and Ike! And I can see the content with one click for my students 
- I’m emphasising using online resources like papers on ArXiV

**What should be in a Syllabus**

- I’d like a list of links to additional links…it changes from year to year 
- I do have a PDF Syllabus 

**Fields in here**

- The fields at the top are perfect!
- The very top section should have two versions with physical vs online. This is great for physical, but online but Instructors and TAs and Zoom links matter
- In a conventional syllabus 


**Workstreams**

- I can see this replacing my existing Syllabus. This is an interactive syllabus with links which is pretty great 
- I currently have a LaTex template. It’s not pleasant to work with…like with spilling sections etcs. LaTeX formatting is great but I’m open to using something else
- This Syllabus paves the way for me to share how I teach in the future
- There are other people who are teaching more advanced courses and I feel like they would love to share their course syllabi as well 


**Canvas / LMS**

- This online version is great and I don’t really need any other formats. This could reduce our need on Canvas…Canvas is really good but the issue it we have to pay for it…it’s good for organising content but it’s not good for content links or zoom recording links etc
- Homeworks are also in LaTeX PDFs. It’s easy for typing equations

**Comment by pandasa123** [comment]
Post-MVP items:

- Export to PDFs
- Custom links (is the content free-text not sufficient though?)
