### ISSUE TITLE
 Validate Grader Integration Feature with Professors

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#754]
Success Metric: 

- Number of problem sets or exams created
- Number of scores returned 

1. Reach out to 3 - 5 Professors 
2. Ask to integrate with ongoing course
3. Measure success metrics as described above

**Comment by pandasa123** [comment]
Hmm...seeing as our actual grader is internal, I think we need to adjust the following metric:

> Number of problem sets or exams created

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
