### ISSUE TITLE
Syllabus: Persist data of updating syllabus in Vuex/Pinia

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#772]
We need to store the state of the form being updated in the "Create a syllabus" page (created in https://github.com/Qiskit/platypus/issues/768) in a Vuex store to prepare for the development of the "Preview" tab.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
