### ISSUE TITLE
Syllabus: Create "Preview" tab in "Create a syllabus" page UI

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#773]
We need to create the "Preview" tab in the "Create a syllabus" page (created in https://github.com/Qiskit/platypus/issues/768) using the data from the Vuex store (developed in https://github.com/Qiskit/platypus/issues/772).

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
