### ISSUE TITLE
[Content UI] Unrendered Mathjax formula showing on page

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#794]
### Steps to reproduce the problem

1. Go to [the Multiple Qubits and Entangled States page](https://learn.qiskit.org/course/ch-gates/multiple-qubits-and-entangled-states#ex1)
2. Scroll down to the first exercise

### What is the current behavior?

a Mathjax formula is not rendered, and visible

### What is the expected behavior?

Either the formula should be hidden, or, it should render correctly

### Screenshots (optional but very helpful)

![Screen Shot 2022-03-07 at 11 56 38 AM](https://user-images.githubusercontent.com/6276074/157114267-f42b3eca-f567-41bd-80de-cce028e7dae8.png)

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: MacOS
 - Browser: Chrome

**Comment by korgan00** [comment]
update:
If you run the cell, the formula renders correctly. It is an issue with the pre-rendered output.

**Comment by frankharkins** [comment]
Fixed in https://github.com/Qiskit/platypus/pull/1427
