### ISSUE TITLE
User Account: Add a User Icon to the Textbook nav

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#796]
Following the comment [here](https://github.com/Qiskit/platypus/issues/258#issuecomment-1061164366)

In order to finish the User Account user story, we'll need a user icon that will allow users to log in.

**Comment by JRussellHuffman** [comment]
@pandasa123 are you proposing those as a dropdown under the user account button in the main header? If so, I would very much like to keep the dark mode UI switcher. I really don't want that to lose that work, especially because that work is like 95% done.

**Comment by pandasa123** [comment]
Oh yep definitely. I was under the impression that the switcher was still WIP

**Comment by JRussellHuffman** [comment]
form the user account [FINAL page in figma,](https://www.figma.com/file/SOnOgCGQIWx4oAlSFhIsIX/1972-User-account?node-id=158%3A1941) this is the designed login flow. Even if we don't have a drop down for MVP (which Randy persuaded me is best), this flow should still work.
