### ISSUE TITLE
Textbook content: sec. 6.2 S-gates confusing sentence

### ISSUE THREAD

**Issue by grossardt** [Qiskit/platypus#830]
Section 6.2 of the (old and new) textbook contains the following sentence:

> It is important to note that unlike every gate introduced in this chapter so far, the S-gate is not its own inverse!

Since the R_phi gate is introduced before, which is generally not its own inverse (obvious from the fact that S is a special case of it) this sentence might be better reformulated, maybe by explicitly naming

> It is important to note that unlike **the Pauli and Hadamard gates** introduced in this chapter so far, the S-gate is not its own inverse!

**Comment by soumya-s3** [comment]
Can I work on this issue. I am new to open source and this looks like a good one to start with.

**Comment by soumya-s3** [comment]
Can't find it on Qiskit/platypus. Opened a PR in LaBEQ-main/qiskit

**Comment by frankharkins** [comment]
@soumya-s3 the notebook is here: https://github.com/Qiskit/platypus/pull/797. I think the confusion is that '6.2' refers to the section within the notebook, but the original poster didn't specify which notebook contained the error. Please open a PR here as that repo isn't associated with this one.
