### ISSUE TITLE
As a developer, I would like to have the different platypus parts decoupled to be able to work efficiently

### ISSUE THREAD

**Issue by Tansito** [Qiskit/platypus#831]
## Background

Nowadays, the different parts of platypus are very dependent on each other. These dependencies cause that applying a change in one site produces side-effects in the whole platform.

In our first iteration, we had enough to fulfill the requirements. Many new features require new functionalities that take a longer development time due to the lack of support on the current framework.

## Goal

New architecture to support new developments coming in the future.

## Accepting criteria

- [ ] - Decoupling the converter
  - [ ]   -  Notebook to markdown
  - [ ]   - Render markdown
- [ ] - Content outsourcing
- [ ] - Unification and restructuring of the front end
- [ ] - API decoupling
- [ ] - More robust
- [ ] - Improve development time

### General setup & DevOps

- [ ] https://github.com/Qiskit/saiba/issues/3

### Frontend

- [x] Base project structure
- [x] Markdown to HTML converter
- [ ] Layout: Default / Base (https://github.com/Qiskit/saiba/milestone/2)
- [ ] Layout: User account (https://github.com/Qiskit/saiba/milestone/6)
- [ ] Layout: Content unit (https://github.com/Qiskit/saiba/milestone/3)
- [ ] Navbar with course structure

**Comment by lerongil** [comment]
This is a good outline. We may want to split this up a bit and/or add some context from the dev forum.
