### ISSUE TITLE
User account: Syllabus template and user account

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#837]
### Steps to reproduce the problem

1. Log in at `/account`
2. Go to `/syllabus/abc-123` or `/syllabus/create`
3. See that if a user is logged in, they cannot see the side bar

### Designs
[EDIT: Updated link]
Designs for this can be found [here](https://www.figma.com/file/f1QMqiXSgt2FCt0itvsA24/676-Professor-Syllabus?node-id=814%3A8646)

### What is the current behavior?

The user account sidebar doesn't show if a user is logged in

### What is the expected behavior?

- If a user is logged in, the user account sidebar should show
- a user can only see `syllabus/create` if they're logged in
- a user does not need to be logged in to see `syllabus/abc-123`, but if they are, the designs say that the sidebar should have `Classroom` highlighted, and the sidebar should show

**Comment by techtolentino** [comment]
tagging @JRussellHuffman and @gracelindsell just for visibility.

@eddybrando - please let me know if I should schedule a call so we can discuss the UX here... 

thanks

**Comment by JRussellHuffman** [comment]
Can someone post a URL I can follow to see the bug? From context, it seems like it should be learn.qiskit.org/syllabus/create or learn.qiskit.org/account/syllabus/create, but neither work for me. 

Happy to talk through the UX, but so far this sounds like a bug, but I probably don't have all the context yet.
