### ISSUE TITLE
(DRAFT) Handle "EULA not accepted" cases the same way for all routes

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#866]
We need to handle all the user flows that check routes / actions to see if the user has accepted the EULA before proceeding, consistently.

For this, we can use a "middleware" approach to protect routes with 1 central logic for this use cases.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
