### ISSUE TITLE
Update to Carbon 11

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#874]
The Carbon team recently released v11, along with a good set of [migration docs](https://www.carbondesignsystem.com/migrating/guide/overview/) for projects that need guidance. 

This is a good opportunity to ensure the Textbook is pulling in the latest version of Carbon, and could potentially help us replace the cdn approach that uses unpkg (called out [here in this PR](https://github.com/Qiskit/platypus/pull/871))

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
