### ISSUE TITLE
Equations not rendering correctly on right sidebar

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#880]
### Steps to reproduce the problem

This is a problem on most pages, but there's a good example on [this page](https://learn.qiskit.org/course/ch-states/representing-qubit-states).

### Screenshots
![Screenshot 2022-04-06 at 18 20 47](https://user-images.githubusercontent.com/36071638/162032173-70431ab5-db32-47c8-8f72-70b8b5eb7d4d.png)

### Environment
 - Device: Macbook
 - OS: OSX
 - Browser: Firefox / Chrome

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
