### ISSUE TITLE
Decouple widgets

### ISSUE THREAD

**Issue by korgan00** [Qiskit/platypus#890]
Right now Widgets uses $step from Mathigon to call the goal function.

That makes widgets coupled to Mathigon. We can modify them so we emit an event like "completed" and the parent should capture it and manage it.

We can give an extra step and install `pinia` or any other app state manager plugin so it will serve as a middleware.

Related to https://github.com/Qiskit/platypus/issues/889

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
