### ISSUE TITLE
Coordinate w/ Translation team

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#896]
Now that we have translations in Textbook beta, we need to coordinate with the Translation team to ensure that Crowdin is picking up our repo...

**Comment by vabarbosa** [comment]
we've met and discussed with the translation team. they have reviewed the content and outlined a plan for  handling translations. they will move forward with using GitLocalize and have put together [documentation for translators](https://github.com/Qiskit/platypus/blob/main/TRANSLATING.md) to start contributing. expect to see translation-related PRs  in the coming weeks as the content begins to get translated.
