### ISSUE TITLE
Wrong geometric intrepretation of computational basis

### ISSUE THREAD

**Issue by GeorgeGuannan** [Qiskit/platypus#900]
### Describe the issue

In the Qiskit online textbook -- Introduction to Quantum Computing. In the index "Amplitudes" of "Describing quantum computers", the textbook gives a geometric relation between these standard basis in a Hilbert space. In the picture, basis |-> directed to the wrong direction.

<img width="197" alt="image" src="https://user-images.githubusercontent.com/55653221/163039225-8a0a1d6c-d160-4f4f-9962-d47677f1a7f3.png">

### Describe what you expect to see

![image](https://user-images.githubusercontent.com/55653221/163039287-0a2c6e89-0b2b-4c2d-ad75-791c777e4dbd.png)

**Comment by themathqueen** [comment]
I can work on this

**Comment by frankharkins** [comment]
@themathqueen sorry I missed this comment. I've just made a PR using the solution proposed in #1790. There are two issues for the same problem so I'm going to close this in favour of #1790.
