### ISSUE TITLE
User account: sync progression between local storage and database

### ISSUE THREAD

**Issue by Tansito** [Qiskit/platypus#920]
Most of the use cases are described in the issue #258 . To summarise the idea would be:

- For new users: get its progress and store it in the database
- For registered users: use the information from the database
- For registered users but not logged in: print a message warning them that if they don't log in can loose its progress

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
