### ISSUE TITLE
Sync pages between qiskit-community/qiskit-textbook

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#921]
Some notebooks are out of sync between this repo and [qiskit-community/qiskit-textbook](https://github.com/qiskit-community/qiskit-textbook). E.g. "Representing qubit states" in this repo still uses `execute`, whereas this was removed in https://github.com/qiskit-community/qiskit-textbook/commit/a4c5360fa01927c72ab455f3612d5476ce784fbd. We need to pull in updates from [qiskit-community/qiskit-textbook](https://github.com/qiskit-community/qiskit-textbook), being careful not to lose any updates made on this repo.

**Comment by gprs1809** [comment]
@frankharkins, do you think I can try this? As you said, it requires being very careful.

**Comment by frankharkins** [comment]
@gprs1809 thanks, but I'm already working on it in https://github.com/Qiskit/platypus/pull/967

**Comment by gprs1809** [comment]
@frankharkins , I see. That's fine. Thank you!
