### ISSUE TITLE
When a Syllabus is published (via create), we should add /edit/<CODE> to history

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#944]
## Background

Minor QoL issues for a workflow that creates a Syllabus iteratively ( creates, publishes, edits, publishes, etc)

## Current Behaviour

1. Currently, when a user publishes a Syllabus, they do so on `https://learn.qiskit.org/syllabus/create`
2. The user gets redirected to `https://learn.qiskit.org/syllabus/<SYLLABUS-CODE>`
3. If a user wants to edit the Syllabus and they go back, they go back to `https://learn.qiskit.org/syllabus/create`

## Expected Behaviour

If a user is on a Syllabus page after publishing, and clicks "back", they should go to `https://learn.qiskit.org/syllabus/edit/<SYLLABUS-CODE>`

## Suggested Implementation

Before redirection, we should push `https://learn.qiskit.org/syllabus/edit/<SYLLABUS-CODE>` to [History](https://developer.mozilla.org/en-US/docs/Web/API/History_API)?

**Comment by pandasa123** [comment]
Also, when a user goes back to `/edit` after publishing, it looks like we're pulling stale form data rather than the latest Syllabus edits?

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
