### ISSUE TITLE
Anchor links are behind navbar

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit/platypus#945]
### Details

When you click in content link content scrolls below anchor itself

### How to repoduce?

- go to page https://learn.qiskit.org/course/ch-applications/hybrid-quantum-classical-neural-networks-with-pytorch-and-qiskit#hybrid-4-8
- click on sidebar content (ex [anchor-link](https://learn.qiskit.org/course/ch-applications/hybrid-quantum-classical-neural-networks-with-pytorch-and-qiskit#quantumlayer))
- see that the link itself is behind navbar

Screenshots: 
<img width="1771" alt="Screen Shot 2021-10-22 at 9 52 05 AM" src="https://user-images.githubusercontent.com/8796709/138465711-8cd58f53-4d74-4709-ad85-9f7fe16d8f97.png">

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
