### ISSUE TITLE
Megamenu course links should not be hard coded

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/platypus#955]
the megamenu containing links to all courses currently maintains [a hard-coded list of courses and links](https://github.com/Qiskit/platypus/blob/main/frontend/vue/components/constants/megaMenuLinks.ts).
this should obtained programmatically so if when course get added/changed the megamenu stays current

related https://github.com/Qiskit/web-components/issues/74

**Comment by frankharkins** [comment]
@vabarbosa can I have a go at this?

**Comment by vabarbosa** [comment]
> @vabarbosa can I have a go at this?

@frankharkins double check with @Tansito if he has not started on it. if not, then definitely go for it. he mentioned taking a look but i dont believe he has actually started, yet: https://github.com/Qiskit/platypus/pull/967#issuecomment-1120789272

**Comment by Tansito** [comment]
Sorry no, I was talking about review the PR not start with this issue. But let me know if we should prioritise this.

**Comment by frankharkins** [comment]
@Tansito I don't think this need prioritising, I just thought it seemed like a nice project to work on

**Comment by vabarbosa** [comment]
> Sorry no, I was talking about review the PR not start with this issue. But let me know if we should prioritise this.

@Tansito ah ok, my bad. i misunderstood.


> @Tansito I don't think this need prioritising, I just thought it seemed like a nice project to work on

@frankharkins feel free to assign this to yourself and have a go at it. any questions, just reach out. thanks.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
