### ISSUE TITLE
Check clipboard in "copy code to clipboard" functionality's Cypress test

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#96]
The Cypress test of the "copy code to clipboard functionality" in `cypress/integration/code-mirror/copy-code-to-clipboard.spec.js` (introduced in PR #91) doesn't currently check the clipboard to see if the code was indeed copied properly.

This is quite tricky since browsers might ask for permissions to access the clipboard's data, which might require a manual click, which is not trivial to automate.

This repository (https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__clipboard) shows a way in which we could automate this permissions, at least for Electron a Chrome tests.

Another approach that might be interesting considering is using a proxy for checking what should land in the clipboard, but not what does land in the clipboard for sure, since whatever happens after we tell the system to copy something to the clipboard is a side effect.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
