### ISSUE TITLE
Syllabus V2

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#972]
As a Professor, I want to be able to create a dynamic syllabus, so that I can curate the learning experience for my students. #676

We want to iterate Syllabus V1 based on professor feedback

## Background

Professors have a curriculum or general topics they want to teach their students. They typically turn to the Qiskit Textbook as a resource for hands-on experimentation. Currently, Professors have to painstakingly collect Qiskit Textbook links themselves, order a subset into a syllabus, and share via static documents

Currently, we're working with a few universities to test MVP1 and we'll prioritise and iterate based on feedback

## Goal

> The Syllabus should meet Professor needs and is ready to integrate into a classroom

## Acceptance Criteria:

TBD

## Design

[Current implementation](https://learn.qiskit.org/account/classroom)

## Tasks

[Syllabus v1.1](https://github.com/Qiskit/platypus/milestone/3):

- [x] #1001
- [x] #814
- [x] Adding a "create new section" in between sections (*new*)
- [x] Duplicate Syllabus (*new*)
- [x] #813

[Syllabus v1.2](https://github.com/Qiskit/platypus/milestone/2):

- [x] #772 
- [x] #773 

[Syllabus v1.3](https://github.com/Qiskit/platypus/milestone/4):

- [x] #775 
- [x] #815

[Syllabus v.1.4](https://github.com/Qiskit/platypus/milestone/5):

- [x] #776 
- [x] #777

**Comment by pandasa123** [comment]
Todd Zimmerman is trying to start an Introduction to QC course using Qiskit...starting in June 2022

- **Text formatting in the Content box**. My preference is Markdown, especially since I can render LaTeX in there (not crucial) 
- Main benefit: I can easily include the Qiskit 
- Link to other resources: Other things on the web, as well as my Canvas LMS 
- List of assignments and dates in the Syllabus that open in the window
- **Links to Assignments would be critical since it's a living document** 
- "Course Title" --> "Section Title"
- "I'd like to put assignments here but it could get long...I want to have a sidebar with the sections"

Other:

- "I can do it better" for Labs...the idea is to make changes to them. LaTeX files are preferred. Markdown is fine too. Jupyter Notebooks are definitely the way to go. PICUP 
- **"I've been desperate for some sort of autograding".**...GradeScope is terrible. NBGrader is hard too

**Comment by pandasa123** [comment]
Review with Tzu-Chieh Wei, Stony Brook, Spring 2023

**Syllabus**

- Really easy structure
- **Can I add content into the Description? I want to add other material like papers and Youtube videos** -- loved the Rich Text Editor
- **I will definitely use this** and I want to collect feedback. It's way better than the Syllabus on my website. Mine is just listing material...but since you're having rich text, I can put everything there! I don't even need to have one for my own 
- **Adding the coding problems into the Syllabus would be a useful way to have students learn there**, maybe a Problem of the Day with statistics to see how they do on a day
- **Is there a way to include custom links into the Chapter bullets?** since I want to include any content 
- **Could I rearrange the sections?** It's easier than copy-pasting it which is helpful when I decide to change the order of what I teach. It's not a big issue though...BUT maybe it's a **better idea to be able to add a new section anywhere, rather than just the end** because than it's easier to move it around with that as is
- **If I see a Syllabus, can I duplicate it and edit it?** because then it's easier to copy and make my course from a good one

**Auto-Grader**

- I want to create my own problems: I want to create a Teleportation problem. I give you the Bell State and I want you to create the rest of the circuit. I'd like to change the Bell State and I want my students to change the classical control operation to adapt
- I want to change existing ones too...being flexible is great. I'm fine if my problems are added to a collection to

**Other**

- I want to sync my Assignments to Moodle...LMS sync for Students, Assignments, and Grades is exactly what he needs
- I'm going to create material for Summer and let you know how it goes

**Comment by pandasa123** [comment]
## Syllabus

**Startup issues**

- Hard refresh
- Expectations with link embeds

**Formatting wish-list**

- Heading / Font Sizes
- LaTeX

**New feature**

- I don't really use click-through statistics
- Export to Canvas (HTML format)
- He will get feedback from students

## Auto-Grader

**What do I need**

- Number of attempts
- Time

**Remediation**

- Errors / student input (above and beyond current systems)..."the problem with preformed answers...it's hard to tell what students are doing wrong. I would _like to_ review all the code but I don't have the time without a TA. **Classifying** _how_ they got it wrong would be great"
- Having a dump of student answers is great and use that to create guardrails in the future
- Paired-programming with the same incorrect answer type...remediation is a hard struggle. Classifying and giving feedback would be incredibly useful, even a video

**Writing Problems**

- I've been writing questions myself since I've been working on the Linear and Classical sections...once I get into the Quantum portions, I would want to use Thomas Wong's textbook, Bob Sutor's _Dancing with Qubits_
- I like to use the problem as inspiration, rather than just copying it over because they don't necessarily mesh up + copyright issues

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
