### ISSUE TITLE
Implement progress tracking on all pages (not just courses)

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#979]
Not strictly a bug, but updating a UX pattern. Initial implementation of progress tracking was just on courses. Now that we have gotten feedback and input, it's clear that the best experience is to include it across all pages.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
