### ISSUE TITLE
Code cell styling can be improved

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#985]
### Steps to reproduce the problem

For example cell:
1. Go to [this page](https://learn.qiskit.org/course/machine-learning/training-quantum-circuits)
2. Scroll down to 'Instead of doing this manually, we can use Qiskit's Gradientclass...'

### What is the current behavior?

- ~Code cells have a maximum height so scroll vertically if the content is too tall~
  (fixed in #1019)
- The cells can't fit [79 characters](https://peps.python.org/pep-0008/#maximum-line-length) without scrolling horizontally
- There is a lot of unused space at the top and right of the cell which makes it hard to read sections with short code snippets.

<img width="500" src="https://user-images.githubusercontent.com/36071638/166737963-7f536a21-92c1-4f78-a662-4d6d85a45606.png">

### What is the expected behavior?

I expect code cells to ~grow~(fixed), fit 79 (or more) characters, and would prefer them to be more streamlined. I.e. look something like this:

<img width="500" src="https://user-images.githubusercontent.com/36071638/176225250-32c272c2-e459-4c83-86fc-cb286398f2ce.png">

### Environment (optional but very helpful)

 - Device: Macbook
 - OS: OSX
 - Browser: Firefox

**Comment by gprs1809** [comment]
Hey @frankharkins , do you expect that for any browser on any device, there shouldn't be any need to scroll? I am aware that one can customise the look of jupyter notebooks with css. I think for doing what you mentioned, one would have to make some changes to the scss files in the frontend folder, am I right?

**Comment by frankharkins** [comment]
I don't think the cells should ever scroll vertically, but should scroll horizontally if the lines are over 79 chars long. @korgan00 designed these cells so will know what needs changing.

**Comment by frankharkins** [comment]
Related: https://github.com/Qiskit/platypus/pull/967

**Comment by JRussellHuffman** [comment]
Related to #1250

**Comment by frankharkins** [comment]
Looks like this is fixed now!
![Screenshot 2022-07-21 at 16 37 44](https://user-images.githubusercontent.com/36071638/180254724-ffdaf396-bb04-4d23-b346-3e36373088d0.png)
