### ISSUE TITLE
platypus "backend" appears to be remote ? (running locally doesn't actually work)

### ISSUE THREAD

**Issue by chetmurthy** [Qiskit/platypus#986]
### Steps to reproduce the problem

This might be a known problem, or it might not even be a "problem".  I'm just reporting it in case it was overlooked.

1. Follow "Getting started"/"Setup" procedure precisely
2. Go to the chapter on "Visualizing entanglement" ( `/course/introduction/visualizing-entanglement` )
3. try to click thru the steps -- THIS SUCCEEDS
4. But I'm running locally, so I search "ps" for a python that might be associated with the "backend", and find none
5. So I fire up a jupyter notebook in the `notebooks/intro` and get an error.
### What is the current behavior?
```
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from hello_qiskit import run_puzzle

File ~/Hack/IBMQ/src/platypus/notebooks/intro/hello_qiskit.py:1, in <module>
----> 1 import hello_quantum
      3 exercises = [
      4     {
      5         'initialize': [],
   (...)
    107     }
    108 ]
    111 def run_puzzle(j):

File ~/Hack/IBMQ/src/platypus/notebooks/intro/hello_quantum.py:19, in <module>
     16 from ipywidgets import widgets
     17 from IPython.display import display
---> 19 from qiskit_textbook.widgets._helpers import _img
     21 darker_purple = (105/255, 41/255, 196/255)
     22 dark_purple = (165/255,110/255,255/255)

ModuleNotFoundError: No module named 'qiskit_textbook'
```
6. But then I go to the (old) `qiskit-textbook` repo, the subdirectory `qiskit-textbook-src`, and run `python setup.py install`
7. and now that same notebook works just fine.

### A clear and concise description of what the bug is.

The platypus local server doesn't use a local Python backend, and the code to support running the notebooks locally isn't part of the repo.  Perhaps the intent is that one should install the code from `qiskit-textbook/qiskit-textbook-src`, but that isn't documented anywhere.

### What is the expected behavior?

I guess, the "local server" should run locally, without a remote backend, and I should be able to run the example code locally, both in jupyter notebooks and in commandline python instances.

### Screenshots (optional but very helpful)

If applicable, please add screenshots or video captures to help explain the problem.

### Environment (optional but very helpful)
 - Device: Server, Intel x86_64
 - OS: Ubuntu 20.04
 - Browser: Chrome

### Additional context (optional)

Add any other context that could help debug the problem.

**Comment by frankharkins** [comment]
@chetmurthy I assume you're downloading the repo and opening the notebooks in the `notebooks` folder using Jupyter Notebook? If so, you're right that you need to install the `qiskit_textbook` package (instructions [here](https://github.com/qiskit-community/qiskit-textbook#installing-the-qiskit_textbook-package)).

A short term solution is to document this better in this repo, and in the pages that use the package. More generally though, this has caused a lot of confusion, especially between the main `qiskit` package and this `qiskit_textbook` package, so I would prefer to either wean out the `qiskit_textbook` package, or to go the other direction and get it on PyPI.

**Comment by chetmurthy** [comment]
Yes, I'm d/ling the repo, running locally by opening notebooks, which all works great!  I just wanted to make sure that the dependency on the old textbook repo was .... not an oversight.  So I'l close this issue.
