### ISSUE TITLE
Failed to connect to MongoDB!

### ISSUE THREAD

**Issue by Gopal-Dahale** [Qiskit/platypus#995]
### Steps to reproduce the problem

See `setup` section in ReadMe.

### What is the current behavior?

The command `npm start` does not work as expected. and throws an error. After successfully creating a python virtual environment, installing `requirements` files, running `npm install`, `npm run build` it fails on `npm start` with the following error.

Nothing is specified about MongoDB in the ReadMe file. 

```
> @qiskit/platypus@0.1.1 start
> ts-node --transpile-only -I public -P server/tsconfig.json server/app.ts

Running on port 8080 in development mode.
Trying in-memory Mongo DB...
Starting the instance failed, enable debug for more information
Starting the ReplSet failed, enable debug for more information
Failed to connect to MongoDB!
```

### What is the expected behavior?

As per ReadMe, we should see the Qiskit textbook website locally at  http://localhost:8080/.

### Screenshots (optional but very helpful)
The below screenshot shows the end of `npm run build` command.
![Screenshot from 2022-05-11 11-28-18](https://user-images.githubusercontent.com/49199003/167778985-80a69eca-0a7a-4337-96b5-3bb9d5391e50.png)
The screenshot below shows the output of `npm start` command.
![Screenshot from 2022-05-11 11-27-21](https://user-images.githubusercontent.com/49199003/167779130-c25efcaa-3001-44c5-a102-02148e7db0ce.png)

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: Ubuntu 22.04 LTS
 - Browser: Brave
 - Node version: v16.14.2
 - Python version: 3.10.4

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
