### ISSUE TITLE
Remember sidebar hidden/unhidden state

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#998]
### Steps to reproduce the problem

1. Hide the sidebar on any page
2. Navigate to another page, sidebar should be visible again

### What is the expected behavior?

The sidebar should remain hidden after navigating to a different page

### Environment (optional but very helpful)
 - Device: Macbook pro
 - OS: OSX
 - Browser: Firefox

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
